### ISSUE TITLE
Request for Android: statusbarColor and navigationBarColor

### ISSUE THREAD

**Issue by marksturm** [proyecto26/react-native-inappbrowser#1]
Hi,
thank you very much for this module, it works like a charm! 🥇 

But what is the
secondaryToolbarColor: 'black' for?

Anyways i really would like to have a chance to set the statusbarColor and navigationBarColor on my own for android, any suggestions?

**Comment by jdnichollsc** [comment]
thanks for the feedback, let me check. Any pull request is welcome! 👍

**Comment by marksturm** [comment]
Ok :) if i could, i would make a pull request but atleast i made some research:

1. Statusbar-Color:
not possible by customTabs.

2. Title-Color:
not possible by customTabs.
1 + 2: https://stackoverflow.com/questions/32533069/how-to-change-a-title-color-in-chrome-custom-tabs/32565940

3. navigationBarColor
also not possible by customTabs.

**Comment by jasperkuperus** [comment]
I think by now there is an API for setting the `navigationBarColor`:

https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent.Builder#setNavigationBarColor(int)

Can we reopen this issue? I'd love to be able to set the `navigationBarColor`.

**Comment by jdnichollsc** [comment]
That Android method is now deprecated, maybe this PR is related with this issue https://github.com/proyecto26/react-native-inappbrowser/pull/198
