### ISSUE TITLE
Apple rejecting build due to policy

### ISSUE THREAD

**Issue by bhaskardabhi** [proyecto26/react-native-inappbrowser#101]
I am using this repository for displaying Web view in my application. Everything goes fine but Apple's policy rejecting my build. It gives the following error:
I am getting the following error whenever I am trying to release my app for testing for ios:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I searched through the entire project and didn't find any reference to `UIWebView`. 

Following are versions of the library that I am using:

```
"react": "16.8.3",
"react-native": "0.59.8",
"react-native-inappbrowser-reborn": "^2.0.4",
```

Did you guys face the same issue? Or the issue is with something else but not this library?

**Comment by jdnichollsc** [comment]
This library is using **SafariServices/AuthenticationServices** instead of WebView, for more details here:
- https://developer.apple.com/documentation/safariservices?language=objc
- https://developer.apple.com/documentation/authenticationservices?language=objc
Check if you are you using WebView component of RN 👍

**Comment by mptorz** [comment]
I have just got the same email from apple. We didn't get these emails earlier, and we only display the webview in our app using `react-native-inappbrowser-reborn` :/ @bhaskardabhi let me know if you find a solution!

**Comment by jdnichollsc** [comment]
You can say that to **Apple** and paste the above links, let me know 👍

**Comment by jdnichollsc** [comment]
Also, the correct word here is `system browser`, not `webview`... so take care of this because Apple is Apple ¯\_(ツ)_/¯

**Comment by jdnichollsc** [comment]
To understand more about Safari View Controller => https://developer.apple.com/videos/play/wwdc2015/504/

**Comment by bhaskardabhi** [comment]
Thanks @jdnichollsc . I will take that up with Apple support. @mptorz Sure, Will let you know if I find any solution.

**Comment by mptorz** [comment]
@bhaskardabhi To fix it:
https://github.com/facebook/react-native/issues/26255#issuecomment-526551990

**Comment by cinder92** [comment]
did you guys find any solution?

**Comment by mptorz** [comment]
Yea. We just added this to the podfile
```
post_install do |installer|
  react_project = Xcodeproj::Project.open("../node_modules/react-native/React/React.xcodeproj")
  react_project.main_group["React/Views"].files.each do |file|
    if file.path.match(/^RCTWebView/)
      file.remove_from_project
    end
  end
  react_project.save
end
```
