### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.

### ISSUE THREAD

**Issue by Rana-Muhammad-Amir** [proyecto26/react-native-inappbrowser#106]
Hello...
i am just trying to configure this in my project but i cant regret from this error(android, ios working fine). please gide regarding to this...
working fine on IOS
react-native version 0.60

> Task :react-native-inappbrowser-reborn:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
76 actionable tasks: 76 executed
Note: /Users/muhammadamir/Downloads/cybus/Iyke_mkobo-festivesave-4fa6cae4214a/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/muhammadamir/Downloads/cybus/Iyke_mkobo-festivesave-4fa6cae4214a/node_modules/react-native-inappbrowser-reborn/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java:12: error: package androidx.browser.customtabs does not exist
import androidx.browser.customtabs.CustomTabsIntent;
                                  ^
/Users/muhammadamir/Downloads/cybus/Iyke_mkobo-festivesave-4fa6cae4214a/node_modules/react-native-inappbrowser-reborn/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java:179: error: package CustomTabsIntent does not exist
  void applyAnimation(Context context, CustomTabsIntent.Builder builder, ReadableMap animations) {
                                                       ^
/Users/muhammadamir/Downloads/cybus/Iyke_mkobo-festivesave-4fa6cae4214a/node_modules/react-native-inappbrowser-reborn/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java:64: error: package CustomTabsIntent does not exist
    CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
                    ^
/Users/muhammadamir/Downloads/cybus/Iyke_mkobo-festivesave-4fa6cae4214a/node_modules/react-native-inappbrowser-reborn/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java:64: error: package CustomTabsIntent does not exist
    CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
                                                           ^
/Users/muhammadamir/Downloads/cybus/Iyke_mkobo-festivesave-4fa6cae4214a/node_modules/react-native-inappbrowser-reborn/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java:96: error: cannot find symbol
    CustomTabsIntent customTabsIntent = builder.build();
    ^
  symbol:   class CustomTabsIntent
  location: class RNInAppBrowser
/Users/muhammadamir/Downloads/cybus/Iyke_mkobo-festivesave-4fa6cae4214a/node_modules/react-native-inappbrowser-reborn/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java:134: error: cannot find symbol
      intent.putExtra(CustomTabsIntent.EXTRA_TITLE_VISIBILITY_STATE, CustomTabsIntent.NO_TITLE);
                      ^
  symbol:   variable CustomTabsIntent
  location: class RNInAppBrowser
/Users/muhammadamir/Downloads/cybus/Iyke_mkobo-festivesave-4fa6cae4214a/node_modules/react-native-inappbrowser-reborn/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java:134: error: cannot find symbol
      intent.putExtra(CustomTabsIntent.EXTRA_TITLE_VISIBILITY_STATE, CustomTabsIntent.NO_TITLE);
                                                                     ^
  symbol:   variable CustomTabsIntent
  location: class RNInAppBrowser
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-inappbrowser-reborn:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

**Comment by jdnichollsc** [comment]
Share a reproducible demo in order to debug this issue 👍

**Comment by Rana-Muhammad-Amir** [comment]
@jdnichollsc  i don't have demo....
i am trying to run a project from client for some fixes and currently it throws the above error....
i have checked everything is include corrctlly.....it's working fine on IOS
please help to figure it out.

**Comment by jdnichollsc** [comment]
So try to reproduce this issue from a new project and let me know...

**Comment by jdnichollsc** [comment]
Try this solution and let me know https://github.com/react-native-community/async-storage/issues/127#issuecomment-527146855

**Comment by naywin-programmer** [comment]
![react-native-android-error](https://user-images.githubusercontent.com/21998283/70912527-80429900-2042-11ea-85b0-6be01f0f57bf.png)
After removing .gradle folder and build folder inside android folder of react native project, everything is work for me.
