### ISSUE TITLE
Prevent the URL to Open some installed Application

### ISSUE THREAD

**Issue by ahmad6242** [proyecto26/react-native-inappbrowser#107]
I am experiencing this thing that i dont want to happen. 
for example if i open the URL to a website Booking.com and 
if there is an app for booking.com in my Mobile it will open that. 
i want to prevent the browser to open any app , it should just loads the URL. 
is there any possibility for that. ?
Please Help!
Thanks

**Comment by jdnichollsc** [comment]
We can't handle that as I know, because universal links are configured from another apps like booking app, but let me check 👍

**Comment by davidcort** [comment]
@ahmad6242 you can do it the next way:

`let link = url.replace('https','http')`

```
try {

        if (await InAppBrowser.isAvailable()) {
            
                await InAppBrowser.open(link, {
``` ....

The universal links use the protocol HTTPS, if the InAppBrowser receive a web address with HTTP show the web page. You can try  :)

**Comment by jdnichollsc** [comment]
ohhhh interesting 😄

**Comment by davidcort** [comment]
Works to me!! :D

**Comment by ahmad6242** [comment]
@davidcort But i have to use it for some online shopping websites, so i need to use https so the Users would know that they are secure in every way.  
is there any other possibility

**Comment by jdnichollsc** [comment]
@ahmad6242 are you debugging this behavior from Android or iOS?

**Comment by ahmad6242** [comment]
@jdnichollsc i have tried this from Android. But i need same for IOS also.

**Comment by jdnichollsc** [comment]
@ahmad6242 let me know if you find any official documentation to support this 👍

**Comment by claudiozam** [comment]
The http hack is not working for me. This old apacher cordova / ionic plugin do not open the installed application (for exmaple google drive URL).

https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller
https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/blob/1.6.0/src/android/ChromeCustomTabPlugin.java

**Comment by jdnichollsc** [comment]
Oh ok, it looks like we need to set the package of the Android intent, as we can see here https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/blob/master/src/android/helpers/CustomTabsHelper.java#L63

**Comment by claudiozam** [comment]
This is the IOS implementation https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/blob/master/src/ios/SafariViewController.m

Also the plugin does not open the App.

Thanks

**Comment by jdnichollsc** [comment]
Awesome, let me verify as asap

**Comment by jdnichollsc** [comment]
mmm I can't identify how to handle that, but any pull request is welcome!

**Comment by jdnichollsc** [comment]
Please debug the last changes from `develop` branch, there's a pending PR of the new version 3.5.0 https://github.com/proyecto26/react-native-inappbrowser/pull/195
