### ISSUE TITLE
Android Build is Failing

### ISSUE THREAD

**Issue by kuljeetsingh31** [proyecto26/react-native-inappbrowser#11]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-inappbrowser-reborn:releaseCompileClasspath'.
> Could not find support-compat.jar (com.android.support:support-compat:27.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-compat/27.1.1/support-compat-27.1.1.jar

**Comment by jdnichollsc** [comment]
Any pull request is welcome! 👍

**Comment by pavelkrcil** [comment]
In case of this error, you need to ignore android support module in ```build.graddle```

```
compile(project(':react-native-inappbrowser-reborn')){ exclude group: 'com.android.support' }
```

May be it would be nice to mention this in manual installation documentation.

**Comment by jdnichollsc** [comment]
@pavelkrcil what's that module? do you know other plugins, examples to support multiple sdk versions? I can't see any example from the documentation

**Comment by jdnichollsc** [comment]
Done, check the last version from npm!

**Comment by kuljeetsingh31** [comment]
Hi @jdnichollsc, 
First of all thanks for your precious time.
Have installed latest plugin from npm repo but when building app it was giving below error:

/Users/kuljeetkakkar/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/95e09f6dccd9f5c14aba58f25aca898b/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.
    
/Users/kuljeetkakkar/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/95e09f6dccd9f5c14aba58f25aca898b/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/ttcIndex not found.
    
error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to process resources, see aapt output above for details.

My Android Configurations is as follows:
buildToolsVersion = "27.0.3"
minSdkVersion = 16
compileSdkVersion = 27
targetSdkVersion = 26
supportLibVersion = "27.1.1"

Tried google the issue and found this https://stackoverflow.com/a/51474321.

So I changed my android configuration to
buildToolsVersion = "27.0.3"
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 27
supportLibVersion = "28.0.0"

The build was successful with this. InAppBrowser worked perfectly when app is launched in debug mode.

But when tried the same in release mode the app crashed. Tested it on android 6 and android 7.

I have MI phone with android 7 which gave me the below error logs when the app crashed.

org.a.a.e: Subscriber class com.proyecto26.inappbrowser.b and its super classes have no public methods with the @Subscribe annotation
	at org.a.a.m.a(Unknown Source)
	at org.a.a.c.a(Unknown Source)
	at com.proyecto26.inappbrowser.b.a(Unknown Source)
	at com.proyecto26.inappbrowser.RNInAppBrowserModule.open(Unknown Source)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source)
	at android.os.Looper.loop(Looper.java:163)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:760)

**Comment by ravikumar-yadav** [comment]
> In case of this error, you need to ignore android support module in `build.graddle`
> 
> ```
> compile(project(':react-native-inappbrowser-reborn')){ exclude group: 'com.android.support' }
> ```
> 
> May be it would be nice to mention this in manual installation documentation.

It worked. I was getting issue in one plus

**Comment by jdnichollsc** [comment]
> > In case of this error, you need to ignore android support module in `build.graddle`
> > ```
> > compile(project(':react-native-inappbrowser-reborn')){ exclude group: 'com.android.support' }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > May be it would be nice to mention this in manual installation documentation.
> 
> It worked. I was getting issue in one plus

Hello mate, are you using android support or AndroidX?

**Comment by ravikumar-yadav** [comment]
> > > In case of this error, you need to ignore android support module in `build.graddle`
> > > ```
> > > compile(project(':react-native-inappbrowser-reborn')){ exclude group: 'com.android.support' }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > May be it would be nice to mention this in manual installation documentation.
> > 
> > 
> > It worked. I was getting issue in one plus
> 
> Hello mate, are you using android support or AndroidX?

I have commented //  supportLibVersion = "29.0.0" in android->build.gradle.

ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
      //  supportLibVersion = "29.0.0"
        androidXAnnotation = "1.2.0"
        androidXBrowser = "1.3.0"
    }

**Comment by jdnichollsc** [comment]
mm ok, thanks for letting me know! <3
