### ISSUE TITLE
iOS Animations Cause App Crash

### ISSUE THREAD

**Issue by natehershey** [proyecto26/react-native-inappbrowser#112]
When I use `InAppBrowser.open` with `{animated: true}`, my app crashes.  Looks like Apple decided to kill off the PartialCurl animation in iOS 13 🙄 

I can get around this by turning animations off but it would be great to have animations working again.

**Comment by jdnichollsc** [comment]
I'm going to publish the changes to fix that, the way we're using to animate the modal, so let me confirm you when we finish to debug my changes, because navigating back the animation is not working as expected

**Comment by jdnichollsc** [comment]
Try the last version 3.2.0 and let me know 👍

**Comment by jdnichollsc** [comment]
@natehershey if you want we can continue this discussion here https://forums.developer.apple.com/thread/124765
