### ISSUE TITLE
Android: use openAuth without DeepLinking? Or in other words: what exactly does redirectUrl do?

### ISSUE THREAD

**Issue by TheWirv** [proyecto26/react-native-inappbrowser#113]
Hi, I've been trying to implement PayPal payment in my app using the `openAuth()` method.

First, I send a ```POST``` request to PayPal to create an [Order](https://developer.paypal.com/docs/api/orders/v2/#orders_create) and get (among other things) an approval URL as response. This approval URL is a typical paypal.com link which the app then opens via `InAppBrowser`, so that the end user can approve the payment. This ```POST``` request also includes a mandatory parameter `return_url`, which I set to `'https://www.google.com'` at the moment. Consequently, after the end user has approved payment, PayPal redirects to Google, and this all works perfectly fine.

Now to my question/problem: I have written a `Browser` wrapper class for `InAppBrowser` that has an `openLink()` method which utilizes `openAuth()` in a fashion, kind of like this:
```javascript
openLink = async (url, auth = false, redirectUrl?) => {
  try {
    // this.isAvailable is set at application start
    if (this.isAvailable) {
      console.log(
        `opening ${Platform.ifIosOrAndroid('Safari View Controller', 'Chrome Custom Tab')}...`,
      );

      const browserConfig = {
        // iOS Properties
        dismissButtonStyle: 'cancel',
        preferredBarTintColor: '#453AA4',
        preferredControlTintColor: 'white',
        readerMode: false,
        animated: true,
        modalPresentationStyle: 'overFullScreen',
        modalTransitionStyle: 'partialCurl',
        modalEnabled: true,
        // Android Properties
        showTitle: false,
        toolbarColor: Colors.payPalBlue,
        secondaryToolbarColor: 'white',
        enableUrlBarHiding: true,
        enableDefaultShare: false,
        forceCloseOnRedirection: false,
        // Specify full animation resource identifier(package:anim/name)
        // or only resource name(in case of animation bundled with app).
        animations: {
          startEnter: 'slide_in_right',
          startExit: 'slide_out_left',
          endEnter: 'slide_in_left',
          endExit: 'slide_out_right',
        },
        waitForRedirectDelay: auth ? 1000 : 0,
      };

      if (auth) {
        return await InAppBrowser.openAuth(url, redirectUrl, browserConfig);
      }

      return await InAppBrowser.open(url, browserConfig);
    } else {
      console.log(
        `unfortunately, not able to open ${Platform.ifIosOrAndroid(
          'Safari View Controller',
          'Chrome Custom Tab',
        )}...`,
      );

      Linking.openURL(url);
    }
  } catch (error) {
    console.error('An error occured in InAppBrowser:', error.message);
    Alert.alert('Exception occured in InAppBrowser', error.message);
  }
};
```
Then, in my code, I use it like this:
```javascript
Browser.openLink(approveUrl, true, 'https://www.google.com').then(result => {
  console.log('Browser result:', result);

  // DO STUFF
}
```
The thing is: `InAppBrowser.openAuth()` (or `openLink()`, for that matter) returns only when it closes. In my case, though, the only way to close it is manually tapping the dismiss button (_X_ on Android, _Done_ on iOS). I thought that passing the redirect URL to `openAuth()` would make `InAppBrowser` listen for a redirect to that URL and then close or do at least something. Is there a way to execute code (like, for example, calling `close()` method), once the user has been redirected to `redirectUrl`? Or is deep linking the only way to utilize `openAuth()`'s redirect mechanism?

I tried deep linking btw, and it doesn't work for me because I can't specify a "custom URI" as PayPal's `return_url` parameter. Doing so would throw something like an "Incorrect syntax" exception upon request. It has to be a valid internet address (aka, starting with "http" or "https", I guess).

I hope you can help me. The docs/README doesn't really make it clear what `openAuth()`'s `redirectUrl` parameter achieves or how it works. Please, shed some light on this, thank you! :)

**Comment by jdnichollsc** [comment]
Try using universal links instead of deep linking and let me know 👍 
PD: Other option is redirecting the users to a custom web page having another redirection to the deep link of your app :)

**Comment by jdnichollsc** [comment]
>what exactly does redirectUrl do?

About this question, check the validation when the user is redirected from the browser https://github.com/proyecto26/react-native-inappbrowser/blob/master/index.js#L167

**Comment by TheWirv** [comment]
> Try using universal links instead of deep linking and let me know 
> PD: Other option is redirecting the users to a custom web page having another redirection to the deep link of your app :)

Hey, thanks for the reply. Universal links won't work for me because that's iOS exclusive, as far as I understand.
Is deep linking the only way here? Because the only thing I want is for the InAppBrowser to be dismissed after the redirect, that's it.

**Comment by TheWirv** [comment]
> > what exactly does redirectUrl do?
> 
> About this question, check the validation when the user is redirected from the browser https://github.com/proyecto26/react-native-inappbrowser/blob/master/index.js#L167

I'm gonna have a look into this, thanks.

**Comment by 2xSamurai** [comment]
@TheWirv Can you tell me how you achieved this. I too just want to dismiss the inappbrowser after successful payment. Is there any simple way to achieve this. Thank you

**Comment by TheWirv** [comment]
> @TheWirv Can you tell me how you achieved this. I too just want to dismiss the inappbrowser after successful payment. Is there any simple way to achieve this. Thank you
> 
> PS: I need this for both Android and iOS

I found out that there is no way to provide a redirect link in terms of an http link, it works only via deep linking as far as I know. My advantage was that we are concurrently building an API, so I had my backend team provide and endpoint that does a redirect to a deep link. Meaning, I could pass an http link to PayPal, which would be our API endpoint and then our backend redirects to `android://...` which causes the InAppBrowser to direct back to the app.

Does that make any sense for you? If I should clarify any further, just let me know. :)

**Comment by 2xSamurai** [comment]
@TheWirv I think I understand. But I do have a question. 

Can we auto close the Inappbrowser using deep linking?
 
Thank you for your time and response.

**Comment by TheWirv** [comment]
> @TheWirv I think I understand. But I do have a question.
> 
> Can we auto close the Inappbrowser using deep linking?
> 
> Thank you for your time and response.

Yes, of course. That's exactly what you have to do. Set up deep linking in your navigator via the React Navigation tutorial, then create your `getDeepLink` helper function and use that to provide a redirect deep link, e. g. `sampleapp://backtoapp`, to the website you're opening with the InAppBrowser's `openAuth` function.

Afterwards, the website you're using to somehow authenticate or whatever should redirect to that deep link and that's what the InAppBrowser is actually listening for. So when it sees a redirect to a deep link, it closes and sends you to the location that has been set up (in navigation) for that specific deep link.

As I said, if the website doesn't support non-http:// format URI's, it would be helpful to have your own endpoint as a workaround. The endpoint obviously has a https:// URL, but then redirect to your desired deep link, e. g. `sampleapp://backtoapp`. At least that's how it works perfectly for us.

**Comment by 2xSamurai** [comment]
> PS: Taking your question really literally, I have to say: No. You can't "auto close" the InAppBrowser using deep linking. At least that's not how it works. Rather, you tell the web site you're opening to navigate to a specific URI after completion that is no internet address and belongs to the app. And when the InAppBrowser sees the web site wanting to navigate to the app, it closes as a side effect and takes you where you want to go.

You are a lifesaver. Thank you.

**Comment by TheWirv** [comment]
@2xSamurai You're welcome! :)

**Comment by Ajmal0197** [comment]
https://dev.to/ajmal0197/react-native-twitch-auth-using-deeplinking-and-react-native-inappbrowser-reborn-1hff

**Comment by Riaz5687** [comment]
@TheWirv i am having the same issue and i am using stripe payment. Could you please help me in this " how to close the inappbrowser after payment successed.

**Comment by see2ever** [comment]
you can use a webpage to redirect back to app, meanwhile, the auth popup will close.

// webpage:
window.location.href = 'scheme://xxxx'

// app:

InAppBrowser.openAuth({
  redirect_url: 'url_of_middle_webpage'
}, 'scheme://xxxx')
