### ISSUE TITLE
Bundling failed with runtime error after using RNInAppBrowser

### ISSUE THREAD

**Issue by nihp** [proyecto26/react-native-inappbrowser#125]
I am getting the following errors while running the app in iOS. In terminal it shows the following errors

Anyone have any solution for this

```

react-native-inappbrowser-reborn/ios/RNInAppBrowser.h:10:64: no type or protocol named 'UINavigationControllerDelegate'
@interface ModalSafariViewController : UINavigationController <UINavigationControllerDelegate>
  ^       ~
❌  error: cannot find interface declaration for 'UINavigationController', superclass of 'ModalSafariViewController'
@implementation ModalSafariViewController
                                                              ^
❌  error: 'ModalSafariViewController' cannot use 'super' because it is a root class


❌  error: 'ModalSafariViewController' cannot use 'super' because it is a root class



```

**Comment by juansimon18** [comment]
Getting this error too, react-native-inappbrowser-reborn 3.3.2.

<img width="915" alt="Screen Shot 2019-11-20 at 10 21 04 AM" src="https://user-images.githubusercontent.com/45775350/69251495-79c61c00-0b7f-11ea-9edf-910ea54bb730.png">

**Comment by jdnichollsc** [comment]
Very odd, @juansimon18 what version of iOS are you using? We're checking to include that protocol only with iOS >= 13 https://github.com/proyecto26/react-native-inappbrowser/blob/master/ios/RNInAppBrowser.m#L220

**Comment by juansimon18** [comment]
Yeah @jdnichollsc, it seems very odd.

Im using iOS 12.4, right now im downloding an iOS simulator with 12.0 version to test it there.

**Comment by juansimon18** [comment]
@jdnichollsc also getting the same error with the example, im using Xcode: 10.3 and iOS: 12.4

**Comment by jdnichollsc** [comment]
@juansimon18 can you update Xcode?

**Comment by nihp** [comment]
@jdnichollsc 
I am getting 11 errors
![Screenshot 2019-11-21 at 10 31 55 AM](https://user-images.githubusercontent.com/36992338/69305624-af840700-0c4a-11ea-802a-2c27ea2ad711.png)


![Screenshot 2019-11-21 at 10 31 40 AM](https://user-images.githubusercontent.com/36992338/69305501-3d132700-0c4a-11ea-857d-f7d56d2b895f.png)

**Comment by nihp** [comment]
@jdnichollsc Did you have any other solution except Xcode version update

**Comment by nihp** [comment]
@juansimon18 In this comment they mentioned as we can run iOS 13.1 in Xcode 10 also. Did you got any solution? https://gist.github.com/steipete/d9b44d8e9f341e81414e86d7ff8fb62d#gistcomment-3011483

**Comment by jdnichollsc** [comment]
>Did you have any other solution except Xcode version update

Nope, but any pull request is always welcome! 👍

**Comment by jdnichollsc** [comment]
ohh ok, I can see the logs https://travis-ci.com/Pernett98/react-native-inappbrowser/jobs/259195993#L1034 🤔🤔🤔

**Comment by jdnichollsc** [comment]
Ok guys, try the last version 3.3.3! 👍
