### ISSUE TITLE
I am getting null is not an object (evaluating 'RNInAppBrowser')

### ISSUE THREAD

**Issue by nihp** [proyecto26/react-native-inappbrowser#126]
I have linked the RNInAppBrowser manually and it showing the error as "null is not an object (evaluating 'RNInAppBrowser')

Also If I run pod install it shows below error. But the RNInAppBrowser automatically shows in the pod file. I not added it manually.

[!] CocoaPods could not find compatible versions for pod "RNInAppBrowser":
  In Podfile:
    RNInAppBrowser (from `../node_modules/react-native-inappbrowser-reborn`)

Specs satisfying the `RNInAppBrowser (from `../node_modules/react-native-inappbrowser-reborn`)` dependency were found, but they required a higher minimum deployment target.

**Comment by jdnichollsc** [comment]
Please attach a reproducible demo or the link of your repository 👍

**Comment by nihp** [comment]
Okay

**Comment by jdnichollsc** [comment]
What version of Xcode are you using?

**Comment by nihp** [comment]
I am using Xcode 10.1

**Comment by jdnichollsc** [comment]
Because you can't use native plugins from Expo 🤔

**Comment by jdnichollsc** [comment]
> Why it not worked in expo?

Check here: https://docs.expo.io/versions/v35.0.0/introduction/faq/
>Managed Expo projects don't support custom native code, including third-party libraries which require custom native components. In a managed project, you only write JavaScript.

**Comment by jdnichollsc** [comment]
Try the last version 3.3.3! 👍

**Comment by Devecstatic** [comment]
I'm still having this issue 
<img width="561" alt="image" src="https://user-images.githubusercontent.com/35352046/71770006-c8443580-2ef5-11ea-95a5-0cfa2efb50af.png">

[iOS]

**Comment by jdnichollsc** [comment]
@anagar23 @Devecstatic instead of put bad reactions, I invite you to attach the code of your project or send a link of your repository, have a happy new year! 👍

**Comment by Devecstatic** [comment]
Nevermind, I figured it out. I was adding it to a third party NPM when I should be also adding it to the client

**Comment by sadikyalcin** [comment]
@jdnichollsc I'm having the same issue. RN: 0.61.5

```
async openLink() {
    console.log('@browser: ', InAppBrowser);
    try {
      await InAppBrowser.isAvailable();
      InAppBrowser.open('https://www.google.com', {
        // iOS Properties
        dismissButtonStyle: 'cancel',
        preferredBarTintColor: 'gray',
        preferredControlTintColor: 'white',
        // Android Properties
        showTitle: true,
        toolbarColor: '#6200EE',
        secondaryToolbarColor: 'black',
        enableUrlBarHiding: true,
        enableDefaultShare: true,
        forceCloseOnRedirection: true,
      }).then(result => {
        Alert.alert(JSON.stringify(result));
      });
    } catch (error) {
      Alert.alert(error.message);
    }
  }
```

```LOG  @browser:  {"close": [Function close], "closeAuth": [Function closeAuth], "isAvailable": [Function isAvailable], "open": [Function open], "openAuth": [Function openAuth]}```

<img width="410" alt="Screenshot 2020-04-20 at 16 14 51" src="https://user-images.githubusercontent.com/8109619/79768062-2587b980-8322-11ea-868d-46b65222f98e.png">

**Comment by jdnichollsc** [comment]
@sadikyalcin as far as I know, this happens when Autolinking is not working as expected, can you try linking manually and let me know is this fix that problem?
Thanks in advance!

**Comment by sadikyalcin** [comment]
> @sadikyalcin as far as I know, this happens when Autolinking is not working as expected, can you try linking manually and let me know if this fix that problem?
> Thanks in advance!

Thanks for the quick response. Ye manual linking seems to work.

**Comment by jdnichollsc** [comment]
thanks for let me know! 👯

**Comment by Shrroy** [comment]
For the newest version of ReactNative `0.69` The autolinking might not work so you need to just run `pod install` and that is it.

```
cd ios
pod install
```
This will auto-link it
