### ISSUE TITLE
iOS Build issue

### ISSUE THREAD

**Issue by NKGS** [proyecto26/react-native-inappbrowser#128]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS build issue

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `react-native --version` to fetch it) 
"react": "16.8.3",
"react-native": "0.59.1"
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
"react-native-inappbrowser-reborn": "^3.3.2"

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

1) install react-native-inappbrowser-reborn
2) Followed steps provided :
In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
Go to node_modules ➜ react-native-inappbrowser-reborn and add RNInAppBrowser.xcodeproj
In XCode, in the project navigator, select your project. Add libRNInAppBrowser.a to your project's Build Phases ➜ Link Binary With Libraries
Run your project (Cmd+R)<
3) Gives below errors: 
"Cannot find protocol declaration for 'ASWebAuthenticationPresentationContextProviding'"
"Property 'presentationContextProvider' not found on object of type 'ASWebAuthenticationSession *'"
"Use of undeclared identifier 'UIModalPresentationAutomatic'; did you mean 'UIModalPresentationCustom'?"

Kindly provide with the solution at the earliest.

**Comment by jdnichollsc** [comment]
Try the last version 3.3.3! 👍
