### ISSUE TITLE
"UIModalTransitionStylePartialCurl to or from non-fullscreen view controller" iOS Error

### ISSUE THREAD

**Issue by invisiblemaker** [proyecto26/react-native-inappbrowser#130]
Hello,

I am getting the following issue when running in the iOS Simulator as well as my iPhone X:

Application tried to present UIModalTransitionStylePartialCurl to or from non-fullscreen view controller <UIViewController: 0x100b06900>.

I read that this is due to the fact that iOS 13 uses a different view/fulls screen presentation style. Is there a fix for this?

**Comment by jdnichollsc** [comment]
Are you using the last version v3.3.3? Can you share your code please?

**Comment by invisiblemaker** [comment]
I was able to get it resolved by changing some of the config attributes. Working great on iOS now. Thank you!

**Comment by nihp** [comment]
I am getting the same error. Can you share what is the fix which you made

`Exception 'Application tried to present UIModalTransitionStylePartialCurl to or from non-fullscreen view controller <UIViewController: 0x7fb786d0da00>.' was thrown while invoking open on target RNInAppBrowser with params (`

**Comment by AramArakelyan22** [comment]
@invisiblemaker What kind of changes did you do?
Could you share the changes Please?

**Comment by jdnichollsc** [comment]
Guys, what `modalPresentationStyle` are you using with `UIModalTransitionStylePartialCurl`?

**Comment by nihp** [comment]
@jdnichollsc In which file I need to check and change this. Can you give any example

**Comment by jdnichollsc** [comment]
Oh yes, check the README and the demo project of this repository 🙂

**Comment by nihp** [comment]
Thanks worked for me. But I am getting warning **Another InAppBrowser is already being presented**

**Comment by nihp** [comment]
If I not click on the done and then if I navigate to my app and again i click the url to open the browser it shows the warning and not opens the url again.

Another InAppBrowser is already being presented


How can I handle this if the user not click the done here?

Kindly clarify

**Comment by jdnichollsc** [comment]
To understand, how are you navigating to the app again?

**Comment by nihp** [comment]
If I scroll left to right it get navigate back in my iOS

**Comment by jdnichollsc** [comment]
mmm that behavior is disabled when you enable modal instead

**Comment by nihp** [comment]
Any solution for this?

**Comment by jdnichollsc** [comment]
Please create another issue with the details of the error. Also, put the iOS version you are using 👍

**Comment by Thram** [comment]
Same issue here. I followed the Readme and the Example to implement it on my project and I'm getting  **Another InAppBrowser is already being presented**. I'm using RN 0.61.5 and I tested it on an iPhone 11 with iOS 13.3
