### ISSUE TITLE
How to detect page load event ? 

### ISSUE THREAD

**Issue by meghna1711** [proyecto26/react-native-inappbrowser#132]
I have a use case where I have to clear previous session cookies from the browser, for this, I have to open a URL and close it as soon as the page is loaded completely.
Is there a way we can detect when the URL is loaded completely in the browser? 
If not, can we add this functionality just like what react-native Webview has?

```
<WebView
   ref={MY_REF}
   source={source}
   onLoadEnd={handler}
   startInLoadingState={true}
   renderLoading={() => <Loading />}
/>
```

**Comment by jdnichollsc** [comment]
We can't as I know, but check the official docs of Android/iOS and let me know 👍
