### ISSUE TITLE
How to prevent to show white modal / blank screen when choosing browser?

### ISSUE THREAD

**Issue by Jalson1982** [proyecto26/react-native-inappbrowser#133]
Hello. I have a question regarding the opening URL. When I use just Linking to open URL before I choose the browser it does not show me the white modal background. Is it possible to avoid this behaviour with react-native-inappbrowser? Here is a gif: https://media.giphy.com/media/hQzZtz5JkZmRS6pbTx/giphy.gif
Here is expected behaviour: https://media.giphy.com/media/S45iQXrVcJVF9COjC5/giphy.gif

**Comment by jdnichollsc** [comment]
Hello! I'm not sure if we can handle that, because the Android activity of React Native lost the context of the app when the browser of the device is launched, also you can avoid that white screen if you only have 1 browser installed in the device
