### ISSUE TITLE
Unable to close Browser after timeout (Android)

### ISSUE THREAD

**Issue by meghna1711** [proyecto26/react-native-inappbrowser#135]
I have a use case wherein I have to close the in-app browser after a timeout, however, this is not working in android. This works fine in iOS though. Find below the code snippet used.

### Versions used:
react-native: 0.58.6
react-native-inappbrowser: 1.3.13
node: 10.15.1

```
export const onLogout = async (_url: string) => {
  const deepLink = getDeepLink('identity');
  try {
      await InAppBrowser.isAvailable();
      const authPromise = InAppBrowser.openAuth(_url, deepLink, {
        // iOS Properties
        dismissButtonStyle: 'cancel',
        animated: false,
        modalPresentationStyle: 'overFullScreen',
        modalTransitionStyle: 'partialCurl',
        modalEnabled: true,
        enableBarCollapsing: false,
        // Android Properties
        showTitle: false,
        enableUrlBarHiding: true,
        enableDefaultShare: true,
      });
      
      setTimeout(() => {
        InAppBrowser.closeAuth();
      }, 4500);

      return authPromise.then((response) => {
        console.info('Link closed', response);
        return {};
      });

  } catch (e) {
    return Promise.reject(new Error('Unable to open link'));
  }
};
```

**Comment by jdnichollsc** [comment]
Try using the last version `v3.3.4` and let me know 👍

**Comment by elan** [comment]
This still seems to be broken, but the reason seems to be because JS code stops running when a custom chrome tab is open (e.g. `setTimeout` never completes), which is sort of confusing.

**Comment by sergiulucaci** [comment]
agree @elan. @jdnichollsc are you aware of this?

**Comment by jdnichollsc** [comment]
Do you have this configuration? https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/android/app/src/main/AndroidManifest.xml#L13

**Comment by elan** [comment]
My app has:

```xml
android:launchMode="singleTask"
```

**Comment by jdnichollsc** [comment]
Any pull request is welcome! 🙂

**Comment by elan** [comment]
Sadly I'm an Android n00b.

**Comment by jdnichollsc** [comment]
It looks like we fixed this issue from the last release, but let me know https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.4.0

**Comment by elan** [comment]
Hmm, I just tried it and it doesn't seem to behave any differently. I didn't see any obvious commit/change for the new version, is there something I'm missing?

**Comment by jdnichollsc** [comment]
I added some validations for `closeAuth` here https://github.com/proyecto26/react-native-inappbrowser/compare/v3.3.4...v3.4.0#diff-168726dbe96b3ce427e7fedce31bb0bcR129

**Comment by elan** [comment]
Ah, I'm not sure how that would help as the problem seems to be that the JS stops running once the browser is displayed, so that side never even gets to call `closeAuth`.

**Comment by jdnichollsc** [comment]
Please debug the last changes from `develop` branch, there's a pending PR of the new version 3.5.0 https://github.com/proyecto26/react-native-inappbrowser/pull/195

**Comment by marcelodesouza** [comment]
I had this problem on Android, but it was not related to timers.
Encoding the `redirect_uri` in the url did the trick for me.

```JS
${url}?&redirect_uri=${encodeURIComponent(redirect_uri)}
```

Hope it helps.
