### ISSUE TITLE
Release build fails while proguard is enabled.

### ISSUE THREAD

**Issue by imkrunal** [proyecto26/react-native-inappbrowser#136]
# Which platform(s) does your issue occur on?
- Android 
- Q
- What type of device?: emulator and device. 

Bug Snag Error Report: Subscriber class com.proyecto26.inappbrowser.c and its superclasses have no public methods with the @Subscribe annotation

### Please, tell us how to recreate the issue in as much detail as possible. 
- Enable hermes and pro guard and create release build using ./gradle assembleRelease

### Solutions
The solution to this issue was to add proguard rules in `android/app/proguard-rules.pro`
```
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
 }
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
```

**Comment by jdnichollsc** [comment]
yes, this is the last step of the configuration for Android 👍 https://github.com/proyecto26/react-native-inappbrowser#android

**Comment by wilau2** [comment]
I think the doc can be confusing, 
Is auto-linking managing the proguard configuration or is it part of the manual installation only?

**Comment by jdnichollsc** [comment]
Do you know if Autolinking configure that automatically? 🙂

**Comment by wilau2** [comment]
I'm still trying to figure it out but I experienced some crashes on libs that were auto-link for missing proguard rules. 🤷‍♂

**Comment by jdnichollsc** [comment]
so any pull request to improve our docs is welcome! 👍
