### ISSUE TITLE
After opened the url in real device screen gets stuck after click on the DONE button 

### ISSUE THREAD

**Issue by nihp** [proyecto26/react-native-inappbrowser#139]
I tried to open the inapp browser in my real device. After click on the url it get opens the url inside my app. But after click on the DONE button. It goes back and then stuck and still in that same screen. Kindly refer the attached screenshot

How can I resolve this
![IMG_2E5D401FCA3B-1](https://user-images.githubusercontent.com/36992338/72249671-d560d300-361f-11ea-978d-0589b5724f57.png)

**Comment by jdnichollsc** [comment]
Partial curl animation is not working as expected since iOS 13, check more details here: https://forums.developer.apple.com/thread/124765

**Comment by Benzer1406** [comment]
Still the same issue. Any solution?

**Comment by jdnichollsc** [comment]
This is a native issue, if you figure out any workaround, any pull request is always welcome! 🙂

**Comment by Benzer1406** [comment]
I just realized that changing the prop `modalTransitionStyle` from `partialCurl` to any of the three other animation types (`coverVertical`/`flipHorizontal`/`crossDissolve`) solves the issue.
