### ISSUE TITLE
Cannot run on Andorid

### ISSUE THREAD

**Issue by rborn** [proyecto26/react-native-inappbrowser#14]
Hi,

I don't manage to make it work on android.
It seems that it cannot find the NativeModule 

The error is `TypeError: Cannot read property 'open' of undefined` and it goes down to https://github.com/proyecto26/react-native-inappbrowser/blob/master/index.js#L41

Any idea? (I installed it correctly)

Thank you.

**Comment by jdnichollsc** [comment]
@rborn it looks an issue with the installation if `RNInAppBrowser` is **undefined** :)

**Comment by rborn** [comment]
@jdnichollsc I can confirm that is not in the `NativeModule` - it seems it's not registering itself for somehow

**Comment by jdnichollsc** [comment]
@rborn I don't know if I can remove the build configuration https://github.com/proyecto26/react-native-inappbrowser/blob/master/android/build.gradle#L15
Let me try

**Comment by rborn** [comment]
Not sure this is the problem? I force customtabs to 28.0.0 and it compiles

**Comment by jdnichollsc** [comment]
@rborn can you try the last version of this repository? https://github.com/proyecto26/react-native-inappbrowser/blob/master/android/build.gradle
Please let me know to publish from npm

**Comment by rborn** [comment]
the same :(

**Comment by rborn** [comment]
@jdnichollsc let me gradlew clean..

**Comment by jdnichollsc** [comment]
I don't understand, are you pointing to this github repo from the package.json?

**Comment by rborn** [comment]
OMG 🙀, `gradlew clean` aaaaand it runs with the  ` "react-native-inappbrowser-reborn": "https://github.com/proyecto26/react-native-inappbrowser.git",`🎉
Thanks a lot ❤️

**Comment by jdnichollsc** [comment]
Ok, let me publish a new version

**Comment by jdnichollsc** [comment]
Done, check the last version from npm!
