### ISSUE TITLE
Calling open doesn't do anything

### ISSUE THREAD

**Issue by Dellybro** [proyecto26/react-native-inappbrowser#140]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

-Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `react-native --version` to fetch it)
react-native-cli: 2.0.1

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
v0.61.4

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

```
async function handleOpenInAppBrowser(url, text) {
    console.log(url, text)
    if(await InAppBrowser.isAvailable()) {
      let result = await InAppBrowser.open(url, {
        dismissButtonStyle: 'cancel',
          preferredBarTintColor: '#453AA4',
          preferredControlTintColor: 'white',
          readerMode: false,
          animated,
          modalPresentationStyle: 'fullScreen',
          modalTransitionStyle: 'partialCurl',
          modalEnabled: true,
          enableBarCollapsing: false,
          // Android Properties
          showTitle: true,
          toolbarColor: '#6200EE',
          secondaryToolbarColor: 'black',
          enableUrlBarHiding: true,
          enableDefaultShare: true,
          forceCloseOnRedirection: false,
          // Specify full animation resource identifier(package:anim/name)
          // or only resource name(in case of animation bundled with app).
          animations: {
            startEnter: 'slide_in_right',
            startExit: 'slide_out_left',
            endEnter: 'slide_in_left',
            endExit: 'slide_out_right'
          },
      })
      console.log(result);
    }
    else {
      props.screenProps.showToast({
        text: "We were unable to open your in app browser. To view our policies please visit our website at https://www.iskua.com.",
        type: 'warning'
      })
    }
  }
```

I'm using React navigation, and i'm doing exactly what the example does. But for some reason when i try to open the browser is just doesn't open. I'm not exactly sure what to do. I'm also passing a url which will send them to a 401 page but it still is technically sending a response, so that shouldn't be a problem i imagine.

**Comment by drewhamlett** [comment]
Were you able to solve this?
