### ISSUE TITLE
Nothing happens when inAppBrowser is on the Deep link Url.

### ISSUE THREAD

**Issue by Ne0xygene** [proyecto26/react-native-inappbrowser#142]
Hello everyone !

I have some trouble using the library on my application.

I'm trying to do a google oauth2 login that redirects to a callback url (which set my deep link).
However my application doesn't seem to detect that i'm on the callback url.

Using the native Linking library (using Linking.OpenUrl() and Linking.addEventListen), it works perfectly but for some reasons, i need to perform this action under an in-app browser.

Here is my code :

Intent Filter :

    <intent-filter>
              <action android:name="android.intent.action.VIEW"/>
              <category android:name="android.intent.category.DEFAULT"/>
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="https"
                    android:host="app.getpostman.com"
                    android:pathPrefix="oauth2/callback"/>
     </intent-filter>

InAppBrowser Code: 

    // url correspond to my google oauh2 url
    const DeepLink = encodeURIComponent('https://app.getpostman.com/oauth2/callback');
    try {
            if (await InAppBrowser.isAvailable()) {
                var result = InAppBrowser.openAuth(url, DeepLink, {
                    showTitle: false,
                    enableUrlBarHiding: true,
                    enableDefaultShare: true,
                    forceCloseOnRedirection: true
                }).then((response) => { // Do nothing until the user close the browser
                    console.log("response URL: ", response.url);
                    if (response.type === 'success' && response.url)
                        console.log("response URL: ", response.url);
                })
                console.log("Result: ", result);
            }
        } catch(error) {
            Linking.openURL(url);
        }

So I wanted to know if it was possible to detect when the In-App Browser browse through my Deep Link Url the same way as using the native Linking library, so that i can redirect to my application.

Thanks in advance !

**Comment by sebastiancichos** [comment]
@Ne0xygene Did you resolve that problem? Can you share some advice?

**Comment by Ajmal0197** [comment]
https://dev.to/ajmal0197/react-native-twitch-auth-using-deeplinking-and-react-native-inappbrowser-reborn-1hff
