### ISSUE TITLE
Question: Does SFSafariViewController passes SSL

### ISSUE THREAD

**Issue by firdaussoberi** [proyecto26/react-native-inappbrowser#143]
Hi this is a question, 
Thanks for this awesome looking library.

I came here considering this package after my app got rejected from App Store saying

```
Guideline 4.0 - Design


We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.

Next Steps

To resolve this issue, please revise your app to enable users to sign in or register for an account in the app.

We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.
```
I got this sign in screen where it also has a sign up button when clicked brings user to Safari (Linking.openURL) to a website with sign up form.
I saw the standard ReactNative's WebView is being moved to https://github.com/react-native-community/react-native-webview. Since I'm not familiar with iOS implementation of webview, 

My questions:
1. For react-native-community/react-native-webview, do you know what kind of implementation they currently uses (is it UIWebView or is it already changed to WKWebView since i heard webview is being phased out soon)
2. I'm keen to use this library since it uses SFSafariViewController but what is its difference than UIWebView or  WKWebView? And its modal Safari will not share cookies with the system Safari, so does the modal Safari passes SSL (like how UIWebView passes unverified SSL)?

Sorry for the trivial questions, but I appreciate if anyone could enlighten me.
Thanks!

**Comment by firdaussoberi** [comment]
Nvm, I got the answer I was looking for. Am using the library now. Thanks.

**Comment by olegdev** [comment]
Can you share that answer here? Tnhks

**Comment by firdaussoberi** [comment]
> Can you share that answer here? Tnhks

I am not so sure but I think WKWebView might be better, based on this:
https://www.hackingwithswift.com/example-code/wkwebview/whats-the-difference-between-uiwebview-and-wkwebview
https://medium.com/@kevin.baldha/difference-between-uiwebview-and-wkwebviewapple-6f8b75819a18
