### ISSUE TITLE
Cookie Clear 

### ISSUE THREAD

**Issue by amon-shadow** [proyecto26/react-native-inappbrowser#145]
How can  clear cookie using logout URL in Android for the Auth0 login?

**Comment by jdnichollsc** [comment]
Let me know if you find any official documentation to support this 👍https://developer.chrome.com/multidevice/android/customtabs

**Comment by IkeyBenz** [comment]
Some clarity on this would be much appreciated. Currently the .openAuth method seems to be storing the cookies received from authentication. This causes subsequent logins to occur automatically, a feature that is undesired in the case where a user has multiple accounts to log in to.

**Comment by jdnichollsc** [comment]
That's the default behavior of Android Chrome CustomTabs, let me know if you find any native option to be able to disable that, also any pull request is always appreciated!

**Comment by FrancisLeigh** [comment]
I'm also in a similiar boat with this issue. 

At the moment I am trying to open a custom-tab and make a POST to our `/logout` endpoint which should invalidate our session cookies on the custom-tab itself however I can't get this library to make a `POST` to my URL.

see #230

**Comment by Ros-ty** [comment]
Any progress?

**Comment by jdnichollsc** [comment]
The best way to solve this CustomTabs limitation is to create a webpage or an endpoint to clear the cookies and then redirect your users to the auth flow using deep linking 🤠

**Comment by therealtgd** [comment]
Any solution now?

**Comment by dieptx** [comment]
Any update?

**Comment by mrazekrad** [comment]
> The best way to solve this CustomTabs limitation is to create a webpage or an endpoint to clear the cookies and then redirect your users to the auth flow using deep linking 🤠

Hi, which cookies do you clear? I don't want to delete all cookies. Thx
