### ISSUE TITLE
InAppBrowser.open triggering a open with dialog

### ISSUE THREAD

**Issue by crushy26** [proyecto26/react-native-inappbrowser#149]
### Which platform(s) does your issue occur on?
- Android
- Android 9, Oneplus 3
- Device

### Please, provide the following version numbers that your issue occurs with:

- CLI: react-native-cli: 2.0.1 |  react-native: 0.59.10
- Plugin(s): ^2.0.4

### Please, tell us how to recreate the issue in as much detail as possible. 

Configured this package normally with my existing react-native app.

The InAppBrowser.open for any url shows two an open with a dialog with google chrome and NewsPoint app. By default, it should directly open in an in-app chrome browser.  Please check attachment.

Checked other apps like LinkedIn, they are able to directly open it in their in-app browser, without these open with dialog. 

![photo_2020-03-31_22-52-59](https://user-images.githubusercontent.com/37217713/78056404-b4985600-73a2-11ea-9719-b5335c85a6b1.jpg)

**Comment by jdnichollsc** [comment]
Let me know if you find something to handle that from oficial docs (Android Custom Tabs)

**Comment by crushy26** [comment]
@jdnichollsc  unfortunately, I am unable to figure out the solution. I checked with other apps who use custom tabs, they seem to be working fine. Please check Linkedin once.

**Comment by jdnichollsc** [comment]
It looks like we need to add an Android option to indicate the package here https://stackoverflow.com/a/42318742/1532821

**Comment by crushy26** [comment]
Yes, it works by setting default package:  intentCustomTabs.intent.setPackage("com.android.chrome");

Can you please do this bydefault, I will anyway handle for now.

**Comment by williamtran1988** [comment]
intentCustomTabs.intent.setPackage("com.android.chrome");

IT IS NOT A GOOD SOLUTION. Because the app will crash if your device has not "Chrome" enabled.

**Comment by jdnichollsc** [comment]
@williamtran1988 what do you think having this as optional? Let me check more about this :)

**Comment by williamtran1988** [comment]
@jdnichollsc 

There is a pull request from  #177 which support chosen a browser default. It works well. Please take a have look
