### ISSUE TITLE
Hiding views from UXCam

### ISSUE THREAD

**Issue by jamestri-nandos** [proyecto26/react-native-inappbrowser#151]
Hello

First off, this lib is great thanks so much!

We use UXCam to record what the user is getting up to but i need to be able to hide disable this on sensitive web views.

According to UXCam docs you do this buy grabbing the ref of a component and passing it to the lib.
[UXCam docs](https://help.uxcam.com/hc/en-us/articles/115000967031-Hide-Sensitive-Views) 
Is there a way to get hold of inAppBrowser modal ref so I can add it? Or is there another way to ensure it is hidden?

iOS secure web views should be fine - do you use these? - but Android will not hide anything automatically i don't think.

Is there a way to grab the reference?

Many thanks!

**Comment by jdnichollsc** [comment]
We don't use Webviews

**Comment by jamestri-nandos** [comment]
Apologies, I did not mean web view other than to mean a view of the web. Sorry very confusing terminology on my part.

You do use a modal though. Is it a react native modal or purely native? If react, can I get my hands on the ref?

Thanks

**Comment by jdnichollsc** [comment]
This plugin don't have React components, it's just a wrapper for Native components, Chrome Custom Tabs and SafariServices 🙂
