### ISSUE TITLE
Loads the same screen, for one url with different routes

### ISSUE THREAD

**Issue by venkat77777** [proyecto26/react-native-inappbrowser#152]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
Android version 10
OnePlus 6

### Please, provide the following version numbers that your issue occurs with:
"react-native-inappbrowser-reborn": "^3.4.0"
"react": "16.12.0",
"react-native": "0.61.5",

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
I have 2 urls whose base url is same but has different end points
 https://example.com/routes/loadData
and 
https://example.com/routes/displayData

when I load the first url by calling InAppBrowser.open(url), it loads fine,
in the first Url I have a button which loads different url (https://test.com/list),
and it's loading that url, and from that url, there's a function to load second url.

Second url is not loading and instead of it's loading the first url.

I think it's considering only base url but not the complete url, how to fix this issue?

**Comment by jdnichollsc** [comment]
I can't help without code to be able to reproduce this issue

**Comment by venkat77777** [comment]
`if (await InAppBrowser.isAvailable()) {
        const result = await InAppBrowser.open(url, {
          // iOS Properties
          dismissButtonStyle: 'cancel',
          preferredBarTintColor: colors.darkNavyBlue,
          preferredControlTintColor: 'white',
          readerMode: false,
          animated: true,
          modalPresentationStyle: 'overFullScreen',
          modalTransitionStyle: 'partialCurl',
          modalEnabled: true,
          enableBarCollapsing: false,
          // Android Properties
          showTitle: true,
          toolbarColor: colors.black,
          secondaryToolbarColor: 'black',
          enableUrlBarHiding: true,
          enableDefaultShare: true,
          forceCloseOnRedirection: false,
          // Specify full animation resource identifier(package:anim/name)
          // or only resource name(in case of animation bundled with app).
          animations: {
            startEnter: 'slide_in_right',
            startExit: 'slide_out_left',
            endEnter: 'slide_in_left',
            endExit: 'slide_out_right'
          },
        })
        Alert.alert(JSON.stringify(result))
      }`

above is the code i'm using, Try to load different urls with same base like mentioned in the issue.

**Comment by jdnichollsc** [comment]
I need to see the redirection you have in your external domain, otherwise I can't reproduce this issue, share that to reopen this issue
