### ISSUE TITLE
[XSLT] Load local XML string with stylesheet

### ISSUE THREAD

**Issue by bobojager** [proyecto26/react-native-inappbrowser#154]
Hello,
I have two questions about the component usage.
1. Can I load a local file/string (I don't have a remote URL to load)?
2. Is the component able to render an XML with a stylesheet (XSLT) properly?

Thanks in advance

**Comment by jdnichollsc** [comment]
As far as I know, Chrome Custom Tabs and SafariViewController only works for http/https
