### ISSUE TITLE
android: open .pdf link in browser not os pdf viwer!

### ISSUE THREAD

**Issue by ramyareye** [proyecto26/react-native-inappbrowser#159]
### Which platform(s) does your issue occur on?
- Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: latest
- Plugin(s): latest

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
I try to open a .pdf link from dropbox in browser but it opens os native pdf viwer!
As my file is not really a pdf but a link to the file I need to open it in browser.
How can I force my app to open this .pdf link like a normal link?

**Comment by jdnichollsc** [comment]
I don't understand, what kind of link? please attach an example to be able to reproduce this issue
Can you try using Google Viewer?
```js
const encodedUrl = encodeURIComponent(fileUrl)
const url = `https://docs.google.com/viewer?url=${encodedUrl}&embedded=true`
```
Regards

**Comment by ramyareye** [comment]
> I don't understand, what kind of link? please attach an example to be able to reproduce this issue
> Can you try using Google Viewer?
> 
> ```js
> const encodedUrl = encodeURIComponent(fileUrl)
> const url = `https://docs.google.com/viewer?url=${encodedUrl}&embedded=true`
> ```
> 
> Regards

I ended up with same solution. The problem is I couldn't open a pdf in dropbox file viewer. As I searched it's related to Android. [Here](https://stackoverflow.com/questions/7437602/how-to-display-a-pdf-via-android-web-browser-without-downloading-first) is a same issue

**Comment by KingAmo** [comment]
while I am in China, i could not reach any `google services`, is there a alternative way

**Comment by jdnichollsc** [comment]
@KingAmo honestly I've no idea

**Comment by gajjartejas** [comment]
Why does not it is working in China?
