### ISSUE TITLE
How to hide URL during loading process

### ISSUE THREAD

**Issue by JRamonMC** [proyecto26/react-native-inappbrowser#162]
# Which platform(s) does your issue occur on?
This happens on emulator and real devices on iOS/Android. 

### Please, provide the following version numbers that your issue occurs with:

- CLI: react-native-cli: 2.0.1
          react-native: 0.61.5
- Plugin(s): ^3.4.0

### Please, tell us how to recreate the issue in as much detail as possible. 

Firstly, it's not an error. I would like to hide the url at the top of browser during social login.  Main reason is that it shows my server url and this could be a little bit strange for users. I've been searching info on the web but I didn't found anything. Also, I would like to know if we can edit the message of **InAppBrowser.closeAuth**, due to it shows "Sign In" during logout process.

### Is there any code involved? 

Login

```
const response = await InAppBrowser.openAuth(url, deepLink, {
      modalPresentationStyle: "overFullScreen",
      animated: true,
      showTitle: false,
      readerMode: false,
      modalEnabled: true,
      ephemeralWebSession: false,
    });

```

Logout 

```
    await Auth.signOut()
      .then(async () => {
        InAppBrowser.closeAuth();

        await AsyncStorage.clear();
      })
```

**Comment by jdnichollsc** [comment]
Chrome CustomTabs/SafariViewController don't support hiding the url
