### ISSUE TITLE
Navigation listener and custom actions

### ISSUE THREAD

**Issue by zatsepinvl** [proyecto26/react-native-inappbrowser#163]
Hi All!

What about the following features (for both iOS and Android):

1. Listen for navigation events in Custom tabs
2. Add custom items into the action bar

```javascript
InAppBrowser.open(url, options: {
    //...existing options,
    onNavStateChanged: (event) => {  },
    menuItems: [
          {
              title: "My custom action",
              onItemClicked: (event) => {  }
          }
    ]
})
```

Is it something that planned to be added in the future?

**Comment by jdnichollsc** [comment]
Chrome CustomTabs/SafariViewController don't support navigation events

**Comment by jdnichollsc** [comment]
Any pull request to add custom items is really appreciated!

**Comment by CodeByAlvin** [comment]
> Hi All!
> 
> What about the following features (for both iOS and Android):
> 
> 1. Listen for navigation events in Custom tabs
> 2. Add custom items into the action bar
> 
> ```js
> InAppBrowser.open(url, options: {
>     //...existing options,
>     onNavStateChanged: (event) => {  },
>     menuItems: [
>           {
>               title: "My custom action",
>               onItemClicked: (event) => {  }
>           }
>     ]
> })
> ```
> 
> Is it something that planned to be added in the future?

I really wish there was this feature
