### ISSUE TITLE
Header not working as expected in iOS

### ISSUE THREAD

**Issue by joaonew** [proyecto26/react-native-inappbrowser#165]
On iOS, when scrolling down in the webview, the header is hiding in a weird way, photo attached.

![IMG_AA92B87D4E1C-1](https://user-images.githubusercontent.com/43939710/86181582-4e83b200-bafc-11ea-9568-bbbcca8b24d1.jpeg)

Any easy fix on this?

**Comment by jdnichollsc** [comment]
Please include your code and more details (platform, RN and plugin versions, etc)

**Comment by joaonew** [comment]
IOS problem
"react-native": "0.59.9"
"react-native-inappbrowser-reborn": "2.0.4",

`  openLink = async (url) => {
    try {
      if (await InAppBrowser.isAvailable()) {
        const result = await InAppBrowser.open(url, {
          // iOS Properties
          dismissButtonStyle: "cancel",
          preferredBarTintColor: "gray",
          preferredControlTintColor: "white",
          readerMode: false,
          // Android Properties
          showTitle: true,
          toolbarColor: "#6200EE",
          secondaryToolbarColor: "black",
          enableUrlBarHiding: true,
          enableDefaultShare: true,
          forceCloseOnRedirection: false,
          // Specify full animation resource identifier(package:anim/name)
          // or only resource name(in case of animation bundled with app).
          animations: {
            startEnter: "slide_in_right",
            startExit: "slide_out_left",
            endEnter: "slide_in_left",
            endExit: "slide_out_right",
          },
          headers: {
            "my-custom-header": "my custom header value",
          },
        });
        // Alert.alert(JSON.stringify(result));
      } else Linking.openURL(url);
    } catch (error) {
      // Alert.alert(error.message);
    }
  };`

**Comment by jdnichollsc** [comment]
Can you try disabling modal using `modalEnabled: false`?

**Comment by joaonew** [comment]
Like this?

I tried both false and true and still got the same response.

Any other ideas?

![image](https://user-images.githubusercontent.com/43939710/87180337-6272a500-c2ae-11ea-9a4f-caa2b0b79461.png)

**Comment by jdnichollsc** [comment]
What version of iOS are you using? What devices? Please share a repo to reproduce this issue
