### ISSUE TITLE
Avoid confirmation dialog to login

### ISSUE THREAD

**Issue by bsjaffer** [proyecto26/react-native-inappbrowser#167]
When we use openAuth is there any way to avoid that confimation dialog and still persist cookies in ios ? 

Currently its showing "AppName" wants to sign in with "siteurl". Which I want to avoid and still persist cookies across sessions.

**Comment by jdnichollsc** [comment]
iOS don't allow that, the only option to avoid that dialog is using the **ephemeralWebSession** option
