### ISSUE TITLE
library currently using deprecated SFAuthenticationSession

### ISSUE THREAD

**Issue by nairmanu** [proyecto26/react-native-inappbrowser#168]
### Which platform(s) does your issue occur on?
- iOS

### Please, provide the following version numbers that your issue occurs with:
3.4.0

### Please, tell us how to recreate the issue in as much detail as possible. 
Currently the library is using SFAuthenticationSession class which is deprecated and Apple recommends to use SFAuthenticationSession instead. Is there a plan to migrate to use this new class?

**Comment by jdnichollsc** [comment]
We already have that validation here https://github.com/proyecto26/react-native-inappbrowser/blob/974a966cdf2a1ed7d9cd071c535d15f7d594cb07/ios/RNInAppBrowser.m#L93
