### ISSUE TITLE
How to close with deeplink

### ISSUE THREAD

**Issue by skiddolo** [proyecto26/react-native-inappbrowser#169]
Hi everyone, i need help for interacting with a custom page.
Manual deeplink works ( if i call myapp:// from safari, the app correctly open ), but i can't close the inAppBrowser page to send data to RN.
i'd try window.location to redirection_url and also a php header("Location:". $redirection_url) but both seems not work.

I've this page with a form, and after the submit there's a courtesy page for submit confirm and here i want to comeback to app with the response.

**Comment by jdnichollsc** [comment]
the only way to send data to the app is using query string params in that redirection :)

**Comment by skiddolo** [comment]
i'm sorry, maybe i wasn't clear..both type of redirection doesn't close the inAppBrowser page and no callback i receive

**Comment by jdnichollsc** [comment]
did you configured deep linking in your app? please share a repository of the project to be able to reproduce this issue :)

**Comment by skiddolo** [comment]
yep, deep link correctly work, if  if i call myapp:// from safari, the app correctly open on IOS.

i've to do some other stuff for doing that with inAppBrowser?

**Comment by jdnichollsc** [comment]
As far as I know, for security concerns, `window.location` doesn't work, you need to redirect to the app with a backend redirection (HTTP 302)

**Comment by skiddolo** [comment]
yep i'd try also the php redirection 302, but nothing append :( how can i debug it?

**Comment by jdnichollsc** [comment]
Can you share the url of that backend redirection? :)

**Comment by skiddolo** [comment]
http://manager.hellobeach.it/server/gestpayTest/response.php?redirect_url=hellobeach%3A%2F%2F

Here :) 

with this instruction

**Comment by skiddolo** [comment]
ok i noted a thing. The OPEN method, doesn't do nothing with 302 redirect. Instead the OPENAUTH did and works correctly.

it's possibile to trigger OPEN method with 302 redirection? or to avoid the alert using OPENAUTH? or to customize the alert!

We need to make external payment or other form and not to signin and that alert is not correct for us

Thx :)

**Comment by jdnichollsc** [comment]
sorry, what alert? Did you try **ephemeralWebSession** option for iOS? openAuth is the correct way to do that :) Other option is using [React Native Linking](https://reactnative.dev/docs/linking) directly, with the **getInitialURL** method: https://reactnative.dev/docs/linking#getinitialurl
Regards
