### ISSUE TITLE
Throwing an invalid link error when url includes a | character

### ISSUE THREAD

**Issue by jacquesdev** [proyecto26/react-native-inappbrowser#175]
### Which platform(s) does your issue occur on?
Happens everywhere

### Please, provide the following version numbers that your issue occurs with:

Using current master commit ff641257819b18de0ec854d0276cf29189c3de66

### Please, tell us how to recreate the issue in as much detail as possible. 
Some of my links reference google docs links, and in my case, it included something like url?207|631. I realised that for whatever reason, including a pipe character (even after ? for extra params), throws an unsupported scheme error (which doesn't seem correct)

<img width="302" alt="Screenshot 2020-07-24 at 12 44 40" src="https://user-images.githubusercontent.com/7842197/88387957-7b4d8100-cdab-11ea-96f6-8d53481b2f26.png">

### Is there any code involved? 
Open a link with a pipe character for example, https://github.com/proyecto26/react-native-inappbrowser?letsaddapipe|

**Comment by jdnichollsc** [comment]
Try this 
```
const param = encodeURIComponent('letsaddapipe|')
const url = `https://github.com/proyecto26/react-native-inappbrowser?${param}`
```
Regards

**Comment by jacquesdev** [comment]
Thanks for that workaround, but it would be nice if this functionality was built-in. Will look at adding a PR for this

**Comment by jacquesdev** [comment]
Specifically because it's throwing the wrong error

**Comment by jdnichollsc** [comment]
that's not a valid character for urls, so that's not a workaround at this point :)

**Comment by jacquesdev** [comment]
I agree it's not a valid character, but that is specifically what the error should be (ie illegal character used), and not that it's not a http or https error?
