### ISSUE TITLE
Redirect only work correct on Chrome browser

### ISSUE THREAD

**Issue by thuongtv-vn** [proyecto26/react-native-inappbrowser#176]
I have tested on some browsers:

Chrome : OK
Firefox: Start app again, callback not called
Opera: Start app again, callback not called.

After authenticated successfully, the CustomTabsIntent closed and start the main application again, the callback when openAuth not called.

**Comment by jdnichollsc** [comment]
It requires Chrome CustomTabs for Android => https://developers.google.com/web/android/custom-tabs
