### ISSUE TITLE
Listener for changes in URL

### ISSUE THREAD

**Issue by HumayounBaig** [proyecto26/react-native-inappbrowser#180]
Need event for listening to changes when a change in url appears.

something like       Linking.addEventListener('url', handleOpenedUrl)

as some api's return auth token in URL i am unable to find an event

**Comment by jdnichollsc** [comment]
That's only supported by WebView, ChromeTabs and SafariViewController don't support that

**Comment by HumayounBaig** [comment]
The Apollo Reddit app uses it so i guess it must be supported. 
Is there any chance this module would get it anytime soon?

**Comment by jdnichollsc** [comment]
Any pull request is welcome! :)
