### ISSUE TITLE
InAppBrowser.open open dialog

### ISSUE THREAD

**Issue by BhagirathGadhesariya** [proyecto26/react-native-inappbrowser#182]
i am use inappbrowser for open my web in react-native app but when i am click on button open dialog for display external browser application for open my web 
but i need to open my web in react-native app not in any external browser
![Screenshot_20200901-145238](https://user-images.githubusercontent.com/69451838/91832590-3bf43900-ec63-11ea-9ec0-c942d8a1010e.png)

check this image i not need to display this dialog
need to open web in my app like webview

**Comment by jdnichollsc** [comment]
This is not a WebView, can you debug the last changes from develop branch? There's a pending PR for the new version 3.5.0 https://github.com/proyecto26/react-native-inappbrowser/pull/195
