### ISSUE TITLE
Unable to access camera ( .getUserMedia for Webrtc ) 

### ISSUE THREAD

**Issue by praveen3edge** [proyecto26/react-native-inappbrowser#185]
The inappbrowser unable to get the camera feed from getUserMedia function shows undefined .

**Comment by damieng57** [comment]
Hi,

I think your problem appears if you are trying to connect a on non secure website. You cannot use getuserMedia on HTTP website. 
I'm stucked on this problem too. I'm running my HTTP server inside my react-native app. It works on localhost but when I switch on local network with an address 192.168.XX.XX, getUsermedia shows undefined too.

With Chrome(mobile or desktop), you can set a flag chrome://flags/#unsafely-treat-insecure-origin-as-secure, it will be great to have a similar option for inappbrowser

**Comment by praveen3edge** [comment]
Hi  damieng57 ,

I used https://meet.jit.si , for Audio video conference . 
I read an article on accessing camera from Ios web view kit , It states that IOS doesn't allow camera access for webkit , Only safari supports it . 
So I tried this plugin , So that Jitsi can access the safari's webrtc functions . But it shows that getUserMedia is undefined , I have to research on this topic.

**Comment by jdnichollsc** [comment]
Please attach a repo to reproduce this issue :)

**Comment by Genesy91** [comment]
Same problem accessing camera and mic but if i refresh the page it works.

**Comment by jdnichollsc** [comment]
Can you check this WebComponent I did with WebRTC? https://proyecto26.com/record-audio-button-enterprise

Let me know if you're getting issues with InAppBrowser

**Comment by jdnichollsc** [comment]
Please share more details (Platform, OS version, RN version, etc) in order to reopen this issue 👍
