### ISSUE TITLE
openAuth crashed when going to be closed and then press the cancel button

### ISSUE THREAD

**Issue by lkspc** [proyecto26/react-native-inappbrowser#186]
Just the simple codes called `openAuth` cause  APP crashed. It was tested by our QC team.
```js
  const response = await InAppBrowser.openAuth(url, redirect, {
    // iOS Properties
    ephemeralWebSession: false,
    // Android Properties
    showTitle: false,
    enableUrlBarHiding: true,
    enableDefaultShare: false,
  });
```

Happened when the auth modal of InAppBrowser was finished and going to be closed then you pressed the cancel button at the same time.

Need help please.

**Comment by jdnichollsc** [comment]
Any pull request is welcome!

**Comment by jdnichollsc** [comment]
Please debug the last changes from `develop` branch, there's a pending PR of the new version 3.5.0 https://github.com/proyecto26/react-native-inappbrowser/pull/195

**Comment by lkspc** [comment]
We've ignored this bug for now, as it only produces in extreme environments. 

Our team may debug the fixes next time, thanks for your work.

**Comment by jdnichollsc** [comment]
Thanks for let me know!
