### ISSUE TITLE
RNInAppBrowser becomes 'undefined' after upgraded to Xcode 12

### ISSUE THREAD

**Issue by pxmage** [proyecto26/react-native-inappbrowser#187]
### Which platform(s) does your issue occur on?
iOS emulator 13.4

### Please, provide the following version numbers that your issue occurs with:

- CLI: 2.0.1
- Plugin(s): 3.4.0

### Please, tell us how to recreate the issue in as much detail as possible. 
- Upgrade Xcode to 12 (I didn't want to, but I was upgraded automatically)
- Use any method provided by this package like 'RNInAppBrowser.isAvailalbe()'
- You will see the error "Cannot read property 'isAvailable' of undefined"

### Is there any code involved? 
No, just upgrade your Xcode to 12, and then you cannot use this package.

I am pretty sure I imported this package, because I can see all methods when I
```javascript
import InAppBrowser from 'react-native-inappbrowser-reborn'
console.log(InAppBrowser)
```

I guess this bug may caused by this line of code in the source code
```javascript
const { RNInAppBrowser } = NativeModules;
```
Something must went wrong when using NativeModules with Xcode12

**Comment by asleepingpanda** [comment]
We've just recently started having issues with this, too, and I'm curious if it's the same problem.

When I run `InAppBrowser.open`, I get an `Unhandled Promise rejection` every time.

**Comment by pxmage** [comment]
> We've just recently started having issues with this, too, and I'm curious if it's the same problem.
> 
> When I run `InAppBrowser.open`, I get an `Unhandled Promise rejection` every time.

Yes, exactly.

Hope this will be fixed soon :(

**Comment by asleepingpanda** [comment]
Yeah I agree! It's currently affecting our production app.

**Comment by pxmage** [comment]
@asleepingpanda 
After upgraded to React Native 0.63.2, it works again in my project now.
