### ISSUE TITLE
Custom Headers on iOS

### ISSUE THREAD

**Issue by export-mike** [proyecto26/react-native-inappbrowser#188]
I'm sending custom headers with the api as documented:

``` headers: { 'x-my-header':'123'}``` I can see that these headers are not passed over

turns out this is caused by SFSafariViewController whereas. https://developer.apple.com/documentation/webkit/wkwebview supports this

Any way I can work around this?

**Comment by jdnichollsc** [comment]
`headers` param is only supported from Android platform, we're not using WebView in this lib
