### ISSUE TITLE
Pop Up Windows For cross communication Webview 

### ISSUE THREAD

**Issue by maschad** [proyecto26/react-native-inappbrowser#193]
### Feature Request
I would like to be able to utilize window.opener , window.open , window.postMessage from my Webview to communicate with an InAppBrowser, on Safari (iOS) the popUps are blocked but on Chrome (Android) it's unable to postMessage at all, for instance, given the target Origin provided doesn't match the recipient window's origin. If there are any existing solutions I am definitely open to exploring.

### Additional Context
I am using [react-native-webview](https://github.com/react-native-webview/react-native-webview) as well.

### Proposed Solution
Whenever the webivew sends a `postMessage` , then  using the `onMessage` [prop](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onmessage) that could be forwarded to inAppBrowser, and it could respond via it's own `onMessage` prop so that the two Web-views can communicate.

### Which platform(s) does your issue occur on?
- iOS/Android/Both

**Comment by jdnichollsc** [comment]
We're not using WebViews :)
