### ISSUE TITLE
Clarifying the purpose of redirectUrl

### ISSUE THREAD

**Issue by jacobparish** [proyecto26/react-native-inappbrowser#194]
I'm confused about the purpose of the `redirectUrl` param for `openAuth`, even after looking at #113. It seems as if I can pass any arbitrary string as the `redirectUrl`, and no matter what, it will always redirect back to my app when it gets redirected to a URL with the `my-app://` scheme. Is this the intended behavior? Also, what should I do if I want to handle 2 possible redirect urls?

**Comment by jdnichollsc** [comment]
2 possible redirect urls? can you please attach a repo to reproduce this issue?
If you want to understand how to use deep linking with the redirectUrl param, check this example: https://docs.expo.io/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl
