### ISSUE TITLE
openAuth not loading content on iOS

### ISSUE THREAD

**Issue by lukemorales** [proyecto26/react-native-inappbrowser#196]
I'm trying to implement this as Apple has denied my version with react native's Linking opening the browser itself. On android the openAuth works correctly, in iOS the content is only loaded using the `.open` method, if I use the `.openAuth` it keeps "refreshing" the page with the browser changing from modal to fullscreen and constantly asking me the openAuth dialog to sign in. Below are images of that behaviour:

Content loaded on `.open` method:
![Screen Shot 2020-10-14 at 09 25 39](https://user-images.githubusercontent.com/14251143/95988817-d36eaf00-0dff-11eb-9826-747ac956f9e0.png)

Blank loop when using `.openAuth` method:
![Screen Shot 2020-10-14 at 09 26 46](https://user-images.githubusercontent.com/14251143/95988879-e8e3d900-0dff-11eb-9b78-44725e57551f.png)
![Screen Shot 2020-10-14 at 09 27 10](https://user-images.githubusercontent.com/14251143/95988884-eaad9c80-0dff-11eb-9e17-daa25b9eddc9.png)

### Which platform(s) does your issue occur on?
iOS iPhone 11 Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.13.0
- Plugin(s):
```json
{
"dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "axios": "^0.19.2",
    "immer": "^7.0.7",
    "lottie-ios": "^3.1.8",
    "lottie-react-native": "^3.5.0",
    "polished": "^3.6.5",
    "prop-types": "^15.7.2",
    "qs": "^6.9.4",
    "react": "16.13.1",
    "react-native": "0.62.2",
    "react-native-code-push": "^6.3.0",
    "react-native-dropdown-picker": "^3.1.11",
    "react-native-fast-image": "^7.0.2",
    "react-native-flash-message": "^0.1.15",
    "react-native-flipper": "^0.62.0",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-image-crop-picker": "^0.32.2",
    "react-native-image-picker": "^2.3.3",
    "react-native-inappbrowser-reborn": "^3.4.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-masked-text": "^1.13.0",
    "react-native-reanimated": "^1.10.1",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.10.1",
    "react-native-shimmer-placeholder": "^1.0.36",
    "react-native-ultimate-config": "^3.2.3",
    "react-native-vector-icons": "^7.0.0",
    "react-native-webview": "^10.3.3",
    "react-redux": "^7.2.1",
    "reactotron-react-native": "^5.0.0",
    "reactotron-redux": "^3.1.2",
    "reactotron-redux-saga": "^4.2.2",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.1",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.2.2",
    "babel-plugin-root-import": "^6.4.1",
    "commitlint": "^11.0.0",
    "eslint": "7.6.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-import-resolver-babel-plugin-root-import": "^1.1.1",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.5",
    "eslint-plugin-react-hooks": "^4.0.8",
    "husky": "^4.3.0",
    "jest": "^26.2.2",
    "lint-staged": "^10.4.0",
    "metro-react-native-babel-preset": "^0.61.0",
    "prettier": "^2.0.5",
    "react-test-renderer": "16.13.1"
  }
}
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Implement InAppBrowser, and try to openAuth the url: `https://id.layers.digital`

**Comment by jdnichollsc** [comment]
Please share the code you're using in order to debug your issue :)

**Comment by lukemorales** [comment]
@jdnichollsc besides the code styling the page, this is the function that triggers the InAppBrowser auth:
```js
const handleAuthFlow = async () => {
  try {
    if (await InAppBrowser.isAvailable()) {
      const { type, url } = await InAppBrowser.openAuth(
       'https://id.layers.digital',
       'horadasaidaoauth://',
        {
          // iOS Properties
          ephemeralWebSession: false,
          preferredBarTintColor: '#00B8AD',
          preferredControlTintColor: '#fff',
          // Android Properties
          showTitle: true,
          enableUrlBarHiding: true,
          enableDefaultShare: false,
          toolbarColor: '#00B8AD',
          secondaryToolbarColor: '#00B8AD',
        }
      );

      if (type === 'success' && url) {
        Linking.openURL(url);
      }
    } else Linking.openURL('https://id.layers.digital');
  } catch (error) {
    Linking.openURL('https://id.layers.digital');
  }
};
```

**Comment by lukemorales** [comment]
Also something I noticed is that, even with the `.open` method, it only loads the content if I open in normal Safari first. If I don't, it loads so slowly that it doesn't finish loading, but if I open once in Safari (whether clicking the safari button on the InAppBrowser, or opening the Sarafi app) it loads every time after.

**Comment by jdnichollsc** [comment]
Do you have the same experience using `Linking.openURL` instead?

**Comment by lukemorales** [comment]
> Do you have the same experience using `Linking.openURL` instead?

I was actually using that way and Apple rejected the app because of that behavior, so nope, with Linking it was actually working. 😕

**Comment by jdnichollsc** [comment]
What are you using to authenticate your users? A JWT token? Are you sending that token to the app in that redirection?

**Comment by lukemorales** [comment]
> What are you using to authenticate your users? A JWT token? Are you sending that token to the app in that redirection?

It's an SSO Auth, users would login in the website and the next URL would be the redirected URL to the app with the token within the URL. I'm opening the website with some URL Params do the website can identify who's asking, but even if I just use the normal URL without any Params, the website does not load. 
Just reinforcing, it works fine on Android, but for iOS, that is my main use so that Apple can approve my app, it doesn't work.

**Comment by jdnichollsc** [comment]
What happen if you enable **ephemeralWebSession**?

**Comment by lukemorales** [comment]
Same result but with no dialog box

**Comment by jdnichollsc** [comment]
In my team, we were using Okta Web widget before without any issue. Maybe you can try that solution if you want, also with the widget you can customize the html, css, etc :)

**Comment by lukemorales** [comment]
@jdnichollsc Okta Web Widget won't really suit the app, there's nothing we can do to debug why it's not loading? Did you try and managed to load the `https://id.layers.digital`URL?

**Comment by jdnichollsc** [comment]
Oh sorry, I don't have time to debug external solutions using free support (without a Tidelift subscription or being a sponsor), try debugging from Xcode 🙂

**Comment by lukemorales** [comment]
@jdnichollsc ok, so I tried running the demo code opening the google URL. Same behaviour: it doesn't load the content unless I click the open in safari button, wait for safari to load the URL, then when I come back to the app the page is loaded within the InAppBrowser and every time after that the content loads, even if I change the URL. This doesn't seems to be an issue with the URL I'm trying to access, but rather an issue with the iOS implementation (whether is something on the code itself, or something that's not working very well within an emulator, but if it's just in emulation how can I send this to production if I cannot test it and ensure it's functionality?)
I don't think this request is valid as free suport, but rather trying to figure out a bug, that's why I asked if you managed to just load a single URL

**Comment by jdnichollsc** [comment]
> it doesn't load the content unless I click the open in safari button

Did you verify from a native app to compare? how do you know it's a mistake?

> something that's not working very well within an emulator

Did you verify from an iOS device? Try debugging from Xcode with a device connected

> that's why I asked if you managed to just load a single URL

The url used from the demo project works as expected :)

**Comment by lukemorales** [comment]
@jdnichollsc just managed to test this on my iOS device. The lib worked flawlessly , including the openAuth with the `ephemeralWebSession` disabled. There's seems to be an issue with the emulator realm

**Comment by jdnichollsc** [comment]
Awesome, thanks for let me know! <3
