### ISSUE TITLE
[Bug] Unable resolve module in new version 3.5.0 

### ISSUE THREAD

**Issue by trqvinh90** [proyecto26/react-native-inappbrowser#199]
Hi, I am just installed the newest version 3.5.0 and I got error when running.
Please note that the previous version worked well.
Please see this attached screenshot for more details: 
![image](https://user-images.githubusercontent.com/29704094/96227485-635a5780-0fbe-11eb-8da7-1f120e2936f4.png)

Btw many thanks for this great library 👍

**Comment by sharifhh** [comment]
Change your package.json to this
"react-native-inappbrowser-reborn": "proyecto26/react-native-inappbrowser#pull/200/head",
Currently the build is broken, this one will fix it for now

**Comment by webmedya** [comment]
@sharifhh thanks, we are waiting for new build

**Comment by jdnichollsc** [comment]
Can you try the last version 3.5.1?

Please let me know, also to verify that last code from TypeScript projects would be awesome!
