### ISSUE TITLE
iOS 10: safariViewController, Url and redirection issues 

### ISSUE THREAD

**Issue by mkarimv** [proyecto26/react-native-inappbrowser#2]
Hi, 
I have a bit of an issue with the openAuth for iOS 10. I use your library to authentication the user and retrieve the token from the url, it works for iOS 11+ but not for iOS10. 

Also i have an issue with the implementation of safariViewController when i have a modal open the browser close very immediately ( there is a fix in: https://github.com/naoufal/react-native-safari-view/pull/69/commits/a7543574ff7635fdf9c87759de87e99fc8a7a369)

**Comment by jdnichollsc** [comment]
@mkarimv thanks for report this issue, let me check 👍

**Comment by jdnichollsc** [comment]
@mkarimv in this moment, **openAuth** requires iOS 11 or greater
