### ISSUE TITLE
Android animations support

### ISSUE THREAD

**Issue by maestor** [proyecto26/react-native-inappbrowser#20]
Hi and first thanks for awesome library, I have search one replacement for two quite inactive projects I used separately for that purpose with iOS and Android. Luckily found this.

In [react-native-custom-tabs](https://github.com/droibit/react-native-custom-tabs#customize-for-android), there is nice animation props for polish look and feel. Wouldn't that be doable polishment for this too?

I don't have much time and/or skills yet, but I'm interested to give support if somebody could be main contributor if this isn't bad idea at all.

**Comment by jdnichollsc** [comment]
@maestor Done, check the last version (1.3.8)
