### ISSUE TITLE
Empty or invalid URL app crashes

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [proyecto26/react-native-inappbrowser#204]
I want to open the browser if I have no URL. then my app crashed. 

` const validate_url = async () =>{

    try {
        if (await InAppBrowser.isAvailable()) {
          const result = await InAppBrowser.open(url, {
          // iOS Properties
          dismissButtonStyle: 'cancel',
          preferredBarTintColor: '#453AA4',
          preferredControlTintColor: 'white',
          readerMode: false,
          animated: true,
          modalPresentationStyle: 'fullScreen',
          modalTransitionStyle: 'coverVertical',
          modalEnabled: true,
          enableBarCollapsing: false,
          // Android Properties
          showTitle: true,
          toolbarColor: '#6200EE',
          secondaryToolbarColor: 'black',
          enableUrlBarHiding: true,
          enableDefaultShare: true,
          forceCloseOnRedirection: false,
          // Specify full animation resource identifier(package:anim/name)
          // or only resource name(in case of animation bundled with app).
          animations: {
            startEnter: 'slide_in_right',
            startExit: 'slide_out_left',
            endEnter: 'slide_in_left',
            endExit: 'slide_out_right'
          },
        })
        
      }
     // else Linking.openURL(url)
   }
    catch (error) {
      alert('Error MEssage')
    }
  }`

**Comment by jdnichollsc** [comment]
Please attach a repository in order to debug your issue 👍
