### ISSUE TITLE
Browser crashes on Android when Chrome is not installed/disabled

### ISSUE THREAD

**Issue by TheWirv** [proyecto26/react-native-inappbrowser#206]
Hi, I have been using this package for a long time in production now, and now I have a crash bug on Android since updating to 3.5.1.

I have Firefox installed on my phone and immediately disabled Chrome afterwards. Before updating InAppBrowser, everything worked just fine and the Firefox would just open as a "Custom Tab" -- a special "Custom Tab" version of Firefox, mind you, just like the "real" Chrome Custom Tab. So it's not like it would open the fully blown Firefox and pulling the end user out of the flow.

My suspicion is that the most recent `browserPackage` feature is the culprit here. I don't want to supply a browser package because I don't want to pin down the user to a specific browser. But I think that the default value for `browserPackage` doesn't work properly since before this feature everything worked fine, as I was mentioning.

**Comment by TheWirv** [comment]
I can confirm: Downgrading to v3.4.0 (and leaving everything else as is) fixes the issue. Yet, I still would very much like to use the most up-to-date version of the package for obvious reasons.

**Comment by jdnichollsc** [comment]
Hi Marcel, please use `browserPackage: ''` if you don't want to use Chrome by default

**Comment by jdnichollsc** [comment]
I'm going to add more utilities in order to get the preferred **browserPackage** depending of the available packages of the device, in the meantime you can put that option with a empty string like a workaround

**Comment by jdnichollsc** [comment]
Other option could be adding firefox package, like this: https://github.com/proyecto26/react-native-inappbrowser/pull/157/files#diff-78dea708a38f9ddae320d241d7136ca6d38f9ec1bea0275bf062638449b5ff4aR22
What do you think? :)

**Comment by TheWirv** [comment]
> Other option could be adding firefox package, like this
@jdnichollsc that would definitely be smart. Just in general, adding the most used browsers. For my situation it wouldn't help because I use Firefox Nightly and that has a separate bundle ID, which would be `CLASS_NAME`, I think, in that diff.

I'll try `browserPackage: ''` though. Thanks so much!
