### ISSUE TITLE
The 'dismissButtonStyle' option is displaying 'cancel' after being set to 'done' or 'close'

### ISSUE THREAD

**Issue by tyIer** [proyecto26/react-native-inappbrowser#211]
### Issue

- The `dismissButtonStyle` option is displaying 'cancel' after being set to 'done' or 'close'
### Device type 
- Tested on iOS 12.2 / `react-native` 0.60.3

### How to recreate

- Initialize `InAppBrowser` with the option: `dismissButtonStyle: 'done'`
- Run application - the browser seems to override the option and only displays 'cancel' in the top left of the toolbar

### Is there any code involved? 
```
try {
  if (await InAppBrowser.isAvailable()) {
    InAppBrowser.openAuth(url, deepLink, {
      ephemeralWebSession: false,
      dismissButtonStyle: 'done',
      animated: true,
      modalEnabled: true,
    }).then(response => {
      if (response.type === 'success') {
        Linking.openURL(url)
      }
    })
  } else {
    Linking.openURL(url)
  }
} catch (error) {
  Alert.alert(error.message)
}
```

**Comment by jdnichollsc** [comment]
These options are not supported in the authentication flow, that's limited by iOS Authentication services

**Comment by Shan7anu** [comment]
If anyone still wondering, below are working fine.

`dismissButtonStyle: 'cancel'`
`dismissButtonStyle: 'done'`
`dismissButtonStyle: 'close'`

Reference Link: https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/dismissbuttonstyle

**Comment by jdnichollsc** [comment]
@Shan7anu sorry mate, did you check the documentation? downvote for Apple, we're limited by them ;)

**Comment by Shan7anu** [comment]
@jdnichollsc Updated my comment with the vote lol.
