### ISSUE TITLE
Could not download eventbus-3.2.0.jar

### ISSUE THREAD

**Issue by joegoodall1** [proyecto26/react-native-inappbrowser#214]
For some reason, seeing this error when building on CI.

<img width="941" alt="Screenshot 2020-11-14 at 23 29 26" src="https://user-images.githubusercontent.com/8888799/99159129-ba447100-26d1-11eb-9a45-c723cc1c1407.png">

**Comment by jdnichollsc** [comment]
Hello Joe, can you try the last step of the manual installation process? https://github.com/proyecto26/react-native-inappbrowser#android

Let me know 🙂

**Comment by joegoodall1** [comment]
@jdnichollsc Thanks for the quick response.

Unfortunately, making changes to `proguard-rules.pro` didn't work. Still getting the error.

**Comment by joegoodall1** [comment]
Not sure what's going on.

Removing this project and the building CI succeeds. Adding this library, and it breaks with the above error 🤷‍♂️.

**Comment by jdnichollsc** [comment]
What's the configuration of your build.gradle?

**Comment by jdnichollsc** [comment]
Check our example project https://github.com/proyecto26/react-native-inappbrowser/blob/develop/example/android/build.gradle#L23

**Comment by joegoodall1** [comment]
> What's the configuration of your build.gradle?

```
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "29.0.0"
        // v16.1.0 causes problems with react-native-device-info - see: https://github.com/react-native-community/react-native-device-info/issues/802
        googlePlayServicesVersion = "16.0.0"
    }
    repositories {
            google()
            jcenter()
        }
    dependencies {
        classpath('com.android.tools.build:gradle:3.6.3')
        // RNFirebase specifies 4.2.0 but it breaks codepush
        classpath('com.google.gms:google-services:4.0.1')
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        jcenter()
        maven {
            url 'https://www.jitpack.io'
        }
        maven {
           // Local Maven repo containing AARs with JSC library built for Android
           url "$rootDir/../node_modules/jsc-android/dist"
       }
    }
}
```

**Comment by jdnichollsc** [comment]
Try this solution https://github.com/proyecto26/react-native-inappbrowser/issues/226#issuecomment-754925411
