### ISSUE TITLE
Getting Crash while opening "Http://www.google.com"

### ISSUE THREAD

**Issue by subinsuresh991** [proyecto26/react-native-inappbrowser#218]
### Make sure to check the demo app(s) for sample usage 
Checked the demo app. its crashing
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

Getting crash on Android device only

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `react-native --version` to fetch it)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Download the demo app, open url "Http://www.google.com"

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by jdnichollsc** [comment]
Please attach a repo to be able to reproduce this issue :)

**Comment by subinsuresh991** [comment]
@jdnichollsc As I mentioned earlier issue is happening in the example application also in this repo.

**Comment by jdnichollsc** [comment]
I'm not getting that error testing from some Android devices (Galaxy Note, etc). Please share more details

**Comment by subinsuresh991** [comment]
Plz try URL Https://www.google.com
H instead of h

**Comment by jdnichollsc** [comment]
That's handled by Chrome Custom Tabs, if you want to avoid native exceptions you can add some validations from JS side, e.g:
`const url = encodeURI( "URL HERE".toLowerCase()
)`

**Comment by subinsuresh991** [comment]
@jdnichollsc It's not a reliable solution. If I am trying to open any link which includes capital letters like 
"https://www.amazon.in/Amazon-Brand-Symbol-Mens-Sweatshirt/dp/B07Y8T2F5G/?_encoding=UTF8&pd_rd_w=0Vc1R&pf_rd_p=e60c70f0-0541-4ba5-b6fc-ada95198a5fe&pf_rd_r=1KGK5JM033KKNRXV9GSS&pd_rd_r=c4eb4c67-0a30-4b21-bd8a-7ee4f304a692&pd_rd_wg=qPWbd&ref_=pd_gw_crs_zg_bs_1571271031"

won't be working if its converted to lowercase. It will show a 404 page.

**Comment by jdnichollsc** [comment]
Oh I understand your point now, any pull request is welcome! 👍

**Comment by jdnichollsc** [comment]
Hello folks, please check the new version [3.6.0](https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.6.0) 👍

If the issue persist, any pull request is welcome! <3
