### ISSUE TITLE
go Back

### ISSUE THREAD

**Issue by 0707236659** [proyecto26/react-native-inappbrowser#219]
how can I go back to the previous page when  I click on the x or <- button.

**Comment by jdnichollsc** [comment]
When you open the brower, it returns a promise that's resolved when the browser is dismissed/closed, then you can redirect your users 👍

**Comment by 0707236659** [comment]
> When you open the brower, it returns a promise that's resolved when the browser is dismissed/closed, then you can redirect your users 👍
I mean when the user opens a link for example. Then the keep opens another link on that web. The browser will link to that link. but when the user press close or ( <- ) button.  the browser is not showing the previous link but it closes the browser and returns the app.

**Comment by jdnichollsc** [comment]
Oh that's a native behavior, but any pull request is welcome! 👍
