### ISSUE TITLE
Question: Authentication without rendering the inappbrowser

### ISSUE THREAD

**Issue by avlonder** [proyecto26/react-native-inappbrowser#220]
Is it possible to render the inappbrowser (with animation) only if really necessary (if your user name and password are not stored in your browser)? This would improve the UX incredibly :)

**Comment by jdnichollsc** [comment]
As far as I know SafariViewController don't support that, but any pull request is welcome! 👍

**Comment by avlonder** [comment]
Or alternatively, is there a way to make the inappbrowser transparent/render it offscreen? This may be a sufficient workaround

**Comment by jdnichollsc** [comment]
That's not allowed from iOS, the App Store Review Guidelines (5.1.1) specifically say that:
> SafariViewContoller must be used to visibly present information to users; the controller may not be hidden or obscured by other views or layers.
