### ISSUE TITLE
Customize toolbar title and hide address URL while opening URL.

### ISSUE THREAD

**Issue by amit13091992** [proyecto26/react-native-inappbrowser#221]
While opening inAppBrowser I want to hide the address URL and customize the title name. Please suggest some solution.
I have tried the 
`showTitle: false `
for Android platform but it did not work as expected.

Platform tested on:
- iOS and Android

```
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-inappbrowser-reborn": "^3.5.1",
```

**Comment by jdnichollsc** [comment]
That's not supported, check more details here https://stackoverflow.com/a/40157921/1532821
