### ISSUE TITLE
Adding Component inside the bowser

### ISSUE THREAD

**Issue by Bayramito** [proyecto26/react-native-inappbrowser#225]
Is there anyway to add any component inside the browser as a footer or header. 

I want to have a interaction with the user via custom component like rating the link the he opened etc.. 
Is there any way to implement it into this browser ?

**Comment by jdnichollsc** [comment]
It's the system browser instead of a WebView component so that's not supported

**Comment by jdnichollsc** [comment]
I mean, it's not supported from JS side, but you can validate a native implementation with Chrome Custom Tabs and SafariViewController 👍
