### ISSUE TITLE
Getting this error when i run react-native run-android

### ISSUE THREAD

**Issue by Bayramito** [proyecto26/react-native-inappbrowser#226]
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.greenrobot:eventbus:3.+.
     Required by:
         project :app > project :react-native-inappbrowser-reborn
      > Skipped due to earlier error

* Try:`

**Comment by jdnichollsc** [comment]
Please attach a repo to reproduce this issue

**Comment by Bayramito** [comment]
Fixed it bt changing mavenLocal() to mavenCentral()
