### ISSUE TITLE
Want to know the modal style for ios

### ISSUE THREAD

**Issue by nwpnkmngm** [proyecto26/react-native-inappbrowser#227]
I want to know what type of modal for ios style of In app browser ?
I want to use this style to custom modal in my application

thanks

**Comment by jdnichollsc** [comment]
Sorry, can you clarify this issue?

**Comment by jdnichollsc** [comment]
Check the documentation of the native API used from iOS, let me know if you find any option to customize the modal, any pull request is welcome! https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller
