### ISSUE TITLE
InAppBrowser.open() promise resolve immediately on ios - not when the inappbrowser in actually closed

### ISSUE THREAD

**Issue by gbalduzzi** [proyecto26/react-native-inappbrowser#228]
Version 3.5.1 of the library 
### Which platform(s) does your issue occur on?
- iOS
- tested on version 13.6.1 and 14.3
- Both emulator and real iPhone 7 Plus

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.9.0
- React native 0.63.2

I'm using the exact same code from the readme to properly set the statusbar style:

```
const openUrl = async (url) => 
    const oldStyle = StatusBar.pushStackEntry({ barStyle: 'dark-content', animate: false });
    const result = await InAppBrowser.open(url)
    StatusBar.popStackEntry(oldStyle);
    console.log('RESULT:', result)
}
```

The problem is, **on iOS**, `await InAppBrowser.open(url)` immediately returns and I can see the log ` RESULT: {"type": "dismiss"}` while the inappbrowser is showing. The statusbar gets the `dark-content` for less then a second then immediately return to the `white-content`.

In android the `.show()` promise is resolved when the browser is really closed.

Am I doing something wrong?

**Comment by gbalduzzi** [comment]
I discovered something new - probably it should be considered a bug.

In my app, I show a `Modal` with a bunch of options. When the user taps on one of them, I open the corresponding link inside the inappbrowser. I have a function like this:

```
onOptionSelected = (url) => {
   this.popupRef?.dismiss()

  this.openUrl(url)
}
```

**When my modal is closed, the `.open()` promise is resolved**

If I add a timeout (or if I don't dismiss my own modal), I don't encounter the problem:

```
onOptionSelected = (url) => {
   this.popupRef?.dismiss()
  setTimeout(() => {
     this.openUrl(url)
  }, 1000)
}
```

**Comment by jdnichollsc** [comment]
Please attach any reproducible demo from a GitHub repository
