### ISSUE TITLE
can the height of the view be adjusted?

### ISSUE THREAD

**Issue by digitalml** [proyecto26/react-native-inappbrowser#229]
Can the height of the view / modal be adjusted at all? Looking to hide the bottom bar so a user cant press the safari button.

**Comment by jdnichollsc** [comment]
Can you attach a screenshot to clarify your issue?

**Comment by digitalml** [comment]
Trying to hide the part in red... My thoughts were i could maybe put a view over this view? or extend the height of the entire view outside the visible screen bounds.

![Simulator Screen Shot - iPhone 11 - 2021-01-31 at 16 04 59](https://user-images.githubusercontent.com/1479241/106402430-4c5d3b00-63de-11eb-86cf-534e4bc03f77.png)

**Comment by jdnichollsc** [comment]
That's limited by Chrome Custom Tabs/SafariViewController, let me know if you find any native configuration to do that 👍

**Comment by digitalml** [comment]
any way you know of to place a view OVER the displayed SafariViewController?

**Comment by jdnichollsc** [comment]
As far as I know, that's only supported from WebView

**Comment by jdnichollsc** [comment]
Any pull request is welcome! <3
