### ISSUE TITLE
Support ephemeralWebSession for non openAuth calls? 

### ISSUE THREAD

**Issue by FrancisLeigh** [proyecto26/react-native-inappbrowser#231]
I'm wondering if this is something you have considered. In my use-case it would be great to be able to set this property to true when just using `.open()`

**Comment by jdnichollsc** [comment]
Hello mate, that option is only supported by [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio?language=objc)
