### ISSUE TITLE
Property 'url' does not exist on type 'AuthSessionResult'.

### ISSUE THREAD

**Issue by avlonder** [proyecto26/react-native-inappbrowser#232]
In VS Code, the following code
```
const { type, url: newUrl } = await InAppBrowser.openAuth(url, redirectUrl, {
        showTitle: false,
        enableUrlBarHiding: true,
        enableDefaultShare: false,
        ephemeralWebSession: false
      });
```
yields the TypeScript error *Property 'url' does not exist on type 'AuthSessionResult'.*

tsconfig.json:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["es6"],
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitAny": false,
    "strict": true,
    "strictNullChecks": true,
    "target": "esnext"
  },
  "include": [
    "./src",
    ".eslintrc.js",
    "index.js"
  ],
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js"
  ]
}
```

**Comment by jdnichollsc** [comment]
The type is here https://www.github.com/proyecto26/react-native-inappbrowser/tree/develop/index.d.ts

What do you think?

**Comment by avlonder** [comment]
I patched it with
```
type AuthSessionResult = {
    type: 'cancel' | 'dismiss' | 'success',
    url?: string
}
```
but not sure if this doesn't break anything.

**Comment by jdnichollsc** [comment]
It looks like you're not validating the type of the response

**Comment by avlonder** [comment]
Ow, ok, I see... What I should have done is:
```
const res = await InAppBrowser.openAuth(url, redirectUrl, {
        showTitle: false,
        enableUrlBarHiding: true,
        enableDefaultShare: false,
        ephemeralWebSession: false
      });
if(res.type === 'success') await Linking.openURL(res.url);
```
Thanks!

**Comment by aajinkya1203** [comment]
> Ow, ok, I see... What I should have done is:
> 
> ```
> const res = await InAppBrowser.openAuth(url, redirectUrl, {
>         showTitle: false,
>         enableUrlBarHiding: true,
>         enableDefaultShare: false,
>         ephemeralWebSession: false
>       });
> if(res.type === 'success') await Linking.openURL(res.url);
> ```
> 
> Thanks!

For those wondering, what's happening in this code. The ```url``` parameter is available only when ```res.type``` is checked for its value and only if it's successful, then only it lets you access this.

**Comment by tonicprism** [comment]
I have the same problem but with jest. When i run my jest test is happening the follow error:
`error TS2339: Property 'params' does not exist on type 'AuthSessionResult'`. But in accord from what you guys said, need add a verification from the response type and i'm already doing this.
`const hasResponseAndIsSuccessfully = response && response.type === 'success'`

**Comment by tonicprism** [comment]
> I have the same problem but with jest. When i run my jest test is happening the follow error: `error TS2339: Property 'params' does not exist on type 'AuthSessionResult'`. But in accord from what you guys said, need add a verification from the response type and i'm already doing this. `const hasResponseAndIsSuccessfully = response && response.type === 'success'`

The error is still happerns. In some way, is needed a declarative way to add the response.type verification if a assign to a variable this doesnt work properly. Someone have to why this happens?

**Comment by jdnichollsc** [comment]
> > I have the same problem but with jest. When i run my jest test is happening the follow error: `error TS2339: Property 'params' does not exist on type 'AuthSessionResult'`. But in accord from what you guys said, need add a verification from the response type and i'm already doing this. `const hasResponseAndIsSuccessfully = response && response.type === 'success'`
> 
> The error is still happening. In some way, if i assign the response.type === 'success' verification to a variable this doesnt work properly. Someone knows why this happens?

Please share a repository to be able to reproduce the issue 🙂

**Comment by tonicprism** [comment]
> 

The repository is private, but i can share the code snippet.
