### ISSUE TITLE
Error: InAppBrowser not available when chrome are not installed

### ISSUE THREAD

**Issue by pedroalefm** [proyecto26/react-native-inappbrowser#233]
### Which platform(s) does your issue occur on?
- Android
- emulator

### Please, provide the following version numbers that your issue occurs with:

react-native-cli: 2.0.1
react-native: 0.63.4
 "dependencies": {
    "@react-keycloak/native": "^0.5.2",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-inappbrowser-reborn": "^3.5.1"
  },

The tab open when chrome are installed, but on a device chrome are not installed, the dependency dont open a tab.

**Comment by jdnichollsc** [comment]
We're using **Chrome Custom Tabs** from **Android**, check the current list of the supported packages: https://github.com/proyecto26/react-native-inappbrowser/blob/develop/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java#L53

Any pull request to add new packages is always welcome! e.g: https://github.com/proyecto26/react-native-inappbrowser/pull/157/files#diff-78dea708a38f9ddae320d241d7136ca6d38f9ec1bea0275bf062638449b5ff4aR22
