### ISSUE TITLE
InAppBrowser.openAuth() never gets resolved

### ISSUE THREAD

**Issue by VivekNeel** [proyecto26/react-native-inappbrowser#234]
Recently our app got rejected by apple for social logins. So i have this solution using InAppBrowser.openAuth() but the issue is that our app never gets redirected **(because the promise does not get resolved hence Linking.openUrl never gets called)** it just redirects to the redirected url in the in app browser after logging in successfully

I have the following configuration : 

```
userPoolId: awsExports.UserPoolId,
  userPoolWebClientId: awsExports.UserPoolClientId,
  storage: MemoryStorage,
  identityPoolId: awsExports.IdentityPoolId,
  region: awsExports.Region,
  authenticationFlowType: 'USER_PASSWORD_AUTH',
  aws_appsync_graphqlEndpoint: awsExports['API-Endpoint'],
  aws_appsync_region: awsExports.Region,
  aws_appsync_authenticationType: 'AWS_IAM',
  graphql_headers: graphqlHeader,
  oauth: {
    domain: awsExports.UserPoolDomain,
    scope: UserPoolClients.mobileClientScope,
    redirectSignIn: UserPoolClients.mobileClientCallbackURLs[0],
    redirectSignOut: UserPoolClients.mobileClientLogoutURLs[0],
    responseType: 'code',
    urlOpener: delegateToInAppBrowser ? urlOpener : null,
  },
```
```
async function urlOpener(url: string, redirectUrl: string) {
  try {
    if (await InAppBrowser.isAvailable()) {
      InAppBrowser.openAuth(url, redirectUrl, {
        // iOS Properties
        ephemeralWebSession: true,
        // Android Properties
        showTitle: false,
        enableUrlBarHiding: true,
        enableDefaultShare: false,
      }).then((response) => {
        console.log('.......response', response);
        if (
          response.type === 'success'
          && response.url
        ) {
          Linking.openURL(response.url);
          InAppBrowser.closeAuth();
        }
      });
    } else {
      Linking.openURL(url);
    }
  } catch (error) {
    console.log('.......error', error);
    Linking.openURL(url);
  }
}
```
Neither catch or then block gets called after providing credentials for any provider facebook, google , apple

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- emulator and device.

**Comment by jdnichollsc** [comment]
Check our example https://github.com/proyecto26/react-native-inappbrowser/blob/develop/example/App.js#L113, it's working as expected, I don't understand your backend configuration, but you need to redirect to the app using `redirectUrl` param (with the deep linking configuration of your app)

**Comment by Ajmal0197** [comment]
https://dev.to/ajmal0197/react-native-twitch-auth-using-deeplinking-and-react-native-inappbrowser-reborn-1hff

**Comment by ojaspatharkar-qure** [comment]
I am still getting this issue. it is happening only when i freshly install the app and try login for the very first time. any solution?. we are using keycloak login inside the InAppBrowser.
