### ISSUE TITLE
Unsupported URL scheme

### ISSUE THREAD

**Issue by haveamission** [proyecto26/react-native-inappbrowser#238]
So I want to use In App Browser to open a link for PayPal (specifically Connect to Paypal), and then redirect to a URL scheme once this is done.

However I am getting the error:

"Only HTTP and HTTPS URLs are supported".

Is there no way to do deeplinking with url schemes inside In App Browser?

**Comment by jdnichollsc** [comment]
Can you attach a GitHub repository to reproduce your issue?

**Comment by haveamission** [comment]
Just use literally any non-HTTP or non-HTTPS url as the redirect in an OAuth connection...

```
import React, { Component } from "react";
import {
    View,
    Text,
    TouchableOpacity
  } from 'react-native';
import { InAppBrowser } from 'react-native-inappbrowser-reborn';

let client_id = "paypal-client-id-goes-here";

// This is where the issue comes in
let redirect_uri = "scheme://callbackuri";

let uri = 'https://www.sandbox.paypal.com/connect/?';
let params = { 
flowEntry: "static",
client_id: client_id,
scope: "openid profile email address",
redirect_uri: redirect_uri,
response_type: "code",
 }

let search = new URLSearchParams(params);

let url = uri + search.toString();

 export default class Test extends Component {

async test() {
    if (await InAppBrowser.isAvailable()) {
        const result = await InAppBrowser.open(url);
}
}

    render() {
        return(
<View>
    <TouchableOpacity onPress={this.test}>
        <View style={{backgroundColor: "black"}}>
            <Text style={{color: "white"}}>Launch PayPal</Text>
            </View>
            </TouchableOpacity>
            </View>
        )    
}
  }
```

It'd be hard to make a Github repo that reproduces this, as I'm using my own PayPal client ID, but all you need is the code above, with your own PayPal ID and it'll happen.

Looks like this:

<img width="407" alt="Screen Shot 2021-02-19 at 2 07 25 PM" src="https://user-images.githubusercontent.com/10475533/108549946-de5cb300-72bb-11eb-940d-b15ffa02ff74.png">

**Comment by jdnichollsc** [comment]
You need to use InAppBrowser.openAuth instead

**Comment by haveamission** [comment]
Thank you!

**Comment by haveamission** [comment]
@jdnichollsc I am getting the same error with openAuth.

**Comment by jdnichollsc** [comment]
Please share your code, did you configure the deep link from Android/iOS folders of your project?

**Comment by haveamission** [comment]
The deeplink is setup in Xcode (I'm not testing it on Android yet).

And the code I shared above is the code I am using to generate this error. That's literally all of it.

If you want my iOS deeplink code, here it is:

```
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

I seem to be getting this error even when I switch my scheme to one with http, so it may be some other issue. I'm investigating and trying to reproduce what's happening.

**Comment by haveamission** [comment]
Interesting. It seems to be due to the URL query arguments. When I cut those off, it seems to be working (though PayPal won't, because it needs those arguments).

`https://www.sandbox.paypal.com/connect/`

Works

`https://www.sandbox.paypal.com/connect/?flowEntry=static&client_id=my-paypal-client-id&scope=openid profile email address&response_type=code&redirect_uri=scheme://callbackuri`

doesn't work

**Comment by haveamission** [comment]
It's due to needing to encode spaces in URLs.

Ok, well that makes sense. That's what caused the error.

**Comment by jdnichollsc** [comment]
You enable deep linking (iOS) from Info.plist, check the README with the example, so did you fix this issue? 🙂

**Comment by haveamission** [comment]
No no, my deeplinking was already working just fine and completely configured correctly.

The issue was that the URL was not encoded.

Once the URL was encoded, this issue disappeared.

The problem is fixed, but it was due to URL encoding.

**Comment by jdnichollsc** [comment]
Awesome, congrats mate!

**Comment by Ajmal0197** [comment]
https://dev.to/ajmal0197/react-native-twitch-auth-using-deeplinking-and-react-native-inappbrowser-reborn-1hff

**Comment by merohitnishad** [comment]
Please share encoding url part

**Comment by MayoudP** [comment]
I want to achieve the same thing, but with google sign on, I need to specify redirect URL, else I'm getting some error like the screen below : 

<img src="https://github.com/proyecto26/react-native-inappbrowser/assets/48682041/a37aa647-4fcf-45e5-bf31-11a2d80efd20" data-canonical-src="https://github.com/proyecto26/react-native-inappbrowser/assets/48682041/a37aa647-4fcf-45e5-bf31-11a2d80efd20" width="200" />


How can I specify my_app:// redirect scheme for google sign in ? 

<img width="300" alt="Capture d’écran 2023-06-15 à 13 47 52" src="https://github.com/proyecto26/react-native-inappbrowser/assets/48682041/d85cdfae-cabc-41d4-9ea7-9eb5f2dffb17">

Thanks for the clarification 🙏
