### ISSUE TITLE
Android `openAuth` method cancels browser on deep link redirection

### ISSUE THREAD

**Issue by WeshGuillaume** [proyecto26/react-native-inappbrowser#239]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
When trying to use a deep link redirect URL (`moodwork://sso_profiling/?param=fewfwe`) using `openAuth`, it works on IOS by returning `{ type: 'success', ... }`, but `{ type: 'cancel' }` on Android. Ideally, I would like to retrieve the URL the same way I do on IOS

### Which platform(s) does your issue occur on?
- Android emulator and device
- 
### Please, provide the following version numbers that your issue occurs with:
``` json
{
  "react-native": "0.63.3",
  "react-native-inappbrowser-reborn": "^3.5.1"
}
```

#### Android Manifest scheme part
``` xml
<activity
          android:name=".MainActivity"
          android:label="@string/app_name"
          android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
          android:windowSoftInputMode="adjustResize"
          android:launchMode="singleTask"
          android:exported="true">
          <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
          <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="moodwork" android:host="sso_profiling" />
          </intent-filter>
      </activity>
```

#### Browser instanciation
``` javascript
export function getDeepLink(path = "") {
  const scheme = "moodwork";
  const prefix =
      Platform.OS === "android" ? `${scheme}://sso_profiling/` : `${scheme}://`;
  return prefix + path;
}

export const openBrowser = async (url: string, auth?: boolean) => {
  try {
    const config = {
      dismissButtonStyle: 'cancel',
      preferredBarTintColor: navColor,
      preferredControlTintColor:  Colors.textNavBar,
      readerMode: false,
      modalEnabled: true,
      showTitle: true,
      toolbarColor: navColor,
      secondaryToolbarColor: primaryDarkColor,
      enableUrlBarHiding: false,
      enableDefaultShare: false,
      forceCloseOnRedirection: true,
      waitForRedirectDelay: 1000,
    }
    if (await InAppBrowser.isAvailable()) {
      const result = await (auth ? InAppBrowser.openAuth(url, getDeepLink(), config) : InAppBrowser.open(url, config))
      console.log({ result });
      if (result.type === "success" && result.url) {
        return parseURL(result.url);
      }
    } else {
      Linking.openURL(url)
    }
  } catch (error) {
    console.log({ error })
  }
};

// openBrowser(url, true)

```

#### Redirect link sent back from the Broswer URL
`moodwork://sso_profiling/?param=fewfw4`

#### Result
``` json
{ "type": "cancel" }
```

**Comment by jdnichollsc** [comment]
Please let me know the Android version of your device

**Comment by WeshGuillaume** [comment]
Hey, thanks for the reply !
It happens on Android 10. I'm not proficient in Java, but if I can do anything on the js side let me know :)

**Comment by jdnichollsc** [comment]
Are you getting this same wrong behavior with our demo project?

**Comment by WeshGuillaume** [comment]
Indeed, it looks like it's working on the example 🤔, so it's something I do wrong with the library

**Comment by WeshGuillaume** [comment]
It's actually working in mine with the URL you're using in the example. Maybe the browser cannot handle two redirections. My current flow is the following:
 - The user opens Google Login and logs in
 -  Google redirects to my backend
 - My backend redirects to the deep link

The strange thing is that everything is fine on IOS

**Comment by jdnichollsc** [comment]
> My backend redirects to the deep link

What URL is your backend using for that redirect?

**Comment by WeshGuillaume** [comment]
The backend redirects to moodwork://sso_profiling/?token=...

**Comment by jdnichollsc** [comment]
I mean, is your backend taking care of the current platform? Is your backend redirecting to a different URL depending on the user device?

**Comment by WeshGuillaume** [comment]
No, but it should be handled by the AndroidManifest I suppose. Right now here is the thing:

 - I arrive on the signup screen, then click on one of them, for example Microsoft:
<img width="546" alt="Capture d’écran 2021-02-24 à 16 10 47" src="https://user-images.githubusercontent.com/6558790/109021214-f7e66c00-76ba-11eb-9843-a843fed37d21.png">

 - The user arrives on microsoft websites and logs in, Microsoft then use a redirect_uri to call my backend to generate a token.
 - My backend then renders html (last thing I tried), with a link that contains the deep link
<img width="588" alt="Capture d’écran 2021-02-24 à 16 10 55" src="https://user-images.githubusercontent.com/6558790/109021222-fae15c80-76ba-11eb-8bc8-616e2ed46436.png">
<img width="633" alt="Capture d’écran 2021-02-24 à 16 15 24" src="https://user-images.githubusercontent.com/6558790/109021833-8955de00-76bb-11eb-8ae4-76c1d71aa98f.png"> 
<img width="532" alt="Capture d’écran 2021-02-24 à 16 11 08" src="https://user-images.githubusercontent.com/6558790/109021227-fc128980-76ba-11eb-91b7-529c9c61a7ea.png">

 - Once I confirm that I want to open the link using the app, return InApp Browser returns a `{ type: 'cancel' }`, preventing me to get back the URL.

The config I use and the way I instanciate the browser is the following:
<img width="773" alt="Capture d’écran 2021-02-24 à 16 31 34" src="https://user-images.githubusercontent.com/6558790/109024325-ebafde00-76bd-11eb-877e-b3982a51b3db.png">
<img width="480" alt="Capture d’écran 2021-02-24 à 16 30 58" src="https://user-images.githubusercontent.com/6558790/109024374-fa969080-76bd-11eb-9b98-13796a2cd210.png">
<img width="809" alt="Capture d’écran 2021-02-24 à 16 30 51" src="https://user-images.githubusercontent.com/6558790/109024397-02eecb80-76be-11eb-8011-f686cfbcd05a.png">

 - As the deep link triggers the little modal to select the app I want to open the link to, I suppose this part is working
<img width="827" alt="Capture d’écran 2021-02-24 à 16 34 29" src="https://user-images.githubusercontent.com/6558790/109024563-303b7980-76be-11eb-8ce2-9d1aaba51aec.png">

**Comment by jdnichollsc** [comment]
Try with a backend redirection instead of rendering an HTML :)

**Comment by WeshGuillaume** [comment]
That was the initial way I did things. I'm closing this, I think I'll try to do it with a webview. It was probably something wrong with the devices or the rest of the code, I don't know

**Comment by rkz98** [comment]
@WeshGuillaume how did you solve this?

**Comment by nateshmbhat** [comment]
Facing the same issue, anyone found a fix ?
