### ISSUE TITLE
Slide in animations not working

### ISSUE THREAD

**Issue by ccorcos** [proyecto26/react-native-inappbrowser#24]
The following code does not slide in from the right.

```ts
				await InAppBrowser.open(url, {
					animations: {
						startEnter: "slide_in_right",
						startExit: "slide_out_left",
						endEnter: "slide_in_right",
						endExit: "slide_out_left",
					},
				})
```

**Comment by jdnichollsc** [comment]
more info please... do you have these animations into the Android resources? https://github.com/proyecto26/react-native-inappbrowser/tree/master/example/android/app/src/main/res/anim

Check the example https://github.com/proyecto26/react-native-inappbrowser/tree/master/example

**Comment by ccorcos** [comment]
Hmm. No. I'm doing this in iOS. Didn't add anything else, just tried putting those animations in....

**Comment by jdnichollsc** [comment]
The animations are only for Android

**Comment by ccorcos** [comment]
ah. I see
