### ISSUE TITLE
how can i detect when the browser window has been closed and hook into it??

### ISSUE THREAD

**Issue by digitlninja** [proyecto26/react-native-inappbrowser#240]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Both 
- Multiple
- Both

### Please, provide the following version numbers that your issue occurs with:
react-native-cli: 2.0.1
react-native: 0.63.3
react-native-inappbrowser: ^4.3.4

### Please, tell us how to recreate the issue in as much detail as possible. 
when the inAppBrowser is closed, how can I hook into that event and perform functions I want when or after it is closed.

**Comment by jdnichollsc** [comment]
We have a demo from the README, the methods return a promise to notify when the browser is closed
