### ISSUE TITLE
Load local HTML

### ISSUE THREAD

**Issue by alexpchin** [proyecto26/react-native-inappbrowser#241]
Is it possible to load local HTML using this package? I'm trying to fix displaying ApplePay - https://github.com/react-native-webview/react-native-webview/issues/920 and it's not working in `react-native-webview`.

**Comment by jdnichollsc** [comment]
Share official documentation about that (Using Native APIs) and then we can help you, why not publishing the website to an external page and redirect to the app using deep Linking? Webview don't support that, but this package works with deep Linking redirections
