### ISSUE TITLE
Universal Links are not being handled by installed app on iOS

### ISSUE THREAD

**Issue by mbr93** [proyecto26/react-native-inappbrowser#242]
### Which platform(s) does your issue occur on?
- iOS
- all versions
- all iPhones

### Please, provide the following version numbers that your issue occurs with:
RN version: 0.63.2
react-native-inappbrowser version: 3.5.1

### Please, tell us how to recreate the issue in as much detail as possible. 
If we open universal link like https://oauth.tiaa.barclays.com/  in inappbrowser we expect it to be handled by Barclays app, if installed.
It does work as expected on Android, however it's not the case on iOS.

```
if (await InAppBrowser.isAvailable()) {
        const result = await InAppBrowser.open(url, {
          // iOS Properties
          dismissButtonStyle: "cancel",
          preferredBarTintColor: "#FFFFFF",
          preferredControlTintColor: "black",
          readerMode: false,
          animated: true,
          modalPresentationStyle: "fullScreen",
          modalTransitionStyle: "coverVertical",
          modalEnabled: false,
          enableBarCollapsing: true,
          // Android Properties
          showTitle: false,
          toolbarColor: "#FFFFFF",
          secondaryToolbarColor: "black",
          enableUrlBarHiding: true,
          enableDefaultShare: true,
          forceCloseOnRedirection: false,
        });
      }
```

Are there any additional steps required to make universal links to be handled by corresponding apps on iOS?

**Comment by jdnichollsc** [comment]
Please attach a repository to be able to reproduce your issue and reopen this issue.

Cheers

**Comment by RohitRastogi94** [comment]
@mbr93 did you find any solution of this? 
For me universal link is not working if It is being redirected from server authentication but works if I tap on link from notes or some page
