### ISSUE TITLE
onNavigationStateChange

### ISSUE THREAD

**Issue by alexpchin** [proyecto26/react-native-inappbrowser#243]
**Feature Request**

I've switched to this package from `react-native-webview` in order to try to display ApplePay/Google Pay during a Stripe Checkout. 

What I would like to do is to listen to the URL change to close the browser when a successful payment has been paid. I don't believe this is implemented in this package?

- https://github.com/proyecto26/react-native-inappbrowser/issues/180

I guess some people are trying to redirect back to the app with dynamic links?

- https://github.com/proyecto26/react-native-inappbrowser/issues/237
- https://github.com/proyecto26/react-native-inappbrowser/issues/208

**Comment by jdnichollsc** [comment]
Did you try using **openAuth** method with deep Linking configured from your app? Please attach a reproducible demo to take your scenario into consideration

**Comment by jdnichollsc** [comment]
Also **onNavigationStateChange** is not supported by **ChromeCustomTabs** or **SafariViewController**, you need to redirect your users using a deep Linking with a token to be validated from your app 🙂
