### ISSUE TITLE
Can i change text of that that permission popup 

### ISSUE THREAD

**Issue by harpalCodal** [proyecto26/react-native-inappbrowser#244]
<img width="200" alt="Screenshot 2021-03-10 at 7 12 00 PM" src="https://user-images.githubusercontent.com/47382628/110638837-082b3a80-81d5-11eb-96ee-6f33d9c90d08.png">

**Comment by jdnichollsc** [comment]
You can hide that native popup using `ephemeralWebSession` option  but I'm not sure if that's possible

**Comment by jdnichollsc** [comment]
@TonyFTannous please attach your code and give us more context 👍
