### ISSUE TITLE
ability to hide url bar for seamless in app browsing

### ISSUE THREAD

**Issue by digitlninja** [proyecto26/react-native-inappbrowser#245]
### Which platform(s) does your issue occur on?
- Both 
- All
- Samsung s10+ and iphone 9

### Please, provide the following version numbers that your issue occurs with:

- CLI: 2.0.1
- Plugin(s): 3.5.1

The nature of this plugin is to provide in app browsing, without needing to leave the app, so inherently a **key** feature that would be super useful is to hide the url bar always (not just on scroll) so that it appears to the user that they are 100% in the housing app.

Please can you provide a solution or any workarounds for this, shouldn't be a big thing to implement/allow?

Many thanks
🙏🏼

**Comment by jdnichollsc** [comment]
As I said before I can't see any native option to support that with SafariViewController and ChromeCustomTabs, the idea of this plugin is to open system browser and the options are limited by the browser, WebView is the only way to support that 🙂

**Comment by digitlninja** [comment]
hmmm... any workarounds?

**Comment by jdnichollsc** [comment]
No idea, any pull request is welcome! 👍

**Comment by digitlninja** [comment]
what about a simple display: none on the bar?

**Comment by jdnichollsc** [comment]
The system's browser is a native component, we can't use css or React Native styles 🙂

**Comment by aabsharkhan1** [comment]
any one find the solution?

**Comment by aabsharkhan1** [comment]
any one found the solution?
