### ISSUE TITLE
Error occuring when setting hasBackButton to true and nothing to toolbarColor

### ISSUE THREAD

**Issue by markoj3s** [proyecto26/react-native-inappbrowser#246]
Hi,

I am getting "Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference" 
with package version 3.5.1 when trying to set hasBackButton to true without setting toolbarColor.

Seems like it is happening here: https://github.com/proyecto26/react-native-inappbrowser/blob/develop/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java#L113

**Comment by jdnichollsc** [comment]
You're right mate, it looks like back button requires to know the color of the toolbar with the current code, what do you think?

**Comment by jdnichollsc** [comment]
I think we can get the toolbar color outside of this try/catch to determine the asset to load https://github.com/proyecto26/react-native-inappbrowser/blob/develop/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java#L86

**Comment by markoj3s** [comment]
Sorry for the late reply. Didn't notice your message.
Yes indeed, if no color specified, it will lead to an error.
I think moving it below line 65 should be fine :)

**Comment by jdnichollsc** [comment]
Hello mate, please check the new version [3.6.0](https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.6.0) 👍

**Comment by markoj3s** [comment]
@jdnichollsc Thank you!!

**Comment by jdnichollsc** [comment]
You're welcome! ❤️
