### ISSUE TITLE
Disable close button in browser

### ISSUE THREAD

**Issue by snowsiechau** [proyecto26/react-native-inappbrowser#247]
Hi,
Have any way to disable close button in browser for both android and ios ???
Thank you

**Comment by jdnichollsc** [comment]
No idea, any pull request is welcome! 👍

**Comment by jdnichollsc** [comment]
I can't see any option with [Chrome Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs/overview/) or [Safari View Controller](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller)

Let me know :)
