### ISSUE TITLE
import type' declarations can only be used in TypeScript files.

### ISSUE THREAD

**Issue by ejoo** [proyecto26/react-native-inappbrowser#251]
I am using monorepo i.e react native(mobile) and react native web(web). It is working perfectly in react native. But getting error in web.

<img width="1089" alt="Screenshot 2021-04-09 at 1 15 11 PM" src="https://user-images.githubusercontent.com/8073885/114150571-a413a780-9935-11eb-9aa5-a71f5f3bdb51.png">

**Comment by jdnichollsc** [comment]
Can you attach a reproducible demo please?

**Comment by jdnichollsc** [comment]
This library don't support react native web but any pull request is welcome!

**Comment by jdnichollsc** [comment]
Import type is supported with flow too https://flow.org/en/docs/types/modules/
