### ISSUE TITLE
node_modules/react-native-inappbrowser-reborn/utils.js: function (path) {return fn.call(state, path, state); } could not be cloned.

### ISSUE THREAD

**Issue by janardhansripuram** [proyecto26/react-native-inappbrowser#252]
### Which platform(s) does your issue occur on?
- android
- iOS/Android versions 
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 
  - react-native-cli: 2.0.1
  -  react-native: 0.64.0
- Plugin(s):
    "react-native-inappbrowser-reborn": "^3.5.1",

### Please, tell us how to recreate the issue in as much detail as possible. 
I have upgraded to react-native 0.64.0 and npm install - > react-native run-android then getting this error in metro builder and in device
<img width="564" alt="Screenshot 2021-04-19 at 4 05 37 PM" src="https://user-images.githubusercontent.com/10362109/115202582-1dc34680-a129-11eb-8b1e-e7c813f75d4c.png">

**Comment by jdnichollsc** [comment]
Hello, hope you're doing well
Please attach a reproducible demo to be able to debug your issue.

Thanks for your collaboration!

**Comment by Vandanabisht17** [comment]
@janardhansripuram did you find any solution? I am getting the same error

**Comment by jdnichollsc** [comment]
@Vandanabisht17 are you using Flow or TypeScript? please allow types :)

**Comment by Vandanabisht17** [comment]
The issue is resolved now I have upgraded dependencies.
