### ISSUE TITLE
Open Facebook App

### ISSUE THREAD

**Issue by rogsmith** [proyecto26/react-native-inappbrowser#253]
I am using with Facebook auth flow, and it is working fine, but I am wondering if it is possible instead of users having to sign in to Facebook with username/pass, how to prompt to open the Facebook app to authenticate?

**Comment by jdnichollsc** [comment]
Hello, hope you're doing well
Please attach a reproducible demo to be able to debug your issue.

Did you try using Facebook SDK instead?

Thanks for your collaboration

**Comment by jdnichollsc** [comment]
It looks like you need to use deep linking with `Linking` API
