### ISSUE TITLE
Error: Invariant Violation: InAppBrowser.openAuth is in a bad state.

### ISSUE THREAD

**Issue by jacdx** [proyecto26/react-native-inappbrowser#254]
### Which platform(s) does your issue occur on?
Android, physical device and emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.12, react native .63
- Plugin(s): a lot, relevant ones: @aws-amplify/auth 3.4, react-navigation 5.x, 

### Please, tell us how to recreate the issue in as much detail as possible. 
After logging in (works great, other than cookies being non-ephemeral), then logging out (works fine), attempting to login a second time gives the error:

Error:  Invariant Violation: InAppBrowser.openAuth is in a bad state. _redirectHandler is defined when it should not be.
    at invariant (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1846:17)
    at openAuthSessionPolyfillAsync$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:358318:36)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:24919:19)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25092:24)
    at Generator.next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:24962:23)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:24919:19)
    at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:24992:22)
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25022:13
    at tryCallTwo (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:26975:7)
    at doResolve (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27139:15)

Closing, then opening the app resolves it. 

### Is there any code involved? 

My config was modeled after Amplify's example using this library. In comparing this to the example in the docs, there is no android:host used in the Android Manifest.

https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend

Login code:

```
async function urlOpener(url, redirectUrl) {

    try {
        await InAppBrowser.isAvailable();

        //@ts-ignore
        const { type, url: newUrl } = await InAppBrowser.openAuth(url, redirectUrl, {
            showTitle: false,
            enableUrlBarHiding: true,
            enableDefaultShare: false,
            ephemeralWebSession: true, //ios13 only
        });

        if (type === 'success') {
            console.log(f, 'urlOpener: success: ', newUrl);
            console.log(f, 'urlOpener: can open: ', await Linking.canOpenURL(newUrl));
            await Linking.openURL(newUrl);
        }

    } catch (e) {
        console.error('Error: ', e);
    }
}
```

Logout code:
```
async function onLogoutPress() {
    console.log(f, 'onLogoutPress');
    try {
        await Auth.signOut(); //amplify. doesn't matter if this comes after the line below
        await InAppBrowser.closeAuth(); //doesn't matter if I use close() instead or I don't call it at all
    } catch (e) {
        console.error(f, 'Failed to sign out', e);
    }
}

```

**Comment by sammartinez** [comment]
https://github.com/aws-amplify/amplify-js/issues/7468

**Comment by sammartinez** [comment]
Adding a reference to the open issue we have in Amplify JavaScript for this. Any chance that you can look into this issue? Thanks ahead of time

**Comment by jdnichollsc** [comment]
Please share your AndroidManifest config :)

**Comment by jdnichollsc** [comment]
Hello folks, please check the new version [3.6.0](https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.6.0) 👍
If this issue persist, any pull request is welcome!

**Comment by ims7inc** [comment]
issue still existed why closed this issue?

**Comment by jdnichollsc** [comment]
@ims7inc please attach a repository to be able to reproduce this issue and then I can reopen it, thanks for your help!

**Comment by ajayAloha** [comment]
This issue got resolved by setting `android:launchMode="singleTask"` in android/app/src/main/AndroidManifest.xml

**Comment by rcidt** [comment]
Thanks @ajayAloha 

Unfortunately, this is a problem for apps that need to use `android:launchMode` other than `singleTask`.

**Comment by andreydos** [comment]
> This issue got resolved by setting `android:launchMode="singleTask"` in android/app/src/main/AndroidManifest.xml

Doesn't help for me

**Comment by dgrover-spotnana** [comment]
@jdnichollsc This is happening with the latest version [3.7.0](https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.7.0) as well.

"react-native": "0.72.12"

Device: `Samsung Galaxy S20 5G (SM-G981U)` | `OS Level 33`

The below got reported on our Instabug dashboard

```
Invariant Violation - InAppBrowser.openAuth is in a bad state. _redirectHandler is defined when it should not be.
```

**Comment by stee1ix** [comment]
@jacdx Any solutions? I have universal link setup. And my auth page on web is on the same domain that I'm trying to login with in the inappbrowser
