### ISSUE TITLE
[Question] Shared Cookies

### ISSUE THREAD

**Issue by cristianoccazinsp** [proyecto26/react-native-inappbrowser#255]
"On iOS, the modal Safari will not share cookies with the system Safari." .  Is it possible to actually enable this? Looking through some deep-linking strategies to get a referrer value from the app, using `SFSafariViewController` was highlighted as an option to get cookies from the browser. Can that be done with this library?

**Comment by jdnichollsc** [comment]
What's that native option? Can you share official docs about that please?

**Comment by cristianoccazinsp** [comment]
This was the link: https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller?language=objc

However, I think it is not really possible anymore to share cookies between safari and SFSafariViewController.

**Comment by jdnichollsc** [comment]
Yeah, you're right :)

> In iOS 9 and 10, it shares cookies and other website data with Safari... If you would like to share data between your app and Safari in iOS 11 and later, so it is easier for a user to log in only one time, use ASWebAuthenticationSession instead
