### ISSUE TITLE
How to ask the user to choose browser before getting redirected?

### ISSUE THREAD

**Issue by RallyXiaoXiao** [proyecto26/react-native-inappbrowser#259]
### Problem:
As defined in the Readme, for `openAuth` method, it 

"Opens the url with Safari in a modal on iOS using SFAuthenticationSession/ASWebAuthenticationSession, and **Chrome** in a new custom tab on Android. On iOS, the user will be asked whether to allow the app to authenticate using the given url (OAuth flow with deep linking redirection)"

But in the android device, the in-app-browser is opened by the phone's default browser instead of Chrome. 

Is there a way to always ask the user to choose a browser before the redirect happens? 

### Which platform(s) does your issue occur on?
- Android
- Android versions: 10
- device - Samsung Galaxy A5 / Samsung S20

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it:
1. Set the phone's default browser to something but not Chrome
2. Open the inappbrowser, the redirect will use the default browser
3. Set the phone's default browser to Chrome
4. Open the inappbrower, the redirect will use Chrome

### Is there any code involved? 
The below code is used for the redirect.
```
try {
      if (InAppBrowser && (await InAppBrowser.isAvailable())) {
        InAppBrowser.openAuth(link, '');
      }
    } catch (error) {
      ...
    }
```

**Comment by jdnichollsc** [comment]
Hello Rally, hope you're doing well

Thank you for reaching out with this issue. Did you try using browserPackage option?

Regards,
Juan

**Comment by RallyXiaoXiao** [comment]
Hi Juan, thanks for your suggestions. But I'm not aware of the `browserPackage `. 

After some reading, it seems I can do this, like below?
```
try {
      if (InAppBrowser && (await InAppBrowser.isAvailable())) {
        InAppBrowser.openAuth(link, '' {
            browserPackage = 'com.android.chrome'
        });
      }
    } catch (error) {
      ...
    }
```
Does that mean the app will always use chrome to do the redirect?

**Comment by jdnichollsc** [comment]
Exactly, please let me know if that works for you 🙂

**Comment by RallyXiaoXiao** [comment]
I'm currently testing the `browserPackage` option, and found an unrelated question: 
why doesn't the inappbrowser work in android emulator? It opens in the physical device though...

**Comment by jdnichollsc** [comment]
Sorry, I was busy. Let me check from Android emulator and thanks for letting me know! ❤️

**Comment by RallyXiaoXiao** [comment]
Sadly, I found an issue with `browserPackage` with `openAuth` method.
When doing the below, the app will not automatically forward the auth params, instead it asks the user to login again. 
Without `browserPackage : 'com.android.chrome'`, the app will automatically forward the auth result to the redirect link and the user doesn't need to login again.  

```
try {
      if (InAppBrowser && (await InAppBrowser.isAvailable())) {
        InAppBrowser.openAuth(link, '' {
            browserPackage : 'com.android.chrome'
        });
      }
    } catch (error) {
      ...
    }
```
