### ISSUE TITLE
In app browser is not opening on Samsung A40 device.

### ISSUE THREAD

**Issue by gourav-singhal** [proyecto26/react-native-inappbrowser#267]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both  -- Android
- iOS/Android versions - Android 11
- emulator or device. What type of device? --  Device Samsung A40

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `react-native --version` to fetch it)

react-native-cli: 2.0.1
react-native: 0.62.2

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

"react-native-inappbrowser-reborn": "3.4.0",

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.
 
 InAppBrowser.openAuth(url, oAuthRedirectUrl, {options} );
 
 App tries to open the browser but fails and returns to the login screen.

**Comment by jdnichollsc** [comment]
Can you share more details please? What version of Android are you using?

**Comment by gourav-singhal** [comment]
Hi

The version on Android on device is Android 11.

**Comment by gourav-singhal** [comment]
Closing this as the issue was due to Antivirus
