### ISSUE TITLE
isAvailable() returns "false" for Android 11

### ISSUE THREAD

**Issue by sergiulucaci** [proyecto26/react-native-inappbrowser#270]
Hello guys,

thanks for this awesome library, we're using it for a while. 

I found a new issue where, for Android version 11 (API level 30), `isAvailable()` returns false, even though Chrome is installed. I really think it's an issue with this method only, because `open()` method works.

Eg: 

```
import InAppBrowser from 'react-native-inappbrowser-reborn';

await InAppBrowser.isAvailable(); // this is false

await InAppBrowser.open(url, { ...options }) // this works fine
```

Are you guys aware of it? Would be great to have it fixed.

Thanks!

**Comment by jdnichollsc** [comment]
It was reported before from another repo, let me check ASAP, thanks!

**Comment by sergiulucaci** [comment]
@jdnichollsc can you guide me on the repo where it was reported? I can make some investigations there if you don't have time. Thanks!

**Comment by jdnichollsc** [comment]
@sergiulucaci thanks for your help mate, this is the other repo https://github.com/proyecto26/nativescript-inappbrowser/issues/53

**Comment by ruairioliverwv** [comment]
As recommended in that linked thread, I just needed to add this to my AndroidManfiest.xml within the manifest tag.
```

<manifest ...
...
<queries>
      <intent>
            <action android:name=
                  "android.support.customtabs.action.CustomTabsService" />
      </intent>
  </queries>
</manifest>
```

**Comment by jdnichollsc** [comment]
Hello folks, please check the new version [3.6.0](https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.6.0) 👍
