### ISSUE TITLE
Can not change URL text color in iOs

### ISSUE THREAD

**Issue by takeerdevs** [proyecto26/react-native-inappbrowser#271]
I am currently developing in iOs, i haven't tested in Android yet, but i've set in app browser to open with options
```
  await InAppBrowser.open(url, {
    // iOS Properties
    dismissButtonStyle: 'cancel',
    preferredBarTintColor: '#e9821b',
    preferredControlTintColor: 'white', //fails to set URL text color even if i replace 'white' with hex '#FFFFFF'
    readerMode: false,
    animated: true,
    modalPresentationStyle: 'fullScreen',
    modalTransitionStyle: 'coverVertical',
    modalEnabled: true,
    enableBarCollapsing: false,
    // Android Properties
    showTitle: true,
    toolbarColor: '#e9821b',
    secondaryToolbarColor: 'white',
    enableUrlBarHiding: true,
    enableDefaultShare: true,
    forceCloseOnRedirection: false,
    // Specify full animation resource identifier(package:anim/name)
    // or only resource name(in case of animation bundled with app).
    animations: {
      startEnter: 'slide_in_right',
      startExit: 'slide_out_left',
      endEnter: 'slide_in_left',
      endExit: 'slide_out_right'
    }
  })
```
but URL texts are in black color.. 
![Screenshot 2021-06-08 at 12 54 58](https://user-images.githubusercontent.com/49426357/121165218-c607a880-c858-11eb-9432-6adf0c709ae9.png)
any comments on this..?
Thanks :)

**Comment by jdnichollsc** [comment]
Are you trying with `toolbarColor` android option?

**Comment by takeerdevs** [comment]
@jdnichollsc are you able to set circled texts in the screenshot above to white color? if yes, which prop are you using.. thanks :)

**Comment by jdnichollsc** [comment]
I'm not working with RN right now, please let me know the iOS native option you're trying to use 👍

**Comment by jdnichollsc** [comment]
Example project is working as expected :) 
![image](https://user-images.githubusercontent.com/2154886/123493978-e4ed9500-d5e3-11eb-9da2-dcd46e90443b.png)

**Comment by takeerdevs** [comment]
Example project works as expected if you don't change `preferredBarTintColor: '#453AA4',` but if you change to other color url text color changes to black

**Comment by takeerdevs** [comment]
@jdnichollsc try to change `preferredBarTintColor` to a color other than `'#453AA4'` you'll see what i mean.. thanks :)

**Comment by takeerdevs** [comment]
Options i use are in the issue description https://github.com/proyecto26/react-native-inappbrowser/issues/271#issue-914718930

**Comment by jdnichollsc** [comment]
Any pull request is welcome! 👍
