### ISSUE TITLE
App crashes on RN 0.60 with latest version.

### ISSUE THREAD

**Issue by thuongtv-vn** [proyecto26/react-native-inappbrowser#284]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Android
- Android versions 
- emulator or device.

### Please, provide the following version numbers that your issue occurs with:

"react-native": "0.60.5",
"react-native-inappbrowser-reborn": "3.6.2",

### Please, tell us how to recreate the issue in as much detail as possible. 

Open a URL by using:

``` 
InAppBrowser.open(url, {
      // iOS properties
      modalPresentationStyle: 'fullScreen'
});
```

The issue occurs:

**unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.NoSuchKeyException: toolbarColor**

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by jdnichollsc** [comment]
Thanks for reporting this issue! 👍
