### ISSUE TITLE
How to use OIDC/OAuth/PKCE with this tool on iOS

### ISSUE THREAD

**Issue by ToTheSol** [proyecto26/react-native-inappbrowser#288]
Hey all, so I'm trying to use the in-app browser package here to hit an Authentication server using the code specified in the demo, but the thing that I'm confused about (or just need more info) is where do I put the information that I need to send with the request for OpenID Connect/OAuth/PKCE combo (ie. client_id and other things)? I see that there is an option slot for headers on the InAppAndroidOptions type, but not the InAppBrowseriOSOptions type.

I'm wondering if I'm looking in the right spot for these options, or do I need to add something on top of this tool to allow for these comment Authentication flows that I might not be aware of?

I looked through the current issues and made sure that this isn't a repeat.

![Screen Shot 2021-07-14 at 3 34 56 PM](https://user-images.githubusercontent.com/29029348/125696110-2e79aac5-9624-46ae-a36b-0221f2ce426b.png)

**Comment by jdnichollsc** [comment]
> where do I put the information that I need to send with the request for OpenID Connect/OAuth/PKCE combo (ie. client_id and other things)?

Did you try sending these params from the url?

Check other iOS options here and let me know: https://developer.apple.com/documentation/authenticationservices

Other good option for `PKCE` flow is this one: https://www.npmjs.com/package/@okta/okta-react-native

Regards

**Comment by jdnichollsc** [comment]
I added Okta to support PKCE in a project following this sample https://github.com/okta/samples-js-react-native

I hope this can help you! <3

**Comment by ToTheSol** [comment]
> Did you try sending these params from the url?
No I haven't, but I can definitely give that a try.

> Check other iOS options here and let me know: https://developer.apple.com/documentation/authenticationservices
Thanks for the suggestion here, but I do need a more general react native approach which I think the Okta one you mentioned below will take care of.

> Other good option for `PKCE` flow is this one: https://www.npmjs.com/package/@okta/okta-react-native
Yeah, I was looking into using this before, so I'll definitely have to revisit this and implement it.

**Comment by ToTheSol** [comment]
> I added Okta to support PKCE in a project following this sample https://github.com/okta/samples-js-react-native
> 
> I hope this can help you! <3

Thank you so much for the help and suggestions, I really appreciate it :D <3

**Comment by jdnichollsc** [comment]
You're welcome!
