### ISSUE TITLE
Not able to add event listener on url change

### ISSUE THREAD

**Issue by siddheshwarghumare** [proyecto26/react-native-inappbrowser#29]
I am not able add event listerner on url change.
I want to close inappbrowser on specific url like success or failure url.

I am new in React Native so can you please give steps to get url value on url changes.

Please let me know if any required from my side.

Thank you!!!

**Comment by jdnichollsc** [comment]
Any pull request is welcome! 👍

**Comment by jdnichollsc** [comment]
Try using `Linking.addEventListener('url', ...)` and please let me know

**Comment by imbudhiraja** [comment]
Hey @jdnichollsc have you tested this. As i'm not able to get the changed url ?

**Comment by jdnichollsc** [comment]
ohh sorry, I think we need native code to detect that

**Comment by jdnichollsc** [comment]
Sorry guys, this is not possible by security concerns https://stackoverflow.com/questions/47259647/closes-sfsafariviewcontroller-on-a-certain-url?rq=1
