### ISSUE TITLE
Does including headers inside the 'open' URL function work in iOS?

### ISSUE THREAD

**Issue by dan-iliescu** [proyecto26/react-native-inappbrowser#293]
I have been trying to include 'headers' like in the documentation on a iOS react-native app, but they don't go through. It's just the GET request to the URL that works, but the headers are simply missing from the actual request being made. Are there plans to make it work or is there something that I'm missing?

**Comment by jdnichollsc** [comment]
Hello mate, thanks for reporting this issue

Please check the **README** of this project, `headers` option is only supported from **Android**:
![image](https://user-images.githubusercontent.com/2154886/129373694-0030c57f-111c-47ab-a4d1-ebdb1ef7e5d6.png)

Anyway, any pull request is welcome!

Best,
Juan
