### ISSUE TITLE
unwanted popUp

### ISSUE THREAD

**Issue by saurabhkanswal** [proyecto26/react-native-inappbrowser#295]
![WhatsApp Image 2021-08-23 at 1 28 47 PM](https://user-images.githubusercontent.com/26677033/130411746-7e1b5f06-425b-4df9-8890-8ce28fdc1827.jpeg)

=>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

import {Linking, Alert} from 'react-native';
import {InAppBrowser} from 'react-native-inappbrowser-reborn';

export const openLink = async ({url}) => {
  try {
    // const url = 'https://www.proyecto26.com'
    if (await InAppBrowser.isAvailable()) {
      const result = await InAppBrowser.open(url, {
        // Android Properties
        showTitle: true,
        toolbarColor: '#F7A828',
        secondaryToolbarColor: 'black',
        navigationBarColor: 'black',
        navigationBarDividerColor: 'white',
        enableUrlBarHiding: true,
        enableDefaultShare: true,
        forceCloseOnRedirection: false,

      });
      Alert.alert(JSON.stringify(result));
    } else Linking.openURL(url);
  } catch (error) {
    console.log(error.message);
  }
};

<============================================================

the pop shows when I redirect back to my app by clicking on the close button.
Any idea what Iam doing wrong.

**Comment by jdnichollsc** [comment]
Try removing the alert from your code 😅

**Comment by saurabhkanswal** [comment]
> Try removing the alert from your code 😅

thanks, man
sometimes I do a silly mistake

**Comment by jdnichollsc** [comment]
No problem, me too 😂
