### ISSUE TITLE
RN v0.65: Warnings pertaining deprecated usage of event listeners

### ISSUE THREAD

**Issue by TheWirv** [proyecto26/react-native-inappbrowser#296]
### Which platform(s) does your issue occur on?
- iOS/Android/Both: Both
- iOS/Android versions: all
- emulator or device. What type of device? Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.0
- Plugin(s): 
-- RN: 0.65.1
-- InAppBrowser: 3.6.3

### Please, tell us how to recreate the issue in as much detail as possible. 
With the advent of RN v0.65, they changed the way you set up event listeners and throw warnings that "calling `removeListener()` has been deprecated" (as per this commit https://github.com/facebook/react-native/commit/035718ba97bb44c68f2a4ccdd95e537e3d28690c#diff-53ad587a2f77ca63b6940dbf0026a101e3874de1858e058d217a8f4c04d4987e). See the following screenshot:

![inappbrowser-screenshot copy](https://user-images.githubusercontent.com/4397989/130459658-99c99cf7-10f2-4609-8252-0238ca71a2f7.jpg)

I would've just done and submitted a PR, but the CONTRIBUTING guidelines told me to "first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change." 😅

**Comment by jdnichollsc** [comment]
sounds good! <3

**Comment by markl-vesper** [comment]
Would this issue perhaps affect something like Social Sign via AWS Amplify?

Been struggling for a few days now to get Google auth working

Cognito Pool works fine via Hosted UI and returns correct response
Running from app using this browser the UI opens and the user is authenticated and the browser never closes. Its as if the app never gets the url via event

If I run adb cmd below to simulate the redirect coming back then the app closes the browser and carries on the auth process which now makes me think the browser may not be detecting and/or passing on the event??

`adb shell am start -W -a android.intent.action.VIEW -d "cortexmonitoringapp://signin" com.cortexmonitoring/.MainActivity`

**Comment by retyui** [comment]
Also faced with this issue, it so annoying to see this warnings every time(
