### ISSUE TITLE
node_modules\react-native-inappbrowser-reborn\utils.js: function (path) {           return fn.call(state, path, state);         } could not be cloned. Error: function (path) {           return fn.call(state, path, state);         } could not be cloned.

### ISSUE THREAD

**Issue by Vandanabisht17** [proyecto26/react-native-inappbrowser#300]
getting error : node_modules\react-native-inappbrowser-reborn\utils.js: function (path) {
          return fn.call(state, path, state);
        } could not be cloned.
Error: function (path) {
          return fn.call(state, path, state);
        } could not be cloned.

**Comment by jdnichollsc** [comment]
Please attach a repository to be able to reproduce your issue 👍

**Comment by Vandanabisht17** [comment]
The issue is resolved now I have upgraded dependencies.

**Comment by jdnichollsc** [comment]
Thanks for letting me know!

**Comment by riccardocaranfil** [comment]
Got this issue with the `3.6.3` version

**Comment by azozaya** [comment]
@Vandanabisht17 got this issue as well, which dependencies did you upgrade?
