### ISSUE TITLE
Incompatible sdk version with androidx.browser v 1.4.0-alpha

### ISSUE THREAD

**Issue by Swackles** [proyecto26/react-native-inappbrowser#302]
### Which platform(s) does your issue occur on?

- Android
- When compiled sdk version is below 31

### Please, tell us how to recreate the issue in as much detail as possible.

This error occurs when your compiled sdk verson is below 31. September 15, 2021 androidx.browser v1.4.0-alpha01 got released. Since this package always uses the latest 1 version, this breaks our build.

Current fix I found doing fallowing change in `build.gradle` line 61.

```gradle
def defaultAndroidXVersion = "1+"` -> def defaultAndroidXVersion = "1.3+"`
```

**Comment by jdnichollsc** [comment]
Hello mate, thanks for reporting this issue

Please check the configuration for AndroidX libs from [README](https://github.com/proyecto26/react-native-inappbrowser#mostly-automatic-installation)

Best,
Juan
