### ISSUE TITLE
Why the need for `QUERY_ALL_PACKAGES` permission?

### ISSUE THREAD

**Issue by petlys** [proyecto26/react-native-inappbrowser#311]
Could you elaborate on the need for the `QUERY_ALL_PACKAGES` permission?
This is quite a scary permission for many users, and a dealbreaker for us.

**Comment by jdnichollsc** [comment]
Hey @petlys, what Android options are you using? 👍

**Comment by petlys** [comment]
> Hey @petlys, what Android options are you using? 👍

None. Just `InAppBrowser.open(url)`

But it doesn't matter does it? The problem is that the [project itself requires it](https://github.com/proyecto26/react-native-inappbrowser/blob/cf91b3c536ece0ba25997bb2294be9c6cb9e3d35/android/src/main/AndroidManifest.xml#L6) in order to query which system browser to use [here](https://github.com/proyecto26/react-native-inappbrowser/blob/cf91b3c536ece0ba25997bb2294be9c6cb9e3d35/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java#L293)

**Comment by jdnichollsc** [comment]
Sure, you're right! We're now using that to detect if that browser is available <3

**Comment by androideveloper** [comment]
Hi @jdnichollsc .
As this is considered a dangerous permission, apps that are using it need to explain the reason to Google Play. 
If I look the [invalid use cases](https://support.google.com/googleplay/android-developer/answer/10158779?hl=en#zippy=%2Cpermitted-uses-of-the-query-all-packages-permission%2Cinvalid-uses) for it, there is one point mentioning: **When the required task can be done with a less broad app-visibility method.**
I was wondering do we actually need this broad permission to check for available browsers that support custom tabs?

Per google documentation, for android 11 it's only required to provide the manifest `queries` section and from my previous experience with custom tabs, this was enough
https://developer.chrome.com/docs/android/custom-tabs/integration-guide/#how-can-i-check-whether-the-android-device-has-a-browser-that-supports-custom-tab

**Comment by androideveloper** [comment]
Hey @jdnichollsc 
I did more investigation on this and the permission is not needed, as we already have 
```
<intent>
  <action android:name="android.support.customtabs.action.CustomTabsService" />
</intent>
```
What you refer to is covered here https://developer.android.com/training/package-visibility/use-cases#open-urls-custom-tabs, so no need to change the approach. I tested it by removing the permission from our app manifest and testing with different browsers that have custom tabs.

I prepared a PR to remove it https://github.com/proyecto26/react-native-inappbrowser/pull/335 🙏

**Comment by jdnichollsc** [comment]
> Hey @jdnichollsc I did more investigation on this and the permission is not needed, as we already have
> 
> ```
> <intent>
>   <action android:name="android.support.customtabs.action.CustomTabsService" />
> </intent>
> ```
> 
> What you refer to is covered here https://developer.android.com/training/package-visibility/use-cases#open-urls-custom-tabs, so no need to change the approach. I tested it by removing the permission from our app manifest and testing with different browsers that have custom tabs.
> 
> I prepared a PR to remove it #335 🙏

But are you testing with different browsers? what values are you testing with the `browserPackage` option from Android?

And why not use the recommendation from the official documentation to check if a browser is available?
```
<!-- Place inside the <queries> element. -->
<intent>
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="https" />
</intent>
```

**Comment by androideveloper** [comment]
> But are you testing with different browsers? what values are you testing with the browserPackage option from Android?

I tested with different browsers (Chrome, Edge, Phoenix). I was checking `isAvailable` function without custom `browserPackage` option. But in this case you're also only interested in browsers that support custom tabs, right?

> And why not use the recommendation from the official documentation to check if a browser is available?

The one that you're referring to is for checking if there are browsers available in general, but in this case and per your previous message we are interested only in browsers **that support custom tabs**. If we look at the section [here](https://developer.android.com/training/package-visibility/use-cases#open-urls-custom-tabs) 


> you might want to [check whether the device has a browser that supports Custom Tabs](https://developers.google.com/web/android/custom-tabs/implementation-guide#opening_a_custom_tab), or select a specific browser to launch with Custom Tabs using [CustomTabsClient.getPackageName()](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsClient#getPackageName(android.content.Context,%2520java.util.List%3Cjava.lang.String%3E)). In those cases, include the following <intent> element as part of the <queries> element in your manifest:

```
 <intent>
   <action android:name="android.support.customtabs.action.CustomTabsService" />
 </intent>
```

**Comment by jdnichollsc** [comment]
Oh sounds great, thanks for letting me know! <3

**Comment by rosskhanas** [comment]
@jdnichollsc any chance to have this published to NPM? 🥺

**Comment by elliotdickison** [comment]
@androideveloper Thanks for the fix!!

**Comment by nichol-pennell** [comment]
Hey @jdnichollsc! Will this get published in a new package update? I am using this in my app and can't publish without this getting removed.

**Comment by imekinox** [comment]
@nichol-pennell you can try this in th meantime: 

Add this to your Android Manifest: 

`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"
        tools:node="remove" tools:ignore="QueryAllPackagesPermission" />`
        

>    tools:node="remove"
> Remove this element from the merged manifest. Although it seems like you should instead just delete this element, using this is necessary when you discover an element in your merged manifest that you don't need, and it was provided by a lower-priority manifest file that's out of your control (such as an imported library).

**Comment by Rehubbard** [comment]
@jdnichollsc @androideveloper thanks for the quick resolution. Any chance this can be released ASAP? 

The Google Play policy on QUERY_ALL_PACKAGES takes affect today. It blocks all app updates from being published. It's a major concern, especially when this library is the only thing that uses that permission.

**Comment by jdnichollsc** [comment]
Hello folks, sorry for the delay
I just come back from vacations, let me publish a new version ASAP
Thanks for your patience ❤️

**Comment by elliotdickison** [comment]
For anyone who just can't wait, you can unset this permission in your app's AndroidManifest.xml file like so:

```
<manifest
  xmlns:android="http://schemas.android.com/apk/res/android"
  package="<package name>"
  xmlns:tools="http://schemas.android.com/tools"
>
  <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" tools:node="remove" />
```

(make sure to add the `xmlns:tools` attribute to the `manifest` tag)

**Comment by kuorus** [comment]
Thank you for the quick reaction. We are here for help and emotional support 🤣

**Comment by nichol-pennell** [comment]
@imekinox this worked! Thanks for the quick solution :) 

> @nichol-pennell you can try this in th meantime:
> 
> Add this to your Android Manifest:
> 
> `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" tools:node="remove" tools:ignore="QueryAllPackagesPermission" />`
>

**Comment by androideveloper** [comment]
@nichol-pennell This change will just remove the permission, same as the temp fix does.
When I removed it, I tested with different browsers. See my comment https://github.com/proyecto26/react-native-inappbrowser/issues/311#issuecomment-1071030450
What exactly doesn't work? It could be because of some other reason.

**Comment by nichol-pennell** [comment]
@androideveloper Instead of the inappbrowser opening in our app, it opens the link in a browser outside of our app now. And the only thing I changed was adding in the permission removal in the manifest
> @nichol-pennell This change will just remove the permission, same as the temp fix does. When I removed it, I tested with different browsers. See my comment [#311 (comment)](https://github.com/proyecto26/react-native-inappbrowser/issues/311#issuecomment-1071030450) What exactly doesn't work? It could be because of some other reason.

**Comment by androideveloper** [comment]
which browsers do you have installed? Does any of those support chrome custom tabs?

**Comment by nichol-pennell** [comment]
@androideveloper I have chrome installed

**Comment by androideveloper** [comment]
Could you try another browser? It might also be that you have some custom logic that needs QUERY_ALL_PACKAGES permission.

**Comment by felipemengatto** [comment]
Hey @jdnichollsc! Will this get published in a new package update?

**Comment by nichol-pennell** [comment]
> Could you try another browser? It might also be that you have some custom logic that needs QUERY_ALL_PACKAGES permission.

@androideveloper we have no custom logic using this permission, the only thing using it was this package. Everything was working fine before I added in the permission removal, and the only thing in our app not working properly is the in-app-browser.  So @jdnichollsc can this update please get updated with this change soon?

**Comment by amq** [comment]
My workaround:

1. install `patch-package`
2. create a file in `patches/`:

```
diff --git a/node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml b/node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml
index 6aaceca..d0590b1 100644
--- a/node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml
+++ b/node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml
@@ -3,7 +3,6 @@
           package="com.proyecto26.inappbrowser">
 
     <uses-permission android:name="android.permission.INTERNET" />
-    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
 
     <application>
         <activity
```

**Comment by petlys** [comment]
Been a while since I created this issue, but to follow up on it - I ended up just using [react-native-webview](https://github.com/react-native-webview/react-native-webview) inside a [Modal](https://reactnative.dev/docs/modal)

**Comment by elliotdickison** [comment]
We removed the permission with [Android's manifest merging tools](https://github.com/proyecto26/react-native-inappbrowser/issues/311#issuecomment-1089353928) and have seen no adverse effects in production.

**Comment by kuorus** [comment]
> Been a while since I created this issue, but to follow up on it - I ended up just using [react-native-webview](https://github.com/react-native-webview/react-native-webview) inside a [Modal](https://reactnative.dev/docs/modal). Super simple and much more flexible.

Depending on the use case, this won't work. e.g. Facebook 3rd-party login won't allow a webview for security reasons.

**Comment by markl-vesper** [comment]
> <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" tools:node="remove" tools:ignore="QueryAllPackagesPermission" />

This workaround seemed to work fine but we also had to add below

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    **xmlns:tools="http://schemas.android.com/tools"**
  package="com.cortexmonitoring">

at top of file to prevent build failing

**Comment by harveyconnor** [comment]
When will the npm package be updated?

**Comment by mahamaad** [comment]
hey @jdnichollsc thank you for your package i appreciate, but we need an update before July 12,

thank you.

**Comment by informsharique** [comment]
Hey @jdnichollsc Thank you for this awesome library!!
We also need to push an update to play store after new release. Can you please make a release with the fix so that we may not be delayed. App update should have to be approved before July 12

**Comment by jdnichollsc** [comment]
Hello folks, excuse me for the delay
My Mac stopped working, I'm planning to release a new version as soon as possible, sorry for the inconvenience 🙏 

Regards,
Juan

**Comment by KarimMassadCubic** [comment]
any ideas when the release will happen? We would also need the update in order to release apps which are currently in production / in the stores.

**Comment by ArturoTorresMartinez** [comment]
Any update?

**Comment by compwron** [comment]
https://xkcd.com/2347/

**Comment by MoOx** [comment]
See https://github.com/proyecto26/react-native-inappbrowser/pull/335 for followup

**Comment by ana-nd-s** [comment]
Hey @jdnichollsc, is there any update on this?

**Comment by markl-vesper** [comment]
The workaround that @imekinox has proposed works perfectly. No need to wait for a new release. Google Store has accepted our updated APK using the workaround to build it

**Comment by nichol-pennell** [comment]
I don't know if anyone is still dealing with this. But I wanted to add that the fix below worked for me. The issue I had was that we had other versions in testing that were also being flagged for this permission. I just had to add the newest version with this fix to all our testing versions and then I got rid of the flag in the console.
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" tools:node="remove" tools:ignore="QueryAllPackagesPermission" />`

**Comment by RayHughes** [comment]
> The workaround with adding the line to AndroidManifest.xml does not work for me. I still get the same error in my fastlane pipeline.
> 
> `android/app/src/main/AndroidManifest.xml`
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="...">
> 
>   <uses-permission android:name="android.permission.INTERNET" />
>   <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" tools:node="remove" tools:ignore="QueryAllPackagesPermission" />
> ...
> ```
> 
> Getting the error `Google Api Error: Invalid request - This release includes the QUERY_ALL_PACKAGES permission, which hasn't been declared in Play Console.`
> 
> Please release a version to npm with the fix from #335

Having the same issue with Bitrise using both the patch method and the lines added to the manifest to remove. 

I think it's time to declare this package abandoned and move on.

**Comment by zholmes1** [comment]
Better to just learn how to use the `patch-package` than copying the patches from here. It's very easy.

1. Navigate to `node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml`
2. Remove the Query All Packages permission
3. Do `npx patch-package`. This will auto generate the patch file for you.
4. Add `"postinstall": "npx patch-package"` to your `scripts`. This will run your patches every time you install.

It's a very useful tool for situations like this where a repo maintainer is unable to make a required change on time.

**Comment by sinn1** [comment]
> > The workaround with adding the line to AndroidManifest.xml does not work for me. I still get the same error in my fastlane pipeline.
> > `android/app/src/main/AndroidManifest.xml`
> > ```
> > <manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="...">
> > 
> >   <uses-permission android:name="android.permission.INTERNET" />
> >   <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" tools:node="remove" tools:ignore="QueryAllPackagesPermission" />
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Getting the error `Google Api Error: Invalid request - This release includes the QUERY_ALL_PACKAGES permission, which hasn't been declared in Play Console.`
> > Please release a version to npm with the fix from #335
> 
> Having the same issue with Bitrise using both the patch method and the lines added to the manifest to remove.

I had the same problem. 

You may be experiencing the same issue with solution here: https://github.com/proyecto26/react-native-inappbrowser/issues/363#issuecomment-1192074701

**Comment by zholmes1** [comment]
@mohamed2m2018 As far as I know there is no commit or pull request that fixes this. You need to do it yourself with either patch-package to fix the manifest file for this package, or edit your own manifest to override and remove all attempts to add the permission. Both solutions should work fine. After a build you can drag the APK/aab onto Android Studio to inspect the package and make sure the permission is actually gone from the final manifest

**Comment by mohamed2m2018** [comment]
@zholmes1 yes maybe I will do this, but it's natural to have a new release with this since I see this pr: [https://github.com/proyecto26/react-native-inappbrowser/pull/335](url) and it's merged since Mar 17

**Comment by rileycognitv** [comment]
An update on the dependency package would be great! struggling to release onto google play store

**Comment by felipejoribeiro** [comment]
> @mohamed2m2018 As far as I know there is no commit or pull request that fixes this. You need to do it yourself with either patch-package to fix the manifest file for this package, or edit your own manifest to override and remove all attempts to add the permission. Both solutions should work fine. After a build you can drag the APK/aab onto Android Studio to inspect the package and make sure the permission is actually gone from the final manifest

Even after confirming this. Google play still insistis that it is there. I'm not sure what to do next.

**Comment by jbuffin** [comment]
@felipejoribeiro Make sure you update the app in all your testing channels. Play will continue to complain about the issue as long as any version is available. For me, I had an old version in my internal testing channel and was still getting emails from Google about it even though my production version did not have the issue. You can verify if the permission is gone in the Releases tab under the App Bundle details.

**Comment by felipejoribeiro** [comment]
@jbuffin Thank you for the prompt response. I have versions in the production and internal testing. Both already comply to the new security policy. But both were rejected. When i click in 'release details' in one of then and i check the bundles, the ones in 'New app bundles' don't have the permission. The only ones that have are the ones in 'Deactivated app bundles'.
Don't know how to deal with then as i can't launch new versions.

**Comment by jbuffin** [comment]
You might have to appeal the rejection to get more clarity on why they think you have the permission.

**Comment by jdnichollsc** [comment]
Hey folks, please help me reviewing this PR for the new release v3.7.0 https://github.com/proyecto26/react-native-inappbrowser/pull/375

**Comment by zholmes1** [comment]
@felipejoribeiro I am in the exact same situation as you. Cannot submit an update because I can't be approved for this permission, but can't remove the permission from my app policy because I can't submit an update. Truly sadistic torture from the masterminds over at Google Play Policy Team. Please email me so we can keep in touch and let each other know if we ever find a solution.

**Comment by jdnichollsc** [comment]
Sorry for the delay folks 😥

**Comment by bumpingChris** [comment]
@zholmes1 @felipejoribeiro I have the same situation. Google Play rejects updates because this QUERY-ALL-PACKAGES permission request from react-native-inappbrowser apparently exists in OLD bundles that are considered active. THERE'S NO WAY TO DEACTIVATE THE OLD BUNDLES! 

I have communicated to Google via appealing, contact-us, and chat, and the feedback I get from them is so obscure and without doable directions (e.g. they said to deactivate the old bundles but there is no way to do so!). @zholmes1 They also said to fill in the Declaration Form for the sensitive permissions - THIS MUST BE DONE EVENTHO YOU DON'T NEED THE PERMISSION OTHERWISE YOU CAN'T SUBMIT A NEW RELEASE. While we can submit a new release, we keep getting rejected even the new releases do not have the permission request because the old bundles do! I'm at a loss!

If you figure out the way to overcome this issue please let me know.

**Comment by zholmes1** [comment]
@bumpingChris @felipemengatto I was able to get my app approved. The key was to create a brand new build for each release track, and put them all in review at the same time. That way the reviewer doesn't even hear about the QUERY_ALL_PACKAGES permission.

Read more here:
https://bapspatil.medium.com/dear-googles-permissions-declaration-form-can-we-break-up-85bc6b62f690

**Comment by dooleyb1** [comment]
Having the same issue as @bumpingChris , when I submit a new build to `Internal testing` track in order to submit for a review (and eventually promote to `Production` track). Google are blocking this saying the following:

`This release includes permissions that haven't been declared in Play Console. Go to sensitive app permissions to update your Permissions declaration.`

When I go to the `Permissions declarations` section to view the bundles containing the `QUERY_ALL_PACKAGES` permisssion which is causing the issue the only one displayed is my current bundle that is active in `Production`.

**Comment by zholmes1** [comment]
@dooleyb1 Have a look at my comment from earlier this morning. I was stuck like you and I was able to solve it.

**Comment by dooleyb1** [comment]
> @dooleyb1 Have a look at my comment from earlier this morning. I was stuck like you and I was able to solve it.

Yeah I tried the above and am struggling to move my current production build from `Active` to `Inactive`. My production build is code 141. This build is also in Internal test track (was promoted from here). I've uploaded a new build to Internal test track with code 142 as a draft release & similarly a new build to Production track with code 143. I cannot submit either of these draft releases as I'm getting the `This release includes permissions that haven't been declared in Play Console. Go to sensitive app permissions to update your Permissions declaration.` error which is pointing to build code 141 (internal test & production) telling me it has the `QUERY_ALL_PACKAGES` permission. 

@zholmes1 how did you manage to get around this? I tried following the above link to no avail.

**Comment by zholmes1** [comment]
Make sure you're doing every single track. And at 100% rollout. You need to have zero trace.

To confirm this, go to your policy declaration and click "affected bundles/apk's" and you'll see which tracks/versions are still requesting this declaration. You want it to say "no affected bundles" before you release. If there's anything listed at all there, your review will get rejected.

**Comment by dooleyb1** [comment]
<img width="1415" alt="Screenshot 2022-08-03 at 12 37 41" src="https://user-images.githubusercontent.com/23729427/182598951-5997f452-4a2f-4293-b6c3-6702af3b5f81.png">

Basically the problem is that I cannot deactivate the above builds by submitting new builds to these tracks as when I go to publish build 143 to internal test for example it gives the error below even though 141 is the only bundle affected by this issue and is not included in 143 whatsoever.

<img width="1102" alt="Screenshot 2022-08-03 at 12 40 53" src="https://user-images.githubusercontent.com/23729427/182599379-65e11622-f9b9-4a05-9764-a8486a7e7246.png">

**Comment by zholmes1** [comment]
@dooleyb1 They have to all be in review at the same time. I started with internal, then alpha, then beta, then production. Brand new build for each one

**Comment by dooleyb1** [comment]
> @dooleyb1 They have to all be in review at the same time. I started with internal, then alpha, then beta, then production. Brand new build for each one

It's not letting me even submit them to review is the issue

**Comment by rileycognitv** [comment]
I had a problem where I was stuck unable to update my android app. I also had to make sure every active track (an internal and 2 closed tracks) had the same latest build with the fix in review. Only then was it accepted. Was a lot of pain before finding out about this info

**Comment by dooleyb1** [comment]
I can't get any of the above solutions to work unfortunately (possibly due to error on my part). I've reached out to Google Play Developer Support and this is there reply below for anyone else who may be stuck. Looks like I'm going to have to fill out the declaration form.

```
Thanks for contacting Google Play Developer Support.

You’re getting the warning about QUERY_ALL_PACKAGES due to your existing/old versions having used this permission.

You will have to declare the permission QUERY_ALL_PACKAGES first in order to update to a newer version. Once you've successfully updated the app without the QUERY_ALL_PACKAGES permission, it will naturally be removed in your app bundle explorer.

Please note that removing the permission without declaring it first is not possible at the moment.

You can learn more about the form and the review process by visiting the [Declare permissions for your app](https://support.google.com/googleplay/android-developer/answer/9214102) article on the Help Center.
```

**Comment by zholmes1** [comment]
@dooleyb1 

Yes that's correct, you do have to fill the form out. But as long as you have a bundle in review for every single possible track that does not include the permission, they will not look at the declaration form.

**Comment by dooleyb1** [comment]
> @dooleyb1
> 
> Yes that's correct, you do have to fill the form out. But as long as you have a bundle in review for every single possible track that does not include the permission, they will not look at the declaration form.

Awesome, thanks 🙏

**Comment by bumpingChris** [comment]
@zholmes1 @dooleyb1 Thanks Zholmes1 for your input. We were able to finally get our update approved after waiting 4 days in review. We did what you recommended updating the build in every track.

**Comment by felipejoribeiro** [comment]
Was able to get it approved updating both tracks. Thanks @zholmes1 and @dooleyb1!

**Comment by moob123** [comment]
I did not get so lucky, I posted my app's new release on all tracks and all got denied. It is like Catch-22. They have answered to my appeal with some mail templates so far. Is there any specific line of reasoning that gets through? Thanks.

**Comment by zholmes1** [comment]
@moob123 

You're not gonna get through to them. I tried for days emailing/calling all different departments. No one wanted to listen and no one could do anything.

Are you bumping the version number for each package.

For instance: Internal testing gets version code 53, Closed testing 54, Open testing 55, Production 56.

This is what ultimately allowed mine to pass. 

I think the key is to go to your policy declaration and see which builds are affected by the sensitive permissions declaration. If there are any builds listed there, all your updates will be rejected.

**Comment by MoOx** [comment]
FYI, the only thing I had to do was to fill the form. I said in it "Our app isn't using the QUERY_ALL_PACKAGES permission. Incoming update is going to remove it".
I validated and was immediately able to push a version to internal testing.

**Comment by pfrazee** [comment]
Sorry for adding noise -- just wanted to do a quick shout-out thanks to the maintainers and everyone contributing to this issue. This is one of those thankless PITAs and everybody sharing their solutions and helping with the fixes are an immense help to (me and) the community.

**Comment by jdnichollsc** [comment]
Totally agree, gracias totales for all your support folks! ❤️

**Comment by flogy** [comment]
> FYI, the only thing I had to do was to fill the form. I said in it "Our app isn't using the QUERY_ALL_PACKAGES permission. Incoming update is going to remove it". I validated and was immediately able to push a version to internal testing.

Worked for me too with the exact same phrasing. Had to draft a new release for all the used channels too (internal testing & production in my case) to get it working. Took 5 days to review though.
