### ISSUE TITLE
No script to execute in the browser?

### ISSUE THREAD

**Issue by Sander1801** [proyecto26/react-native-inappbrowser#313]
Hello guys,

With the in-app-browser of Ionic, you can execute a console script, but I don't see any 'executeScript' function in the react-native-inappbrowser. WIll this be developed, or is there an option somewhere?

Here is an example of what I mean: https://stackoverflow.com/questions/42362503/how-to-use-executescript-method-of-inappbrowser-plugin-in-ionic-2

Thanks in advance!

**Comment by jdnichollsc** [comment]
Hey @Sander1801, **execute script** option only exist from a **WebView** component, that's not supported by this library
