### ISSUE TITLE
Getting error when trying to open the browser (_utils.RNInAppBrowser.isAvailable())

### ISSUE THREAD

**Issue by jhonidev** [proyecto26/react-native-inappbrowser#314]
Hello, im getting this following error when I try to open the browser:

'null is not an object (evaluating '_utils.RNInAppBrowser.isAvailable')'

I'm using expo running react native on Android Emulator (Android Studio)

I have tried to install it manually too, doing the steps I found on readme.md, but nothing solves it.

My code is pretty simple, it is actually the demo code.

**Comment by jdnichollsc** [comment]
Did you eject Expo first? otherwise, please use the Expo [WebBrowser](https://github.com/expo/expo/tree/master/packages/expo-web-browser) package instead

**Comment by ahnafnafee** [comment]
> Did you eject Expo first? otherwise, please use the Expo [WebBrowser](https://github.com/expo/expo/tree/master/packages/expo-web-browser) package instead

Can this package work with Expo Custom Dev clients?

**Comment by jdnichollsc** [comment]
@ahnafnafee please report an issue from the repository of that project 👍
