### ISSUE TITLE
Inappbrowser showing a warning message in IOS app 

### ISSUE THREAD

**Issue by itskris84** [proyecto26/react-native-inappbrowser#315]
Android & emulator - Working fine 
IOS & emulator - Showing below warning
- CLI: (run `react-native --version` to fetch it) - 2.0.1
react-native - 0.64.1

"react-native-inappbrowser-reborn": "^3.4.0",

In our IOS app while accessing a url inappbrowser is showing a warning message (attached). Please advice  how can i fix this 
![Screen Shot 2021-12-07 at 11 09 27 AM](https://user-images.githubusercontent.com/18735030/145475463-02c473a8-c6c0-442b-8f13-b169b88a5d28.png)

**Comment by jdnichollsc** [comment]
Please share a reproducible demo to be able to debug your issue, what versions of iOS are you using?

**Comment by itskris84** [comment]
i dont think i can use those urls outside. IOS which i have tried is 14.4. Can you pls tell me what will be the cause of this like is it inappbrowser issue or the url/site which i am trying access ?

**Comment by jdnichollsc** [comment]
No idea, a VPN issue? I can't identify the problem without having a reproducible demo to debug, as I can see that's an error from that external website, because that's not a native warning from iOS system
