### ISSUE TITLE
Header not working for android

### ISSUE THREAD

**Issue by tiennv-0883** [proyecto26/react-native-inappbrowser#316]
### Make sure to check the demo app(s) for sample usage 
- emulator
- device 
- 
### Please, provide the following version numbers that your issue occurs with:

- CLI:
react-native-cli: 2.0.1
react-native: 0.64.1

- Plugin(s):
"react-native-inappbrowser-reborn": "3.6.3"

 I posted the header and checked its request
 <img width="681" alt="Ảnh chụp Màn hình 2021-12-11 lúc 13 23 15" src="https://user-images.githubusercontent.com/49437058/145666731-47cc39f9-78b3-43ef-8cc7-d8663f114436.png">

But I don't get it
<img width="681" alt="Ảnh chụp Màn hình 2021-12-11 lúc 13 22 49" src="https://user-images.githubusercontent.com/49437058/145666724-fd826304-a2fd-4ef1-8752-d3f8704fa866.png">

Please help me .

**Comment by tiennv-0883** [comment]
I have looked into the root cause. Hope to get a reply as soon as possible.
https://developer.chrome.com/docs/android/custom-tabs/headers/#set_up_a_custom_tabs_connection_to_validate_the_asset_link

**Comment by jdnichollsc** [comment]
> I have looked into the root cause. Hope to get a reply as soon as possible. https://developer.chrome.com/docs/android/custom-tabs/headers/#set_up_a_custom_tabs_connection_to_validate_the_asset_link

We're already using `EXTRA_HEADERS` or what do you mean? 🤔

**Comment by jdnichollsc** [comment]
> I have looked into the root cause. Hope to get a reply as soon as possible. https://developer.chrome.com/docs/android/custom-tabs/headers/#set_up_a_custom_tabs_connection_to_validate_the_asset_link

I didn't understand, maybe you shared a wrong link

**Comment by jdnichollsc** [comment]
Ok, Chrome removed the support of custom headers, check [here](https://stackoverflow.com/a/63178728/1532821) for more details

**Comment by jdnichollsc** [comment]
Nevermind, it looks like you can create digital asset links to support that https://developer.chrome.com/docs/android/custom-tabs/headers/

Please try and let me know!
