### ISSUE TITLE
Move away from jCenter

### ISSUE THREAD

**Issue by matteodanelli** [proyecto26/react-native-inappbrowser#317]
jcenter is stale. It'll be read only in February 2022 and not updates to dependencies cannot be done.

Is it possible to replace it with mavenCentral? All dependencies should be already there.

**Comment by jdnichollsc** [comment]
Any pull request is more than welcome! <3

**Comment by matteodanelli** [comment]
https://github.com/proyecto26/react-native-inappbrowser/pull/320 @jdnichollsc
