### ISSUE TITLE
Return json from browser to app

### ISSUE THREAD

**Issue by andrey-shostik** [proyecto26/react-native-inappbrowser#319]
I need to return API response which I received in web to the app. I checked docs but I havn't found solution. I think solution could be set json in browser param url and then return somehow the url to app, but I can't get the url
My code looks like this.
```
const data = await InAppBrowser.open(payUrl, {
  enableBarCollapsing: false,
  dismissButtonStyle: 'done',
  showTitle: true,
  modalEnabled: true,
  animated: true,
  enableUrlBarHiding: true,
});
console.log(data);
```
When I close browser using done button I receive `{type: "cancel"}` in data without any url. Any solution?

**Comment by jdnichollsc** [comment]
The suggestion here is using a deep linking redirection and sending data with a query param :)
And then you can extract these query params using [Linking](https://reactnative.dev/docs/linking)

**Comment by boyepanthera** [comment]
@jdnichollsc Sorry I had to comment on closed issues, I am in a similar situation and need to send data back from the inappbrowser but I cannot seem to understand where to get value for my-host and scheme based on what the documentation says. I would appreciate some code examples if possible thank you.

**Comment by stee1ix** [comment]
@boyepanthera Did you find any way?
