### ISSUE TITLE
Unable to use jcenter

### ISSUE THREAD

**Issue by BenjaminSAILcloud** [proyecto26/react-native-inappbrowser#323]
Can this [PR](https://github.com/proyecto26/react-native-inappbrowser/pull/320) be accepted as quick as possible please ?

Jcenter is unaccessible at the moment and I can't build my app.

![image](https://user-images.githubusercontent.com/33052668/149775858-b681e35d-bcda-4ef6-8b7c-0c8515312a8c.png)

<details>
<summary>Stacktrace</summary>

```
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.webkit:android-jsc:+.
     Required by:
         project :app
      > Failed to list versions for org.webkit:android-jsc.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
               > Read timed out
   > Could not resolve org.greenrobot:eventbus:3.+.
     Required by:
         project :app > project :react-native-inappbrowser-reborn
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

</details>

**Comment by willianlemes** [comment]
I'm having this problem too

**Comment by NicoMoli** [comment]
I am having the problem now, It's very important that we could found a solution. Thanks

**Comment by chrismerino** [comment]
@jdnichollsc, I'm having the same issue on a little project... Could it be related to this thread?
![in-app-browser-build-error](https://user-images.githubusercontent.com/10505127/168140640-55d6b4a9-f18e-4309-b14f-64b7526b055d.jpg)

**Comment by arcollector** [comment]
@[chrismerino](https://github.com/chrismerino) try this, go to file `android\build.gradle`  and changed the line `implementation 'org.greenrobot:eventbus:3.+'` to `implementation 'org.greenrobot:eventbus:3.1.0'`

also i suggest you to abandoned this library sadly the author has not time to keep it updated

**Comment by chrismerino** [comment]
> @[chrismerino](https://github.com/chrismerino) try this, go to file `android\build.gradle` and changed the line `implementation 'org.greenrobot:eventbus:3.+'` to `implementation 'org.greenrobot:eventbus:3.1.0'`
> 
> also i suggest you to abandoned this library sadly the author has not time to keep it updated

Thank you @arcollector, this worked. Do you know any other similar library that is maintained? Ideally I would prefer to send a PR to this project but it seems there are a few still waiting for approval from author.

**Comment by slxsh** [comment]
> > @[chrismerino](https://github.com/chrismerino) try this, go to file `android\build.gradle` and changed the line `implementation 'org.greenrobot:eventbus:3.+'` to `implementation 'org.greenrobot:eventbus:3.1.0'`
> > also i suggest you to abandoned this library sadly the author has not time to keep it updated
> 
> Thank you @arcollector, this worked (edit: this worked locally but is not a good idea to work this way). Do you know any other similar library that is maintained? Ideally I would prefer to send a PR to this project but it seems there are a few still waiting for approval from author.

Did you find any other library?

**Comment by slxsh** [comment]
> @[chrismerino](https://github.com/chrismerino) try this, go to file `android\build.gradle` and changed the line `implementation 'org.greenrobot:eventbus:3.+'` to `implementation 'org.greenrobot:eventbus:3.1.0'`
> 
> also i suggest you to abandoned this library sadly the author has not time to keep it updated

My android\build.gradle doesn't have `implementation 'org.greenrobot:eventbus:3.+'` and adding it causes some error.

**Comment by arcollector** [comment]
@chrismerino itnst your build.gradlew, file is located in `node_modules/react-native-inappbrowser/android/build.gradle`

**Comment by chrismerino** [comment]
> > > @[chrismerino](https://github.com/chrismerino) try this, go to file `android\build.gradle` and changed the line `implementation 'org.greenrobot:eventbus:3.+'` to `implementation 'org.greenrobot:eventbus:3.1.0'`
> > > also i suggest you to abandoned this library sadly the author has not time to keep it updated
> > 
> > 
> > Thank you @arcollector, this worked (edit: this worked locally but is not a good idea to work this way). Do you know any other similar library that is maintained? Ideally I would prefer to send a PR to this project but it seems there are a few still waiting for approval from author.
> 
> Did you find any other library?

I haven't yet, although I noticed that Expo has `expo-web-browser` which apparently can be added to a React Native CLI project (which is my case). I haven't tested it yet but probably will because I'd like to keep using the in-app browser functionality.

**Comment by jdnichollsc** [comment]
Sorry for the delay folks, hope you're doing well

I was very busy because I am going to start working in another company and I was sick these days, I'm testing here right now to publish a new version ASAP!

Happy Friday! <3
