### ISSUE TITLE
Callback for exit from in app browser

### ISSUE THREAD

**Issue by schoenbl** [proyecto26/react-native-inappbrowser#325]
This is a question for iOS and Android

Is there a way to execute a callback when the `Cancel` button is pressed and a user leaves the in app browsers?
<img width="323" alt="Screen Shot 2022-01-24 at 9 15 12 AM" src="https://user-images.githubusercontent.com/47538745/150831687-f77e2973-38c5-4441-9872-125a8df37583.png">

**Comment by jdnichollsc** [comment]
The promise returned with `open` and `openAuth` methods is finished when the user press that button :)

**Comment by schoenbl** [comment]
> The promise returned with `open` and `openAuth` methods is finished when the user press that button :)

@jdnichollsc Is a legend
