### ISSUE TITLE
Error:  Can not read property isAvailable of null

### ISSUE THREAD

**Issue by chyamuna** [proyecto26/react-native-inappbrowser#328]
We are facing the error 'Can not read property isAvailable of null' with below simple code

```
import { InAppBrowser } from 'react-native-inappbrowser-reborn';
.....
  try {
    if (await InAppBrowser.isAvailable()) {
      const result = await InAppBrowser.open(url);
      Alert.alert(JSON.stringify(result));
    }
  } catch (error) {
    Alert.alert(error.message);
  }
```

React native version : 0.64.2
react-native-inappbrowser version : 3.6.3
using typescript
Android API 30 pixel emulator

Note:
1.  it's not expo project ( we have android and ios separate folders and we don't have custom code there)
2.  We did linking ( react-native link react-native-inappbrowser && react-native run-android)

**Comment by jdnichollsc** [comment]
Please attach a reproducible demo to be able to debug your issue 👍

**Comment by julienR2** [comment]
Hey @chyamuna !
I just faced the same issue, and adding those missing lines from the installation doc in our `build.gradle` fixed the issues
```
androidXAnnotation = "1.2.0"
androidXBrowser = "1.3.0"
```
![CleanShot 2022-02-11 at 17 25 23@2x](https://user-images.githubusercontent.com/3007435/153639278-8f6f865c-6d64-442a-a043-ed816f325c40.png)

Does it solves the issue for you too ? (Weirdly enough, we have another project without those lines, but also on AndroidX, that is working fine 🙃 )

**Comment by jdnichollsc** [comment]
This error comes from a fail native Linking (wrong installation), Android Backward compatibility is hard to support 😅

**Comment by chyamuna** [comment]
Our app works on another platform. Platform is a hybrid app, where it doesn't support auto linking. I was incorrectly linking the module in our app. when I added this android native module to our platform android native modules, our app could able to consume this module and the error is not coming anymore

**Comment by trongtai1801** [comment]
In my case, I added these line to android/build.grade, run **cd android && ./gradlew clean  && cd ..** and rebuild

<img width="814" alt="image" src="https://user-images.githubusercontent.com/31733095/233760843-ad7ae971-2ee1-40a8-93fa-e30d7ed5c4eb.png">
