### ISSUE TITLE
iOS: Add formSheetPreferredContentSize prop to allow for custom sized formSheet modals

### ISSUE THREAD

**Issue by ShaneMckenna23** [proyecto26/react-native-inappbrowser#330]
## Overview
I currently use this library on one of my projects and require the need to display an in-app browser, on an iPad, with portrait dimensions when the device is in landscape. I simply need a way to define the size of the modal. 

`formSheet` modals can be resized with the `preferredContentSize` attribute.

### Note
The `preferredContentSize` attribute is ignored on iPhone. I believe this is due to `formSheet` presentation on iPhone is adapted to full screen as of IOS 13.

### Which platform(s) does your issue occur on?
- iOS
- Device: iPad

**Comment by jdnichollsc** [comment]
Thanks a lot for your contribution mate! <3
