### ISSUE TITLE
iFrame Integration & Questions

### ISSUE THREAD

**Issue by salorsino** [proyecto26/react-native-inappbrowser#334]
Hello,

Is it possible to use this with an iFrame? I know I can open the contents of the iFrame within this browser, that is working smooth, but the iFrame will be sending a window.postMessage() back to my application with some data. 

Is it possible using this library to access the contents of window.postMessage() and also close the browser with a method/function after?

Thanks,

Sal

**Comment by jdnichollsc** [comment]
Sorry, that's not possible using Chrome CustomTabs from Android or SafariViewController from iOS, you have to use a WebView instead.
