### ISSUE TITLE
[Error: InAppBrowser not available]

### ISSUE THREAD

**Issue by LeoAsher25** [proyecto26/react-native-inappbrowser#337]
I'm using InAppBrowser to authenticate with KeyCloak and I get a issue when I call keycloak.login(). When I using physical device (Oppo realme c15, Android 11), there's no problem here, but when I run in emulator Pixel 5 API 30 (Androud 11 Google APIs), there is a error: InAppBrowser not available. (like below image). I would appreciate any suggestions.
![image](https://user-images.githubusercontent.com/80992197/160460604-14b78349-b2d7-4724-a843-af0e5b14a811.png)

Here is some config file following instructions: 
1) android/app/src/main/AndroidManifrest.xml 
![image](https://user-images.githubusercontent.com/80992197/160462865-bb162e24-925e-41e8-9c70-3531ebdf32b8.png)
2) android/build.gradle
![image](https://user-images.githubusercontent.com/80992197/160463066-7800e4d3-1860-4343-86b4-319318d52325.png)
3) android/app/src/main/.../MainApplication.java 
![image](https://user-images.githubusercontent.com/80992197/160463412-106d9394-1ccc-48ae-aeec-d23602d94eb9.png)
4) android/setting.gradle
![image](https://user-images.githubusercontent.com/80992197/160463573-becf9005-d089-47b8-82e0-6a74e829a534.png)
5) android/app/build.gradle
![image](https://user-images.githubusercontent.com/80992197/160463870-ebc0073d-83c2-4b66-86da-1691c53196f3.png)

**Comment by smourey** [comment]
Hi @LeoAsher25 , we have the exact same issue in one of our apps. Have you found a solution to this?
Thank you

**Comment by MBedy** [comment]
Hello @LeoAsher25, did you solve this problem ? I have the same problem.

**Comment by LeoAsher25** [comment]
I still haven't solved that problem yet, I'm using physical device now.

Vào Th 5, 21 thg 4, 2022 vào lúc 16:25 smourey ***@***.***>
đã viết:

**Comment by MBedy** [comment]
i solved the issue, it is because the emulator needs google play. (English
is not my first language)

**Comment by MBedy** [comment]
https://stackoverflow.com/questions/38593738/is-google-play-store-supported-in-avd-emulators,
Look at the **Easiest way**: `https://stackoverflow.com/questions/38593738/is-google-play-store-supported-in-avd-emulators`

**Comment by edcalderon** [comment]
thanks! @MBedy that solve same problem here

**Comment by edcalderon** [comment]
@LeoAsher25 can u share how do you configure the keycloack client i'm getting and internal error seams like is bad configured 
![image](https://github.com/proyecto26/react-native-inappbrowser/assets/25994054/ac02aecc-2701-40e1-956d-f0bcc966ff26)
