### ISSUE TITLE
Alert.alert() not working (most of the time) in catch block on android

### ISSUE THREAD

**Issue by Adnan-Bacic** [proyecto26/react-native-inappbrowser#339]
### Which platform(s) does your issue occur on?
- Android
- Android 12
- emulator. Pixel 5

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `react-native --version` to fetch it)
6.0.1
im on react-native 0.67.1
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
3.5.1
edit: just tried updating to current version of 3.6.3, and it still happens.

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

1. write a try/catch with and alert() in the catch
2. Put an invalid url to try. i have tried "test" or empty string "" or "google.invalid". it doesnt alert.
3. click to open the link on android. no alert is shown. other code written after the alert is run, such as console.log(). even custom functions afterwards work.

SOMETIMES it alerts, but rarely, and then it only does it once. after it has been dismissed it wont appear again.

alerts works fine otherwise.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

this is basically just the code from the example, i just removed all the options and put an invalid url:

```
async openLink() {
    try {
      const url = 'test'
      if (await InAppBrowser.isAvailable()) {
        const result = await InAppBrowser.open(url)
        Alert.alert(JSON.stringify(result))
      }
      else Linking.openURL(url)
    } catch (error) {
      console.log(error)
      Alert.alert(error.message)
      console.log('post alert')
    }
  }
```

**Comment by jdnichollsc** [comment]
Try adding a delay before showing the alert, something like this:

```
async sleep(timeout: number) {
  return new Promise(resolve => setTimeout(resolve, timeout));
}

async openLink() {
    try {
      const url = 'test'
      if (await InAppBrowser.isAvailable()) {
        const result = await InAppBrowser.open(url);
        await sleep(800);
        Alert.alert(JSON.stringify(result))
      }
      else Linking.openURL(url)
    } catch (error) {
      Alert.alert(error.message)
      console.log('post alert')
    }
```

During my tests I found race conditions like this scenario with these native components, please try and let me know! 👍
