### ISSUE TITLE
Google Developer Console complains about using android.permission.QUERY_ALL_PACKAGES

### ISSUE THREAD

**Issue by norbertschuler** [proyecto26/react-native-inappbrowser#343]
Using react-native-inappbrowser version 3.6.3 in our Android app results into Google complaining about our app to not be compliant due to usage of `android.permission.QUERY_ALL_PACKAGES`. This must be explained as otherwise the app might get rejected. 

<img width="474" alt="Screenshot 2022-04-28" src="https://user-images.githubusercontent.com/1532418/165737950-fca3f7e2-2880-4702-919d-cafa4a8814a4.png">

My question: Is this permission from the Android Manifest of react-native-inappbrowser a necessary requirement for this module to work or can it be removed in future versions, e.g. replacing as described in https://developer.android.com/training/package-visibility?

**Comment by gavrichards** [comment]
Discussed here:
https://github.com/proyecto26/react-native-inappbrowser/issues/311
