### ISSUE TITLE
Automate publish process

### ISSUE THREAD

**Issue by vincent-paing** [proyecto26/react-native-inappbrowser#349]
Since there are important changes recently like https://github.com/proyecto26/react-native-inappbrowser/commit/56a08e40914dec7d240127b4d588b91edbdbc7c9 and https://github.com/proyecto26/react-native-inappbrowser/commit/20468573f971a75fc1ee40d3ded557dfd0c4308c. I think it'd be great to have a new release. Especially because Play store require app to remove `QUERY_ALL_PACKAGES` permissions by end of June.

**Comment by jdnichollsc** [comment]
Sure, thanks for all your help mate! 
I was sick and then I got a job offer, so I've been a bit busy, sorry for the delay!

I think we need to include semantic release with GitHub actions to automate the process of publishing new releases 🙏

**Comment by jdnichollsc** [comment]
Duplicates of #276

**Comment by vincent-paing** [comment]
It's alright, mate. We all need a break sometimes, I hope you feel better. Thanks for all your effort
