### ISSUE TITLE
Notch support

### ISSUE THREAD

**Issue by revh** [proyecto26/react-native-inappbrowser#35]
Hi,

When  inappbrowser browser is opened in a phone with notch, the content in the webview is visible in the space between the inappbrowser title bar and the notch 

![artboard](https://user-images.githubusercontent.com/726921/50681278-33b9a580-100b-11e9-8493-3f9b702cf2f6.jpg)

**Comment by revh** [comment]
```js
StatusBar.setHidden(false) // I've just added this line to workaround the issue
InAppBrowser.open(url)
```

**Comment by brunolemos** [comment]
Hiding the statusbar shouldn't be necessary. There must be a better fix.

**Comment by jdnichollsc** [comment]
We're using this library from iPhone X too 👍

**Comment by jdnichollsc** [comment]
@brunolemos but let me know if you need an option to modify the Safari's navigationBar, any pull request is welcome! 💯 https://github.com/proyecto26/react-native-inappbrowser/blob/master/ios/RNInAppBrowser.m#L130
