### ISSUE TITLE
QUERY_ALL_PACKAGES into npm

### ISSUE THREAD

**Issue by thehellmaker** [proyecto26/react-native-inappbrowser#355]
Hi, 
I do see that the change has been made to Manifest file to remove the permission QUERY_ALL_PACKAGES however a new build into NPM hasn't happened recently which would greatly help as Google is planning to have strict rules against using this permission. Any timelines on when such a build can be made available in npm. Would be happy to help in anyway for the same.

**Comment by informsharique** [comment]
Hi, facing same issue. Because of this Play Store is giving warning that after 12th July, the app will be removed. Can we have a build for this now since this is resolved in the commit [56a08e4](https://github.com/proyecto26/react-native-inappbrowser/commit/56a08e40914dec7d240127b4d588b91edbdbc7c9)

**Comment by chrismerino** [comment]
Hi @jdnichollsc, can you help us releasing a new version to NPM?

**Comment by swushi** [comment]
Same for us, this is obviously a huge blocker. Like the library, but we are currently looking for alternatives because of this.

**Comment by msvargas** [comment]
Add the following line in AndroidManifest.xml

```
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" tools:node="remove" />
```

**Comment by jdnichollsc** [comment]
Hello folks, excuse me for the delay
My Mac stopped working, I'm planning to release a new version as soon as possible, sorry for the inconvenience 🙏 

Regards,
Juan

**Comment by daba-faith** [comment]
Can someone else do it?, @jdnichollsc, this is a major blocker, we would really appreciate if action taken soon

**Comment by swushi** [comment]
This was a great library, but can't sit around waiting for the update. Switched to https://github.com/react-native-webview/react-native-webview

**Comment by chrismerino** [comment]
Hello @jdnichollsc, can we get an update? This is a very useful lib and is being used by a many projects.

**Comment by KevinvdBurg** [comment]
Any update, July 20th is getting closer and closer? 👀

**Comment by rileycognitv** [comment]
plz update! remove QUERY_ALL_PACAKGES 

love this dependency but I may have to find a new one so I can put an app back onto the store

**Comment by KevinvdBurg** [comment]
@rileycognitv What I did it forked the repo and referenced the fork in the package.json like this:

`"react-native-inappbrowser-reborn": "https://github.com/KevinvdBurg/react-native-inappbrowser.git",`

**Comment by jdnichollsc** [comment]
Hello folks, please help me reviewing this PR for the new Release 3.7.0 https://github.com/proyecto26/react-native-inappbrowser/pull/375

**Comment by jdnichollsc** [comment]
> @rileycognitv What I did it forked the repo and referenced the fork in the package.json like this:
> 
> `"react-native-inappbrowser-reborn": "https://github.com/KevinvdBurg/react-native-inappbrowser.git",`

Also you can point to a specific branch/commit/tag using git, e.g:
```
"react-native-inappbrowser-reborn": "https://github.com/proyecto26/react-native-inappbrowser.git#develop",
```
Sorry for the delay folks 😥
