### ISSUE TITLE
Support for Trusted Web Activity

### ISSUE THREAD

**Issue by nadishan** [proyecto26/react-native-inappbrowser#357]
Can we use this library to display trusted web applications? Basically, my requirements are, hide URL, disable the share button, and disable 3 dots menu. I need to run all of above options in Android and iOS platforms.

**Comment by AlexanderLanderos** [comment]
@nadishan Yes you can do all of the above mentioned.

**Comment by jdnichollsc** [comment]
Please check if that's supported with Chrome CustomTabs and SafariViewController and let us know to reopen this issue! 👍

**Comment by AlbertoMeQ** [comment]
This would be amazing!

And `Trusted Web Activity` would solve lots of customization issues for this wonderful library!
