### ISSUE TITLE
Android app builds are failing after package installation: `error: package R does not exist`

### ISSUE THREAD

**Issue by rubina-shakhkyan** [proyecto26/react-native-inappbrowser#360]
### Which platform(s) does your issue occur on?
-Android

### Please, tell us how to recreate the issue in as much detail as possible. 
The app build is failing on this line
`isLightTheme ? R.drawable.ic_arrow_back_black : R.drawable.ic_arrow_back_white` with the following error:
`error: package R does not exist`

**Comment by jdnichollsc** [comment]
Please refer to this StackOverflow [thread](https://stackoverflow.com/questions/12986301/package-r-does-not-exist)
