### ISSUE TITLE
Unable to render Html source in InAppBrowser

### ISSUE THREAD

**Issue by devTTC129** [proyecto26/react-native-inappbrowser#361]
Is it possible to render html in string format in InAppbrowser ?

while using inAppBrowser in cordova able to render html page in browser (html is in string format. converting it to base64 and passed it as source) . but in react native not able to do same .

let me know if any one has done it .
Thanks

**Comment by jdnichollsc** [comment]
**InAppBrowser** in **Cordova** use [WebView](https://reactnative.dev/docs/0.61/webview) in order to do that, try that component instead! <3
