### ISSUE TITLE
Automatically redirect inside app via Deep Link Android

### ISSUE THREAD

**Issue by AMTrityak** [proyecto26/react-native-inappbrowser#365]
I use react-native-inappbrowser with amplify for social login for Apple and Google. My Deep Links work correct. On IOS I have automatically redirect inside app but on android just opens site instead application. So I need to create additional route in my site with button that will redirect inside mobile application. Do we have variant use deep link for android automatically as in IOS?

**Comment by jdnichollsc** [comment]
Hello mate, did you try this approach? https://developer.android.com/training/app-links

Maybe you need to use Universal Links for your apps: https://medium.com/bumble-tech/universal-links-for-android-and-ios-1ddb1e70cab0

Please let me know!
