### ISSUE TITLE
i am unable to hide address bar in inappbrowser 

### ISSUE THREAD

**Issue by aabsharkhan1** [proyecto26/react-native-inappbrowser#367]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `react-native --version` to fetch it)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by jdnichollsc** [comment]
Please follow the steps of our [issue template](https://github.com/proyecto26/react-native-inappbrowser/blob/develop/.github/issue_template.md)
