### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by mtalhagaoglu** [proyecto26/react-native-inappbrowser#378]
Hi,

I'm getting the below error via Sentry in my production. When I check the ADB logcat there isn't any error tho, just crashing.

Subscriber class com.proyecto26.inappbrowser.c and its super classes have no public methods with the @Subscribe annotation

I am using the latest version of the library, previous version gives QUERRY_ALL_PACKAGES error so google play forced me update the version :/

**Comment by jdnichollsc** [comment]
@mtalhagaoglu did you enable ProGuard? If so, please check the README of this repository to update your ProGuard config, please let us know! <3

**Comment by hugoh59** [comment]
The readme only specifies proguard configuration for RN <= .060 what if we're still getting this crash and using  RN > 0.60, is it the same configs ? @jdnichollsc

**Comment by mtalhagaoglu** [comment]
Sorry @jdnichollsc, I forgot to reply back to you. My problem was solved after disabling Proguard. Thank you.
