### ISSUE TITLE
Query-All-Package rejected by Google play console

### ISSUE THREAD

**Issue by RatikantAppstango** [proyecto26/react-native-inappbrowser#379]
Hello Everyone.
I have used inappbrouser-reborn for social login through AWS amplify like (Gmail and Facebook). Everything is working fine in the application.
While uploading the app to the google play console it was rejected because of query-all-package
![One](https://user-images.githubusercontent.com/105271851/185195496-1685fbd8-f475-4927-881c-1c3e28ac6ec8.PNG)

I have also inserted (uses-permission android:name=" android.permission.QUERY_ALL_PACKAGES")  into my AndroidManifest.xml and resubmitted the app but it still gets rejected.

Any suggestions

**Comment by jdnichollsc** [comment]
@RatikantAppstango hello mate, that permission was removed in the last version of this lib, please check [this thread](https://github.com/proyecto26/react-native-inappbrowser/issues/311#issuecomment-1211810025) for more details.

**Comment by RatikantAppstango** [comment]
Which form do I need to fill out?
