### ISSUE TITLE
Access denied on android

### ISSUE THREAD

**Issue by hieupaul** [proyecto26/react-native-inappbrowser#38]
I'm using cookie to save my session login, but seem InAppBrowser doesn't have Cookie permission so browser show Access denied message instead of redirect url callback.

> `InAppBrowser.openAuth(url, this.conf.appsiteUri, {
>       // iOS Properties
>       dismissButtonStyle: 'back',
>       readerMode: false,
>       // Android Properties
>       showTitle: false,
>       enableUrlBarHiding: true,
>       enableDefaultShare: true,
>       forceCloseOnRedirection: true,
>       animations: {
>         startEnter: 'slide_in_right',
>         startExit: 'slide_out_left',
>         endEnter: 'slide_in_right',
>         endExit: 'slide_out_left'
>       }
>     })`

Any ideas?
 
![img_2089](https://user-images.githubusercontent.com/19374802/51027255-54fe3100-15cb-11e9-9629-6f323974b185.jpg)
![img_2090](https://user-images.githubusercontent.com/19374802/51027268-57f92180-15cb-11e9-9bfb-f86043f36d66.jpg)

**Comment by jdnichollsc** [comment]
can you use headers instead?

**Comment by jdnichollsc** [comment]
It looks like Android Chrome tabs doesn't support cookies
