### ISSUE TITLE
Can I open another screen over InappBrowser?

### ISSUE THREAD

**Issue by namnh-0652** [proyecto26/react-native-inappbrowser#382]
Thanks for awesome library!

I have a passcode screen, when the app goes to background and back to foreground, then this passcode screen should show over the current screen. Now, how can I open it over in-app browser ? In android, the in-app browser is another Activity than the MainActivity, isn't it?.

Can you give me a suggestion for my case?

**Comment by jdnichollsc** [comment]
You're right, Chrome CustomTabs use another Android Activity, so about your requirement, you can't do that as far as I know. Please check the docs of these Native APIs and let me know if you find any alternative! Closing issue in the meantime :-1:
