### ISSUE TITLE
Is there a possible way to disable prompt when using openAuth()

### ISSUE THREAD

**Issue by seco35** [proyecto26/react-native-inappbrowser#384]
As per the documentation the user is getting a popup dialog to open the authentication screen.
> On iOS, the user will be asked whether to allow the app to authenticate using the given url (OAuth flow with deep linking redirection).

Is there a way to avoid this prompt by allowing the app to use a specific link for the authentication beforehand.

The main reason to accomplish that is, that the current workflow is not proper UX. The prompt comes up whenever openAuth() method is called and in my case whenever the user re-opens the app, since I try to re-authenticate using the persisted session after restart. It could easily be done in the background: Using the persisted session to the identity provider (keycloak for my case) the browser opens (with the popup) and redirects the user automatically back to the app using deeplink, since there is no reason for any user input, due to the active session.

To have the prompt always appearing requires user action and prevents the re-authentication in background.

**Comment by jdnichollsc** [comment]
@seco35 did you try using the *ephemeralWebSession* option for iOS?

**Comment by seco35** [comment]
> @seco35 did you try using the *ephemeralWebSession* option for iOS?

I don't know how this can help me to accomplish my intention?

As per the doc:

> ephemeralWebSession : Prevent re-use cookies of previous session (openAuth only) [true/false]

That's exact the opposite what I'm expecting. I want to use the previous cookie information in order to keep the user signed in. The only thing that I want to prevent from happening is the popup dialog that comes up when opening the inapp browser with the openAuth() method.

**Comment by jdnichollsc** [comment]
@seco35 gotcha, that's not possible from iOS, check below link for more details:
https://stackoverflow.com/a/47633537/1532821

**Comment by jdnichollsc** [comment]
BTW, this article looks great for more details
https://developer.okta.com/blog/2022/01/13/mobile-sso
