### ISSUE TITLE
Could some one please explain me about the below sleep method.  (Sorry this is not an issue)

### ISSUE THREAD

**Issue by gangadhartinmen** [proyecto26/react-native-inappbrowser#39]
sleep = m => new Promise(r => setTimeout(r, m))

**Comment by gangadhartinmen** [comment]
Thanks. I got that.

async openLink() {
    try {
      await InAppBrowser.isAvailable()
      StatusBar.setBarStyle('light-content')
      const response = await InAppBrowser.open(this.state.url, {
        // iOS Properties
        dismissButtonStyle: 'cancel',
        preferredBarTintColor: 'gray',
        preferredControlTintColor: 'white',
        readerMode: false,
        // Android Properties
        showTitle: true,
        toolbarColor: '#6200EE',
        secondaryToolbarColor: 'black',
        enableUrlBarHiding: true,
        enableDefaultShare: true,
        forceCloseOnRedirection: false,
        // Specify full animation resource identifier(package:anim/name)
        // or only resource name(in case of animation bundled with app).
        animations: {
          startEnter: 'slide_in_right',
          startExit: 'slide_out_left',
          endEnter: 'slide_in_right',
          endExit: 'slide_out_left',
        },
        headers: {
          'my-custom-header': 'my custom header value'
        },
      })
      await this.sleep(800)
      Alert.alert('Response', JSON.stringify(response))
    } catch (error) {
      Alert.alert(error.message)
    }

After opening InAppBrowser, you are calling sleep method. Could you please tell me, why it is called like that?

**Comment by jdnichollsc** [comment]
In that example, when the browser is closed, I wait 800 milliseconds to show an alert to the user

**Comment by gangadhartinmen** [comment]
Okay Thank you so much for the clarification.
