### ISSUE TITLE
InAppBrowser.openAuth never redirects back after google login

### ISSUE THREAD

**Issue by nateshmbhat** [proyecto26/react-native-inappbrowser#390]
I am using ios 16.1 simulator.
RN 0.66.4

Only for devices above 16.1 , after sign in, redirection is not happening and the `openAuth` method's promise NEVER resolves even though the user has finished sign in.

Looks like its related to issue #387 but for some reason that issue was closed without providing any resolution.

**Comment by Hellhiem** [comment]
It's probably general firebase issue:

https://github.com/firebase/firebase-js-sdk/issues/6716

**Comment by bustazone** [comment]
That is happening to me as well. 
It seems like the function waitForRedirectAsync (inside 'node_modules/react-native-inappbrowser-reborn/utils.js') is not triggered in the redirections and so openAuth never detects that the auth is ended.

**Comment by jdnichollsc** [comment]
Duplicated
