### ISSUE TITLE
How do I clear the browsers cache/state

### ISSUE THREAD

**Issue by MoSattler** [proyecto26/react-native-inappbrowser#393]
### Which platform(s) does your issue occur on?
- iOS 13.7 / Emulator

### Please, provide the following version numbers that your issue occurs with:
- CLI: 0.70.0

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

In our app, user's can log out. When they logout, we also want to log them out from the in-app browser. 
Right now, after they log out from the app, and they open the browser, they are still logged in the browser. 

Is there any function we can call to clear the browser cache, so we can clear everything upon logout?

**Comment by asdolo** [comment]
You can set `ephemeralWebSession: false` in the options params of `openAuth`, but it only works for iOS.

**Comment by fltonii** [comment]
Hmm, any way to do this in Android? I'm thinking of launching the browser on logout and calling an endpoint that clears the cookies, but that's pretty lame tbh. I'd much prefer to have a way to stash the cookies as the IAB closes.

**Comment by asdolo** [comment]
@MoSattler did you find a solution?
