### ISSUE TITLE
 Implicit declaration of function 'RCTPresentedViewController' is invalid in C99

### ISSUE THREAD

**Issue by trinadhkoya** [proyecto26/react-native-inappbrowser#40]
Too many arguments to block call, expected 1, have 3

**Comment by jdnichollsc** [comment]
@trinadhkoya can you debug by using "legacy build mode" in XCode (see File -> Workspace Settings -> Build System)

**Comment by Raserad** [comment]
I get same error too

OS: MacOS Mojave 10.14.2
IDE: XCode 10.14.2

**Comment by jdnichollsc** [comment]
Let me try to find that warning, in the meantime any pull request is welcome! 👍

**Comment by petekp** [comment]
Seeing this too, along with a handful of other errors:

![image](https://user-images.githubusercontent.com/950779/54402920-45fb3400-468b-11e9-9457-ef4571cd535e.png)

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 73.47 MB / 16.00 GB
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 5.3.0 - ~/.npm-packages/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: EAP EAP
      Xcode: 10.0/10L177m - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.5 => 0.58.5
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      create-react-native-web-app: 0.1.6
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by jdnichollsc** [comment]
Can you share more logs about Bad receiver and Too many argumenta please?

**Comment by petekp** [comment]
@jdnichollsc I was able to get things running after using the auto-installation method. I'd have to double-check but pretty sure I ran into issues when using the manual Podfile approach.

**Comment by jdnichollsc** [comment]
Guys, please validate the last changes of this project, pointing this package to the GitHub repo and let me know 👍

**Comment by jdnichollsc** [comment]
Check the version 2.0 and let me know

**Comment by jdnichollsc** [comment]
Other option would be using the following solution instead of `RCTPresentedViewController`:
```
AppDelegate *delegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
UIViewController *rootController = [[delegate window] rootViewController];
[rootController presentViewController:safariHackVC animated:true completion:nil];
```
Let me know 👍

**Comment by yannickoo** [comment]
_@jdnichollsc could you also tag the project here on GitHub so that the releases are also available here? Thank you for this package!_

**Comment by jdnichollsc** [comment]
@yannickoo Done!

**Comment by yannickoo** [comment]
> I'd have to double-check but pretty sure I ran into issues when using the Podfile approach.

I can confirm that I was also able to get rid of this after removing it from my Podfile :)
