### ISSUE TITLE
[IOS] Hide How to hide Safari icon in "In App Browser"?

### ISSUE THREAD

**Issue by duongtranfu** [proyecto26/react-native-inappbrowser#406]
Hi everyone,

in IOS, I would like to hide safari icon in the "In App Browser" like image below:

![image](https://user-images.githubusercontent.com/42492073/224259405-c93e7fa3-0c44-4688-8e36-96e478ff8168.png)

I did not find out any option to hide it in the document. Thank for any help.

**Comment by duongtranfu** [comment]
Hi @friederbluemle @jdnichollsc,

Could you please help?

**Comment by jdnichollsc** [comment]
I'm not sure if that's possible, did you find any native option to support that with the Safari View Controller?

**Comment by duongtranfu** [comment]
Hi @jdnichollsc I did not find out any native option to hide safari icon https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller

Do you have any idea?

**Comment by jdnichollsc** [comment]
Ok, so I don't think that's possible

**Comment by duongtranfu** [comment]
thank you @jdnichollsc
