### ISSUE TITLE
The react-native-modal does not work when react-native-inappbrowser is open (iOS only)

### ISSUE THREAD

**Issue by khj3132** [proyecto26/react-native-inappbrowser#408]
### Which platform(s) does your issue occur on?
- iOS only
- 16.2
- both

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `react-native --version` to fetch it) 6.3.1(0.67.5 in package.json)
- Plugin(s): react-native-inappbrowser-reborn - 3.6.3,

### Please, tell us how to recreate the issue in as much detail as possible. 

The react-native-modal does not work when react-native-inappbrowser is open on iOS env.
I set a timer with setTimeout and react-native-modal open when the timer is over.
When react-native-inappbrowser is open and the timer is over.
Then I close react-native-inappbrowser, the modal is not open.
It works fine on Android env.
I know that react-native-modal cannot open two at the same time.
Is the react-native-inappbrowser treated as modal in ios environment?

**Comment by nguyenduythuc** [comment]
same on me :(

**Comment by khj3132** [comment]
@nguyenduythuc I also asked react-native-modal github about this problem. In conclusion, react-native-inappbrowser is treated as a modal on iOS. So, if you want the modal to appear when react-native-inappbrowser is closed, you need to add a callback. You can check that here. https://github.com/react-native-modal/react-native-modal/issues/735
