### ISSUE TITLE
Getting action advised email from google console.

### ISSUE THREAD

**Issue by codal-mpawar** [proyecto26/react-native-inappbrowser#410]
Hello Google Developer,

We're writing to let you know that we detected the use of an embedded webview in requests to Google's OAuth 2.0 authorization endpoint in the past 120 days associated with one or more of your OAuth client IDs listed in this email.

Any affected authorization endpoint requests will be blocked with a disallowed_useragent error starting July 24, 2023. Affected requests to our authorization endpoint will display a [user-facing warning message](https://notifications.google.com/g/p/APHC3cqpBsGU4nn63OqCmqpY1_FB9n_mf56EwCtCBM1cpeAJP8LcevUBPW1fyh1BkKhy6U_hINnv27JSPHczQnqxaLbYiwSA-cBHrtQ_-IE4_4ogrOxHjV17rj6m7QeUU2-m9MDqckpHyhE-__974DVDuVSQzhijoHRoovGCHS3P3QpcITnk7XiAwJrEG2Fq2nHzBnDfk9wZq2hIeFoABng4PpNVtUp5JRCiT67bODRUzljdi1m0c8335xcc5O7JFZNYpcQlj8sQn7vTnJILTYZ_dxxpcJCBjEkzRw9lAluFXMglG6rEgbw0xAjRNJ7py3xLDfV7) starting in May until July 24, 2023.

What do you need to know?
Embedded webview libraries are highly customizable, which can expose Google's login and account authorization pages to potential "man-in-the-middle" attacks. [Google's OAuth 2.0 "Use secure browsers" policy](https://notifications.google.com/g/p/APHC3cowwN5GNGu7M0aY110TvcCx1jjAjKGPPFv14fBfhy5nu0MwyGgDlO4deNsTTzAxZg3u4QVwIu4k8Qc5zkaEnGQRo71d1WOad8y4a7Pj-FwW-E0HAJCb_eBN49ckNKPEvgJqaYHnh5P6DA2LGWC60L1NceDejYhuGGbY-AfOkYmFi7dlC3eIvWrorYInqnZ5KE5P36jkt8S12Jr0wvslOlVsEHszaipZwaVWy1JdBAZWGnE63uZe) helps us protect users from these and other types of attacks.

Examples of affected embedded webview libraries include android.webkit.WebView on Android and WKWebView on iOS or macOS.

What do you need to do?
Review our June 2021 Google Developers blog post, [Security changes to Google's OAuth 2.0 authorization endpoint in embedded webviews](https://notifications.google.com/g/p/APHC3cpTQhIoZ5KU8HLjBuscjwAA2s-luHgKzKcX_iTeUplglkyAmKjHR7QmvdtoaXtq0bFUmeSuQuM9DGL-kjgqTyza5lky0xvhGgh7lND8AzNW-fqTsF-z8YbJpk1nNP8CG-7ylly0q-pNrftSmoAwK67md64UmKhmzhUYq7d08rPeHg7-wyyXVOiafRFKLSBhZde1k0jOEZbHQvcovIhewFOz7jMpWqFSST9O69dGk1b2UZc4m89kyfVv5vdZLaPjqcVyAKucGkAe90949vCGWRM8vR7HWJ7WLD_9VeC-Sosoqg), to determine potential next steps.
Consider how enterprise and educational users might be impacted by embedded webviews in your app(s).
If you are able to modify the authorization requests of your app, you can choose to [test your application for compatibility](https://notifications.google.com/g/p/APHC3cpJV47gZHbMrS6P5HM4F18Wmr0s-4CYo3_ljjiZ8CcyyUOTvt_vncPCzJD-CoZoS5xlFw0WBoXXW-L7aTdmrsY04y-QBheO1k7fRD1AALDKnAhRNyy_wxfkF-3P_6SHoXWXmTHzvPAGk6LYssrss9FbbXdcPzMdKzks5M5flgS7bcG49yw5EnpbOydK43rjFpGhaZuZSFJ9uwCB8DSVjDbHUHooqKdodnnB2XPAayw3xrLepH8dSV2u75igaYW5rgSFr8fNfXIRm2JnFzQVTldb9KYrUXE1QZyH-O2TVezMg184GAvm) with our "Use secure browsers" policy after making the necessary changes.
Note: Suppression of the user-facing warning message is not supported.

Does anyone have any idea how we can handle this? because in future we getting this warning. I am using this library for google login from aws-amplify.

here is a little bit of code.
```javascript
urlOpener: async function urlOpener(url, redirectUrl) {
            await InAppBrowser.isAvailable();
            const { type, url: newUrl } = await InAppBrowser.openAuth(url, redirectUrl, {
                showTitle: false,
                enableUrlBarHiding: true,
                enableDefaultShare: false,
                ephemeralWebSession: true
            });
            const splitUrl = `${redirectUrl}?${newUrl.split('#_=_')[0].split('?')[1] || ''}`;
            if (type === 'success') {
                Linking.openURL(splitUrl);
            }
        }


package.json
"react": "16.13.1",
"react-native": "0.64.2",
"react-native-inappbrowser-reborn": "3.7.0"

**Comment by codal-mpawar** [comment]
@jdnichollsc @vincent-paing @chrismerino Can you please help me on this..

**Comment by jdnichollsc** [comment]
We'are not using embedded webviews in this project, check the README of the repo https://github.com/proyecto26/react-native-inappbrowser#authentication
