### ISSUE TITLE
Apple rejected due to promoting third party game streaming

### ISSUE THREAD

**Issue by hemangcadscripts** [proyecto26/react-native-inappbrowser#418]
I am using this library for sign-in and sign-up purpose through Azure Ad B2C via sign-in-with-goole and sign-in-with-apple.
But apple rejecting app due to loading webview of external content within app for the purpose of third party game streaming.
So is there anything in this library that rendering any third party game streaming content ?
<img width="1369" alt="Screenshot 2023-06-10 at 11 50 43 AM" src="https://github.com/proyecto26/react-native-inappbrowser/assets/131642253/f5a3edab-30e2-4f7a-b89b-b3df08a3d289">

**Comment by jdnichollsc** [comment]
This lib is not using Webview, please check the native APIs and let me know!
