### ISSUE TITLE
[TypeError: Cannot read property 'isAvailable' of null]

### ISSUE THREAD

**Issue by sarvold** [proyecto26/react-native-inappbrowser#434]
Hi, I found no solutions on the issues already reported. I'm using expo CLI.

```
"dependencies": {
    "expo": "~49.0.7",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-inappbrowser-reborn": "^3.7.0"
  },
```
Create Expo app, install react-native-inappbrowser, 
import InAppBrowser from 'react-native-inappbrowser-reborn'; and code something implementing it, e.g. including something like `if (await InAppBrowser.isAvailable()) {`.
 Start the expo app and test it on any device. Error thrown:
 `[TypeError: Cannot read property 'isAvailable' of null]`
If console logging `InAppBrowser`, it happens to be an object as follows:
`{"close": [Function close], "closeAuth": [Function closeAuth], "isAvailable": [Function isAvailable], "mayLaunchUrl": [Function mayLaunchUrl], "open": [Function open], "openAuth": [Function openAuth], "warmup": [Function warmup]}`

Demo app: https://github.com/sarvold/inappBrowser-expo-app

Reproduces on Macs M2 on android and iOS, both emulators and devices with expo.

**Comment by odera89** [comment]
Same problem for me

**Comment by texmex44** [comment]
Same here on Android

**Comment by magutierrezApply** [comment]
Same problem

**Comment by jarkkotuovinen** [comment]
Had similar problem in circleci. Downgrading node to 18.18.1 seemed to be a workaround 🤷‍♂️

**Comment by GatienBoquet** [comment]
Same issue.
Looking for alternative at the moment =/

**Comment by jdnichollsc** [comment]
Why you are using this lib with Expo?

**Comment by davidli09991** [comment]
Same issue on iOS

"react": "18.2.0",
"react-native": "0.72.6",
"react-native-inappbrowser-reborn": "^3.7.0"

**Comment by catrius** [comment]
I ran into the same problem. After spending some hours searching for a solution, I ended up using Expo's in app browser https://docs.expo.dev/guides/linking/#in-app-browsers.

**Comment by mattrltrent** [comment]
Try instead of `.isAvailable()` using `.isAvailable`.
