### ISSUE TITLE
Build Failed with react native 0.72.3

### ISSUE THREAD

**Issue by parmarrishi16** [proyecto26/react-native-inappbrowser#438]
I am using React native version 0.72.3
and 
FAILURE: Build failed with an exception.
react-native-inappbrowser-reborn: "^3.7.0", 
 when i uninstall  react-native-inappbrowser-reborn it's working but not with react-native-inappbrowser-reborn
 could you please look into it ?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > An issue was found when checking AAR metadata:

       1.  Dependency 'androidx.browser:browser:1.6.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
info Run CLI with --verbose flag for more details.

**Comment by esbenvb** [comment]
In `android/app/build.gradle` add this:

```
configurations.all {
   resolutionStrategy {
    force 'androidx.browser:browser:1.5.0'
   }
}
```

**Comment by parmarrishi16** [comment]
> In `android/app/build.gradle` add this:
> 
> ```
> configurations.all {
>    resolutionStrategy {
>     force 'androidx.browser:browser:1.5.0'
>    }
> }
> ```

**Comment by gabrielnascr** [comment]
any updates?

**Comment by parmarrishi16** [comment]
above solution was worked
