### ISSUE TITLE
Delete or block a session from a previous session

### ISSUE THREAD

**Issue by zvitek** [proyecto26/react-native-inappbrowser#448]
Hi, is there please an option to delete or not save a session within`openAuth`?
I can log into the app under multiple accounts, but when I want to enter another one, the original session exists and I can't log in.
I tried`closeAuth` but no change.

Thank you

**Comment by krini** [comment]
I didn't find a solution to get rid of the old session - but you can invalidate it yourself when logging out,

**Comment by zvitek** [comment]
What exactly do you mean? When I log in, the browser window closes and I can't log out without reopening the browser.

**Comment by krini** [comment]
yes, that is also what I mean. In webview the token is gone when you reopen it, and this is also the case for openAuth on iOS, however android remembers the data and you need to invalidate your token. Maybe you can invalidate it by calling the logout of your identity provider, or you need to reopen openAuth and invalidate the token in there.

**Comment by zvitek** [comment]
Ok, I'll try a similar workaround, even though I don't really like it :)
It is interesting that such a basic function as clear is missing.

Thank you!
