### ISSUE TITLE
Android - The browser closes when the application goes to the background

### ISSUE THREAD

**Issue by zvitek** [proyecto26/react-native-inappbrowser#449]
I use the browser to log into the application. While logging in the browser, the user has to exit the application (put it in the background) and confirm the login in another application. 
When they subsequently return, the browser is closed and they cannot complete the login.
This only happens on some Android phones like Samsung, Redmi etc.

Have you experienced similar behaviour?

Thank you

**Comment by AppSphere** [comment]
Yes we are also facing the same, and the worst is , in my case app is crashing.

**Comment by zvitek** [comment]
That's annoying,
I looked into the issues, but none of the advice helped.

We'll check it out with the Android developers, but I'm skeptical.

**Comment by zvitek** [comment]
So it was ultimately a problem in my configuration and it really helped to set 
`{
    forceCloseOnRedirection: false,
    showInRecents: true
}`

**Comment by vinaygregoryjohn183** [comment]
@AppSphere How did you solve the crash issue? Please do help...

**Comment by mochadwi** [comment]
fixed as well for me, also got the similar workaround mentioned in here: https://github.com/proyecto26/react-native-inappbrowser/issues/153#issuecomment-727833604
