### ISSUE TITLE
How to get the current url opened in InAppBrowser back to the app?

### ISSUE THREAD

**Issue by kardoqadir** [proyecto26/react-native-inappbrowser#46]
Is there anyway to copy the current opened url or after canceling return the to back to the  app?

**Comment by kardoqadir** [comment]
Is there anyone have a solution to my issue?

**Comment by jdnichollsc** [comment]
@kardoqadir it looks like this is not possible https://stackoverflow.com/questions/35160635/check-which-url-is-opened-in-custom-chrome-tabs

**Comment by jdnichollsc** [comment]
Sorry man, this is not possible by security concerns https://stackoverflow.com/questions/42192701/detect-url-change-in-sfsafariviewcontroller

**Comment by kardoqadir** [comment]
Thanks man... I looked something, in facebook app when you open a link no matter where you go, there is a button that let you to save the link.. Do you think they used safariviewcontrollee and chrom tabs? or they developed a special browser for them self?

**Comment by jdnichollsc** [comment]
@kardoqadir ok, so we need native code to create custom actions in order to do that:
```
It is possible to get the URL as a result of the user clicking on the custom action button or on one of the buttons on the secondary toolbar.
```
https://stackoverflow.com/a/49667027/1532821

**Comment by jdnichollsc** [comment]
iOS doesn't support this with the SafariViewController
