### ISSUE TITLE
Return `true` for Android

### ISSUE THREAD

**Issue by Kikketer** [proyecto26/react-native-inappbrowser#48]
[feature]
Currently when I run `isAvailable()` for Android it doesn't return, it simply doesn't throw an exception.
I was thinking perhaps this function could return a boolean value instead of possibly just throwing exceptions.

```
if(await InAppBrowser.isAvailable()) {
  await InAppBrowser.open(....
```

Instead of using a try catch to see if it's available.  I didn't get a chance to look at the iOS detection but I would think a general try/catch could handle it and resolve with false instead of throwing exceptions.

**Comment by jdnichollsc** [comment]
@Kikketer Any pull request is welcome! You can see the code from JS here https://github.com/proyecto26/react-native-inappbrowser/blob/master/index.js#L123
