### ISSUE TITLE
IOS Status bar style

### ISSUE THREAD

**Issue by EQuimper** [proyecto26/react-native-inappbrowser#5]
I see in your code you change the status bar color https://github.com/proyecto26/react-native-inappbrowser/blob/master/ios/RNInAppBrowser.m#L200 The thing about this is now we cannot manage the status bar color from react-native. I will like to use my own function from javascript. If I remove your code what I try to do work. I think people would like this. This way if they want dark or light style they have the control.

**Comment by jdnichollsc** [comment]
let me see after finish my vacations 👍

**Comment by jdnichollsc** [comment]
@EQuimper merged, thanks for your contributions my friend! 👍

**Comment by EQuimper** [comment]
Thank you :) @jdnichollsc You rock!!

**Comment by jdnichollsc** [comment]
We rock! haha
