### ISSUE TITLE
Start animation doesn't work

### ISSUE THREAD

**Issue by TheAlmightyBob** [proyecto26/react-native-inappbrowser#52]
Unlike #24, I am testing on Android, and simply using the example project from this repo. The _dismiss_ animations always _do_ work, but I've tried multiple devices & Android versions and showing the custom tab always uses the default animation (which itself varies by device).

(P.S. I had to modify the build.gradle of the example project in order to get it to build... I'm not sure why...
```
    implementation(project(':react-native-inappbrowser-reborn')) {
        exclude group: 'com.facebook.infer.annotation', module: 'infer-annotation'
    }
```
)

**Comment by jdnichollsc** [comment]
What animations do you have from your Android resources? Check the example of this project https://github.com/proyecto26/react-native-inappbrowser/tree/master/example/android/app/src/main/res/anim

**Comment by TheAlmightyBob** [comment]
As I said in the description, this problem is happening _with the example for this project_.

**Comment by jdnichollsc** [comment]
Let me check, any pull request is welcome!

**Comment by TheAlmightyBob** [comment]
Unfortunately I'm not sure what the problem is or how to fix it. From the research I've done, I would expect what you have to work... And it seems unlikely that Android would have stopped supporting this functionality...

**Comment by jdnichollsc** [comment]
Done! Thanks @miktolon for your help! 🥇
