### ISSUE TITLE
Give the option of opening as push instead of modal

### ISSUE THREAD

**Issue by brunolemos** [proyecto26/react-native-inappbrowser#56]
I see you are forcing it to open as a modal (iOS and Android). Ideally this should be a user's decision, like the `fromBottom` option of https://github.com/naoufal/react-native-safari-view.

https://github.com/proyecto26/react-native-inappbrowser/blob/f5d47e2fb3a8ced67752574a5ddf62fd68feb18d/ios/RNInAppBrowser.m#L123-L126

https://github.com/proyecto26/react-native-inappbrowser/blob/a6a5b3e3838789c103f3c71e7a7773fb35594d0b/ios/RNInAppBrowser.m#L128-L132

**Comment by jdnichollsc** [comment]
And Android? Any pull request is welcome!

**Comment by 3luyka** [comment]
@jdnichollsc please make it at least for iOS :)

**Comment by jdnichollsc** [comment]
@3luyka any pull request is welcome 👍

**Comment by erikvdplas** [comment]
Any updates on this?

**Comment by jdnichollsc** [comment]
I was testing but I have an error, if you want I can create a feature branch and you can help me to inspect the issue in that branch 😅

**Comment by jdnichollsc** [comment]
@brunolemos @3luyka @erikvdplas guys, check the last version from master branch and let me know :)
The new iOS property is `modalEnabled` 👍
