### ISSUE TITLE
Help with closing the InAppBrowser when registration flow is done (RNN)

### ISSUE THREAD

**Issue by kneza23** [proyecto26/react-native-inappbrowser#57]
Hi, i know that this is not the place for asking help implementing stuff. But i have app with React Native Navigation https://wix.github.io/react-native-navigation/#/. 

I need `InAppBrowser` to open registration form on the web, check for success of the registration flow and then close the `InAppBrowser`.

Everything is good on both platform regarding showing the browser. But right now i don't really know how to detect when registration flow on the web is done so i can close the browser and let the user login with the app.

I have looked into the Linking https://facebook.github.io/react-native/docs/linking.html but still not really sure how i can add functionality to my website to tell my app just to close the the `InAppBrowser`.

Thanks for any help.

```
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 66.01 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.2, 28.0.3
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by jdnichollsc** [comment]
From your website you need to redirect to the app again using deep linking 👍
