### ISSUE TITLE
Android: Set orientation to Landscape

### ISSUE THREAD

**Issue by ankit18singh** [proyecto26/react-native-inappbrowser#59]
Hello,

The plugin works great in portrait mode, which is set to default.
In my app there is a requirement to play HTML5 games in landscape mode, but this plugin does not provide this option.
In iOS setting the default app orientation to landscape allows the inappbrowser to open in landscape mode, but same is not in the case of android.

Note: I have already added screenOrientation in AndroidManifest.xml
```
            android:screenOrientation="sensorLandscape"
```

**Comment by jdnichollsc** [comment]
@ankit18singh can you try this? https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock

**Comment by jdnichollsc** [comment]
@ankit18singh On the other hand, let me know about the performance integrating HTML5 games with an embedded browser, I have experience with Phaser Framework and PhoneGap/Cordova, but the performance from Android is horrible :/ 
Example: https://github.com/jdnichollsc/IonPhaser

**Comment by jdnichollsc** [comment]
`Custom Tabs does not currently provide an API that allows the developer to lock the orientation` => https://stackoverflow.com/questions/38231103/lock-orientation-for-custom-tabs
