### ISSUE TITLE
Library size has exploded

### ISSUE THREAD

**Issue by PierreCapo** [proyecto26/react-native-inappbrowser#61]
Hello, since the last version (2.0.0) when I use yarn to install this package, it takes a lot of times to download it. After investigating, it turns out : https://registry.yarnpkg.com/react-native-inappbrowser-reborn/-/react-native-inappbrowser-reborn-2.0.0.tgz is more than 100 Mb.

Could you check if you didn't add node_modules into the npm release for instance ? I suppose that is the origin of this large size.

**Comment by jdnichollsc** [comment]
Check the last version 2.0.1 👍

**Comment by jdnichollsc** [comment]
Let me know because I'm not sure with this, the command that I use is `npm publish` and that's it

**Comment by PierreCapo** [comment]
Hello !
Perfect the size is now ok on 2.0.1 version
Thanks a lot
