### ISSUE TITLE
target="_blank" not work on iOS

### ISSUE THREAD

**Issue by d2luu** [proyecto26/react-native-inappbrowser#63]
I have a problem with a link has target="_blank" property.
I can only click one single target="_blank" link. When clicking another target="_blank" link on this page (was opened by target="_blank") this won't work.
How can I fix it?

Maybe cause by SFSafariViewController?
https://stackoverflow.com/questions/53701940/target-blank-links-not-opening-in-sfsafariviewcontroller

**Comment by jdnichollsc** [comment]
I'm not sure, I need to review that. Any pull request is welcome in the meantime! 👍

**Comment by jdnichollsc** [comment]
Yeah, this issue is caused by `SFSafariViewController`, I can't see any solution :/
