### ISSUE TITLE
undefined is not an object 

### ISSUE THREAD

**Issue by livindead** [proyecto26/react-native-inappbrowser#69]
Hello
I am use example 

`async openLink() {
    try {
      const url = 'https://www.google.com'
      if (await InAppBrowser.isAvailable()) {
        const result = await InAppBrowser.open(url, {
          // iOS Properties
          dismissButtonStyle: 'cancel',
          preferredBarTintColor: 'gray',
          preferredControlTintColor: 'white',
          readerMode: false,
          // Android Properties
          showTitle: true,
          toolbarColor: '#6200EE',
          secondaryToolbarColor: 'black',
          enableUrlBarHiding: true,
          enableDefaultShare: true,
          forceCloseOnRedirection: false,
          // Specify full animation resource identifier(package:anim/name)
          // or only resource name(in case of animation bundled with app).
          animations: {
            startEnter: 'slide_in_right',
            startExit: 'slide_out_left',
            endEnter: 'slide_in_left',
            endExit: 'slide_out_right'
          },
          headers: {
            'my-custom-header': 'my custom header value'
          },
        })
        Alert.alert(JSON.stringify(result))
      }
      else Linking.openURL(url)
    } catch (error) {
      console.log(error.message)
    }
  }`
This show error
undefined is not an object (evaluating 'RNInAppBrowser.isAvailable')

**Comment by jdnichollsc** [comment]
RNInAppBrowser is undefined only if this library is not installed correctly :)

**Comment by mouradkaroudi** [comment]
I have same problem however I followed install steps like you explain !!!

**Comment by jdnichollsc** [comment]
@mouradkaroudi any pull request is always welcome, this is a community plugin 👍
