### ISSUE TITLE
When you call openAuth the styling options are not applied

### ISSUE THREAD

**Issue by kneza23** [proyecto26/react-native-inappbrowser#72]
Example of my code:

`  const result = await InAppBrowser.openAuth(url + `&redirect_uri=${deepLink}`, deepLink, {
        dismissButtonStyle: "close",
        preferredBarTintColor: "white",
        preferredControlTintColor: colors.primaryOrange,
        showTitle: true,
        toolbarColor: "white",
        secondaryToolbarColor: "white",
        enableUrlBarHiding: true,
        enableDefaultShare: true,
        forceCloseOnRedirection: false
      });`

When you call just open, it works and the styles are there.

**Comment by jdnichollsc** [comment]
From iOS we can't add options using authentication services as you can see here => https://stackoverflow.com/a/51043114/1532821
