### ISSUE TITLE
How to set one default browser?

### ISSUE THREAD

**Issue by Sengg** [proyecto26/react-native-inappbrowser#74]
How can i set only chrome or default system browser?

**Comment by jdnichollsc** [comment]
We can't with the current code of this plugin, but any pull request is welcome! 👍

**Comment by sa0sh0iip** [comment]
@jdnichollsc

Can this still not be done?

We need to use https://play.google.com/store/apps/details?id=com.airwatch.browser as our default browser. i found there is a prop `browserPackage` which needs id of the browser package (in my case `'com.airwatch.browser'`). Yet, I am being asked to select between Chrome and Web - Workspace ONE.

Any pointers?

I tested by setting `browserPackage` prop to  `'com.airwatch.browser'` on your example app. Links open Web - Workspace ONE without selection window.

**Comment by jdnichollsc** [comment]
Hello @sa0sh0iip,
Please attach a reproducible demo to be able to debug your issue 👍 

Best,
Juan
