### ISSUE TITLE
How to hide the address bar?

### ISSUE THREAD

**Issue by duycoder** [proyecto26/react-native-inappbrowser#75]
I wan't my app to go full screen mode right after it's on. I didn't find any option to hide the address bar! How can i do that?

**Comment by jdnichollsc** [comment]
Let me know if you can find that option from the official documentation:
- Android: https://developer.chrome.com/multidevice/android/customtabs#whatarethey
- iOS: https://developer.apple.com/documentation/safariservices and https://developer.apple.com/documentation/authenticationservices
Regards

**Comment by jdnichollsc** [comment]
@duycoder in what platform? Android?

**Comment by AreebVohra** [comment]
i need to hide the top bar in android
![Screenshot_1582117463](https://user-images.githubusercontent.com/34376767/74837036-6ecb8500-5342-11ea-9257-83c9a73f7f40.png)

**Comment by jdnichollsc** [comment]
@AreebVohra so it looks like you need to use webview instead => https://github.com/react-native-community/react-native-webview

**Comment by ASakkeer** [comment]
Same issue here!. Did anyone get a solution?.

**Comment by JRamonMC** [comment]
Any update? Same issue here

**Comment by jdnichollsc** [comment]
Any pull request is welcome! 🙂

**Comment by digitlninja** [comment]
Hi, we're also needing the ability to hide the bar. This is a very useful and needed capability as many who use this browser want it to appear to the user as if they're 100% in the app and not the internet.

Please advise :)

**Comment by jdnichollsc** [comment]
I'm not sure if that's supported by **ChromeCustomTabs**, please review the links I shared before and let me know 🙂

**Comment by arjun-mavonic** [comment]
@jdnichollsc Here is a link to how we can achieve the feature people are requesting. It's Trusted Web Activity. It allows us to open a custom tab without any of the browser UI.
https://developer.chrome.com/docs/android/custom-tabs/#when-should-i-use-custom-tabs-vs-trusted-web-activity
