### ISSUE TITLE
Add method to clear cookies

### ISSUE THREAD

**Issue by jamalneufeld** [proyecto26/react-native-inappbrowser#76]
There's an issue using this view with many oauth providers because the cookies are all encapsulated in this instance of the browser. The user can't simply log out in their regular browser.

With enterprise SSO providers this gets worse since they sometimes provide oauth logins through their website and even if one were to use their logout url, it doesn't log out the oauth provider.

The best solution here would be to clear the cookies. If the user tries to log in again, they're forced to actually enter credentials. Otherwise oauth just logs them right back in and it's as if they never logged out.

Can this be done here?

**Comment by jdnichollsc** [comment]
I'm not sure, can you see any method from the official documentation? 
- Android: https://developer.chrome.com/multidevice/android/customtabs#whatarethey
- iOS: https://developer.apple.com/documentation/authenticationservices
We're using authentication with okta without cookies, using JWT tokens in the headers of the requests :)

**Comment by jamestri-nandos** [comment]
Hi,

ephemeralWebSession doesn't seem to be working for me. Is there a problem with it in the simulator?

**Comment by jdnichollsc** [comment]
Ohh let me publish the new version with this fix => https://github.com/proyecto26/react-native-inappbrowser/compare/v3.3.4...HEAD

**Comment by jamestri-nandos** [comment]
Great thanks!

**Comment by jdnichollsc** [comment]
Ok, check the new version `3.4.0` 👍

**Comment by therealtgd** [comment]
Is there any solution for Android?

**Comment by amaury-soto** [comment]
Any solved to Android, some similar option as ephemeralWebSession to Android ?
