### ISSUE TITLE
Do you have any plans to migrate to AndroidX?

### ISSUE THREAD

**Issue by cheolheon** [proyecto26/react-native-inappbrowser#77]
Hi, React Native 0.60 was just released before few minutes.

As you know, RN 0.60 migrates their `com.android.support.*` to AndroidX. And It means `react-native-inappbrowser` should migrate to AndroidX too because this module is using `com.android.support:support-annotations` and `com.android.support:customtabs` now and it means `react-native-inappbrowser` cannot be used on React Native 0.60 projects.

So I wonder you have any plans to migrate to AndroidX because I couldn't find any information that this module will support AndroidX anywhere.

Thank you.

**Comment by jdnichollsc** [comment]
yes, maybe this weekend, in the meantime any pull request is welcome! 👍

**Comment by jdnichollsc** [comment]
@cheolheon do you know if we need to add maven repository from **buildscript**? example: https://github.com/proyecto26/react-native-inappbrowser/blob/master/android/build.gradle#L5
Or using maven `{ url 'https://maven.google.com' }` instead? 
Thanks in advance

**Comment by jdnichollsc** [comment]
ohh ok, it looks like the same for me

**Comment by jdnichollsc** [comment]
@cheolheon in the meantime you can point to the github repo directly https://github.com/proyecto26/react-native-inappbrowser
Let me know please 👍

**Comment by cheolheon** [comment]
@jdnichollsc 
Hey, sorry for late check. 

I've run RN 0.60 with https://github.com/proyecto26/react-native-inappbrowser master branch(version AndroidX), and It works fine! 👍

![androidx](https://user-images.githubusercontent.com/38815423/60952406-31c3fc80-a336-11e9-874b-78e746114f7d.gif)

Thank you very much!

I think it should be major release due to removing confusion to its user.
What can I do for you more?

**Comment by jdnichollsc** [comment]
I'm creating a `CHANGELOG` of the project before to publish the new version `v3.0.0` 👍 https://github.com/proyecto26/react-native-inappbrowser/blob/master/CHANGELOG.md

**Comment by dsah** [comment]
it doesn't work in android with RN 0.60 because of androidX. Ios is fine though.

**Comment by jdnichollsc** [comment]
Done! https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.0.0
