### ISSUE TITLE
Android - how to know when the browser was closed by user?

### ISSUE THREAD

**Issue by mlazari** [proyecto26/react-native-inappbrowser#8]
I have an intent filter like this in my Android app:

```
<activity
        android:name=".MainActivity"
        ...
>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="myapp" android:host="test" />
        </intent-filter>
        ...
</activity>
```

If I open the browser a page that redirects to `myapp://test` the browser is dismissed and the result type is `"cancel"`, which makes impossible to distinguish this situation from the situation when the user closed the browser manually.

```
props.openOAuthUrl(urlThatRedirectsToApp).then((result) => {
  console.log(result); // { type: 'cancel' }, but probably it should be { type: 'dismiss' } so I can know that the user did not close the browser manually
});
```

The promise is resolved with `{ type: 'cancel' }` here when the browser activity is destroyed: https://github.com/proyecto26/react-native-inappbrowser/blob/af97246081cf5678eeebb9e12262cdf03385eb8b/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java#L121

On iOS when the browser redirects to `myapp://test` the browser is not dismissed automatically. Instead I detect with Linking that the app was opened with that url, and close the browser from there, which I think is fine:
```
Linking.addEventListener('url', (url) => {
  InAppBrowser.close();
  console.log('URL: ', url);
});
```

**Comment by jdnichollsc** [comment]
Check the documentation of the WebBrowser https://docs.expo.io/versions/latest/sdk/webbrowser#returns

If you want you can propose the change with a pull request to include that into the documentation too (README)

**Comment by mlazari** [comment]
@jdnichollsc I'm not using Expo, but using this module this seems to be true only for iOS:
> When the listener fires, you should call WebBrowser.dismissBrowser() -- it will not automatically dismiss when a deep link is handled.

On Android it's dismissed automatically, but the promise resolves with `{type: 'cancel'}` instead of `{type: 'dismiss'}`, no matter if I call `InAppBrowser.close();` or not. On iOS it's resolved with `{type: 'dismiss'}` when it's closed with `InAppBrowser.close();`.

Here is a minimal example that reproduces the issue: https://github.com/mlazari/in-app-browser-my-app
And here is the difference between the behaviour on iOS and on Android:
![android-vs-ios](https://user-images.githubusercontent.com/4928274/46535691-e23b3680-c8b4-11e8-84d6-e73d2a6bb10a.gif)

**Comment by mlazari** [comment]
@jdnichollsc I opened a pull request https://github.com/proyecto26/react-native-inappbrowser/pull/9
Can you please review it? With that fix the result type is the same as on iOS.

**Comment by jdnichollsc** [comment]
@mlazari thanks for your excellent contribution!

**Comment by mlazari** [comment]
@jdnichollsc No problem. Thanks.
