### ISSUE TITLE
Add .npmignore to remove examples from node_modules

### ISSUE THREAD

**Issue by kirill3333** [proyecto26/react-native-inappbrowser#82]
Hi, I've found that your package contains example folder. It takes a lot of space on the hard disk.

For example, my folder:

<img width="929" alt="Screenshot 2019-07-19 at 11 09 11" src="https://user-images.githubusercontent.com/1804678/61519884-aae9e080-aa15-11e9-95e1-a64f66024e19.png">

here you can find how to use npmignore https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by jdnichollsc** [comment]
Yes, you're right! Let me publish the version 3.0.0 with that file, thanks!

**Comment by jdnichollsc** [comment]
Check https://github.com/proyecto26/react-native-inappbrowser/blob/master/.npmignore
