### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNInAppBrowser.open')

### ISSUE THREAD

**Issue by EmmanuelID** [proyecto26/react-native-inappbrowser#83]
Install version 2.0.4 and link the library with react-native link

`openUrl = async (url) => {
  try {
    if(await InAppBrowser.isAvailable()){
      await InAppBrowser.open(url, {
        // iOS Properties
        dismissButtonStyle: 'cancel',
        preferredBarTintColor: 'gray',
        preferredControlTintColor: 'white',
        readerMode: false,
        // Android Properties
        showTitle: true,
        toolbarColor: '#6200EE',
        secondaryToolbarColor: 'black',
        enableUrlBarHiding: true,
        enableDefaultShare: true,
        forceCloseOnRedirection: false,
        // Specify full animation resource identifier(package:anim/name)
        // or only resource name(in case of animation bundled with app).
        animations: {
          startEnter: 'slide_in_right',
          startExit: 'slide_out_left',
          endEnter: 'slide_in_left',
          endExit: 'slide_out_right'
        },
        headers: {
          'my-custom-header': 'my custom header value'
        },
      })
    }
  } catch (error) {
    console.log('====================================');
    console.log(error);
    console.log('====================================');
  }`

And the catch error shows:
[TypeError: null is not an object (evaluating 'RNInAppBrowser.open')]
line: 176895,
column: 60,
sourceURL: 'http://localhost:8081/index.delta?platform=android&dev=true&minify=false'

> React native version: 0.59.9
> Platform: Android

**Comment by jdnichollsc** [comment]
try linking manually 👍

**Comment by nihp** [comment]
I have linked it via manually but the above error exist while try to open url

**Comment by jdnichollsc** [comment]
@nihp what version of RN are you using?

**Comment by nihp** [comment]
I am using RN 0.58.4

**Comment by fernando-pascoal** [comment]
I have some problem now

**Comment by anshgupta1234** [comment]
I'm still getting this problem with this code: 

`if (isAvailable) {
        InAppBrowser.open(url, {
          // iOS Properties
          dismissButtonStyle: 'cancel',
          preferredBarTintColor: 'gray',
          preferredControlTintColor: 'white',
          // Android Properties
          showTitle: true,
          toolbarColor: '#6200EE',
          secondaryToolbarColor: 'black',
          enableUrlBarHiding: true,
          enableDefaultShare: true,
          forceCloseOnRedirection: true,
        }).then((result) => {
          Alert.alert(JSON.stringify(result))
        })
      } else Linking.openURL(url)`

**Comment by jdnichollsc** [comment]
Hello guys, check here! let me know if you're installing pods and share the logs please https://github.com/proyecto26/react-native-inappbrowser/issues/126#issuecomment-616621415

**Comment by thribhu** [comment]
@jdnichollsc I face the same issues with RN 0.61.5. I have tried manual linking though and no luck. Any idea on what is causing this?
![image](https://user-images.githubusercontent.com/17533126/86087938-f5e3f300-bac2-11ea-8cd0-00b7f2268542.png)
