### ISSUE TITLE
Does not work on android for react-native 0.59

### ISSUE THREAD

**Issue by michaelfemi81** [proyecto26/react-native-inappbrowser#89]
Please I don't intend to migrate to android x in my current project how do I Get it to work

**Comment by jdnichollsc** [comment]
Continue using the previous version 2.0.4 👍

**Comment by michaelfemi81** [comment]
Thanks works now, seems that version doesn't support animations

**Comment by jdnichollsc** [comment]
Nope, only the new one :)
