### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by marcoizzo** [proyecto26/react-native-inappbrowser#90]
Packages:

> "react": "16.8.3",
> "react-native": "0.59.9",
> "react-native-firebase": "^5.4.3",
> "react-native-inappbrowser-reborn": "^3.0.0",

Hi all,

I get this error during the build:
```
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.
```

Any suggestions? :)

**Comment by jdnichollsc** [comment]
Try upgrading to react-native >= 0.60 and remember update your configuration to support AndroidX, check the breaking changes with the version 3.0.0 => https://github.com/proyecto26/react-native-inappbrowser/blob/master/CHANGELOG.md#300---2019-07-27
Otherwise, you can use the last version 2.0.4 👍
