### ISSUE TITLE
Additional check for isAvailable() on Android

### ISSUE THREAD

**Issue by bhargav-vasist** [proyecto26/react-native-inappbrowser#91]
Just wanted to start off by saying this library has been great for solving some auth concerns we had in our code so thank you!

Right now the check assumes that all Android devices support Custom Tabs, however AFAIK, in cases wherein the device does not have a Chromium flavored browser installed, a Chrome Custom Tab instance cannot be opened.
An additional intent based service check might be needed to check the extent of the support available.
[This answer on Stackoverflow might give more context](https://stackoverflow.com/a/33041870)

**Comment by jdnichollsc** [comment]
Interesting, let me check 👍

**Comment by bhargav-vasist** [comment]
If you need any help with a PR, I'd be more than willing to submit one  👍

**Comment by jdnichollsc** [comment]
ohh yes please, I'm a little busy right now, but any pull request is always welcome, thanks!! 👍

**Comment by wong2** [comment]
yes many devices of my users don't have a chrome browser installed

**Comment by jdnichollsc** [comment]
Please debug the last changes from `develop` branch, there's a pending PR of the new version 3.5.0 https://github.com/proyecto26/react-native-inappbrowser/pull/195

**Comment by jdnichollsc** [comment]
@wong2 what do you think about this other idea? adding other packages that supports custom tabs https://github.com/proyecto26/react-native-inappbrowser/pull/157/files#diff-78dea708a38f9ddae320d241d7136ca6d38f9ec1bea0275bf062638449b5ff4aR20
