### ISSUE TITLE
postMessage / onMessage equivalent?

### ISSUE THREAD

**Issue by matttturnbull** [proyecto26/react-native-inappbrowser#92]
Hey there, loving your module so far, thanks for building!

I'm making an app that launches InAppBrowser, goes through a web flow, and then ideally needs to send a message (from the web js) back to the React Native app that a process has completed successfully. It's just a series of web pages that would ideally finish in a message sent from the web js back to the app (at which point I plan to close the InAppBrowser window, etc).

The closest I can think of is react-native-webview's onMessage event, which enables you to interface between the web page that's being rendered, through the module to the app. Is there an equivalent for InAppBrowser? Apologies if I'm missing something obvious!

**Comment by jdnichollsc** [comment]
Here you need to redirect to the app again using deep linking (302 redirection), you can use query string params to send data to the app if you want, check the example: https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/App.js#L104

**Comment by matttturnbull** [comment]
Legend, thanks so much for the nudge!
