### ISSUE TITLE
How to close inappbrowser and trigger success

### ISSUE THREAD

**Issue by moak** [proyecto26/react-native-inappbrowser#99]
I am having hard time trying to use [inappbrowser][1] in my react native app. 

I have to login on a specific URL on the web from a native app so I decided to embed a browser in the app using inappbrowser and then open the login web url which is a react app. To do this, I do the following:

     try {
      await InAppBrowser.isAvailable();
      InAppBrowser.open(
        'http://loginUrl/login',
        {
          // iOS Properties
          dismissButtonStyle: 'cancel',
          readerMode: false,
          modalPresentationStyle: 'overFullScreen',
          modalTransitionStyle: 'partialCurl',
          modalEnabled: true,
          animated: false,
        },
      ).then(result => {
        alert(JSON.stringify(result));
      });
    } catch (error) {
      alert(error.message);
    }

The inappbrowser successfully opens and I can login from there. 

Here is my question: **How can I close this inappbrowser on login success to go back ?** 

I tried with deeplink to either redirect on the web or on the app depending on the platform I come from with the following code:

    if (origin === 'web') { 
       // web redirect
       window.location = 'http://ip/loginSucess';
    } else {
       // mobile deeplink redirect
       window.location = 'mobApp://app/routing?screen=app/loginSucess';
    }

The problem is that I am already on the app when I am on the login form so it does nothing, it doesnt close the browser. It actually works when I login on my phone with safari, then I am correctly redirected to the app using the deeplink.

I only get the **then result alert** when I press cancel in the inappbrowser but I don't know how to trigger a success or anything ..

Have somebody met the problem before ? It seems impossible to use this package without url control or success callback. 

  [1]: https://github.com/proyecto26/react-native-inappbrowser

**Comment by jdnichollsc** [comment]
Try openAuth method 👍
